In [1]:
import pandas as pd
import os
import numpy as np

In [2]:
os.getcwd()

'/Users/chuqiwang/Documents/US_PFAS_Project/data_cleaning/Maine'

In [3]:
me_df1 = pd.read_excel('Export_Brunswick NAS.xlsx')

In [4]:
me_df1

,Component ID,Component,State,Installation Name,Installation Type,Lab Report Id,Laboratory Sample ID,Sample Date,Analysis Method,CAS Number,Analyte Abbreviation,Final Result,Limit of Detection,Final Units,Final Qualification,Treatment System,Pre Or Post Treatment
0,1700,Navy,Maine,Brunswick NAS,BRAC,21-1421,F4748-FS,10/19/2021,537.1,13252-13-6,HFPO-DA,NaN,1.320,ng/L,U,No,NaN
1,1700,Navy,Maine,Brunswick NAS,BRAC,21-1421,F4748-FS,10/19/2021,537.1,1763-23-1,PFOS,4.79,1.320,ng/L,NaN,No,NaN
2,1700,Navy,Maine,Brunswick NAS,BRAC,21-1421,F4748-FS,10/19/2021,537.1,2058-94-8,PFUnA,NaN,1.320,ng/L,U,No,NaN
3,1700,Navy,Maine,Brunswick NAS,BRAC,21-1421,F4748-FS,10/19/2021,537.1,2355-31-9,NMeFOSAA,NaN,1.320,ng/L,U,No,NaN
4,1700,Navy,Maine,Brunswick NAS,BRAC,21-1421,F4748-FS,10/19/2021,537.1,2991-50-6,NEtFOSAA,NaN,1.590,ng/L,U,No,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
535,1700,Navy,Maine,Brunswick NAS,BRAC,22-0491,F9632-FS1,3/23/2022,537.0,376-06-7,PFTeDA,NaN,1.240,ng/L,UJ,No,NaN
536,1700,Navy,Maine,Brunswick NAS,BRAC,22-0491,F9632-FS1,3/23/2022,537.0,72629-94-8,PFTrDA,NaN,1.240,ng/L,UJ,No,NaN
537,1700,Navy,Maine,Brunswick NAS,BRAC,22-0491,F9632-FS1,3/23/2022,537.0,756426-58-1,9Cl-PF3ONS,NaN,1.240,ng/L,U,No,NaN
538,1700,Navy,Maine,Brunswick NAS,BRAC,22-0491,F9632-FS1,3/23/2022,537.0,763051-92-9,11Cl-PF3OUdS,NaN,1.240,ng/L,U,No,NaN
539,1700,Navy,Maine,Brunswick NAS,BRAC,22-0491,F9632-FS1,3/23/2022,537.0,919005-14-4,ADONA,NaN,0.988,ng/L,U,No,NaN

In [5]:
columns = {
    'sample_id': str,
    'sampling_location': str,
    'data_source': str,
    'latitude': float,
    'longitude': float,
    'sampling_date': 'datetime64[ns]',
    'pws_id': str,
    'water_system_name': str,
    'population': int,
    'well_type': str,
    'well_depth': float,
    'units': str,
    'source_type': str,
    'state': str,
    'city': str,
    'county': str,
    'MRL': float,
    'DL': float,
    'analytical_methods': str,
    'is_detected': bool,
    'analyte': str,
    'concentration': float,
    'pfas_total': float,
    'note': str   
}

In [6]:
df1 = pd.DataFrame({col: pd.Series(dtype=dt) for col, dt in columns.items()})

In [7]:
df1['analyte'] = me_df1['Analyte Abbreviation'].str.upper()
df1['concentration'] = me_df1['Final Result'].fillna(0)
df1['sampling_location'] = me_df1['Installation Name']
df1['DL'] = me_df1['Limit of Detection']
df1['sampling_date'] = pd.to_datetime(me_df1['Sample Date'])
df1['sample_id'] = me_df1['Laboratory Sample ID']
df1['units'] = me_df1['Final Units']
df1['state'] = me_df1['State']
df1['analytical_methods'] = me_df1['Analysis Method']
df1['data_source'] = 'DoD'
df1['source_type'] = 'drinking water'

In [8]:
df1['is_detected'] = df1['concentration'] != 0

In [9]:
df1

,sample_id,sampling_location,data_source,latitude,longitude,sampling_date,pws_id,water_system_name,population,well_type,...,city,county,MRL,DL,analytical_methods,is_detected,analyte,concentration,pfas_total,note
0,F4748-FS,Brunswick NAS,DoD,NaN,NaN,2021-10-19,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.320,537.1,False,HFPO-DA,0.00,NaN,NaN
1,F4748-FS,Brunswick NAS,DoD,NaN,NaN,2021-10-19,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.320,537.1,True,PFOS,4.79,NaN,NaN
2,F4748-FS,Brunswick NAS,DoD,NaN,NaN,2021-10-19,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.320,537.1,False,PFUNA,0.00,NaN,NaN
3,F4748-FS,Brunswick NAS,DoD,NaN,NaN,2021-10-19,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.320,537.1,False,NMEFOSAA,0.00,NaN,NaN
4,F4748-FS,Brunswick NAS,DoD,NaN,NaN,2021-10-19,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.590,537.1,False,NETFOSAA,0.00,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
535,F9632-FS1,Brunswick NAS,DoD,NaN,NaN,2022-03-23,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.240,537.0,False,PFTEDA,0.00,NaN,NaN
536,F9632-FS1,Brunswick NAS,DoD,NaN,NaN,2022-03-23,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.240,537.0,False,PFTRDA,0.00,NaN,NaN
537,F9632-FS1,Brunswick NAS,DoD,NaN,NaN,2022-03-23,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.240,537.0,False,9CL-PF3ONS,0.00,NaN,NaN
538,F9632-FS1,Brunswick NAS,DoD,NaN,NaN,2022-03-23,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.240,537.0,False,11CL-PF3OUDS,0.00,NaN,NaN
539,F9632-FS1,Brunswick NAS,DoD,NaN,NaN,2022-03-23,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.988,537.0,False,ADONA,0.00,NaN,NaN

In [10]:
me_df2 = pd.read_excel('Export_Loring AFB.xlsx')

In [11]:
me_df2

,Component ID,Component,State,Installation Name,Installation Type,Lab Report Id,Laboratory Sample ID,Sample Date,Analysis Method,CAS Number,Analyte Abbreviation,Final Result,Limit of Detection,Final Units,Final Qualification,Treatment System,Pre Or Post Treatment
0,5700,Air Force,Maine,Loring AFB,BRAC,2110182,2110182-05,10/20/2021,QSM_B15,757124-72-4,4:2FTS,NaN,1.89,ng/L,U,No,NaN
1,5700,Air Force,Maine,Loring AFB,BRAC,2110182,2110182-05,10/20/2021,QSM_B15,27619-97-2,6:2FTS,NaN,1.89,ng/L,U,No,NaN
2,5700,Air Force,Maine,Loring AFB,BRAC,2110182,2110182-05,10/20/2021,QSM_B15,39108-34-4,8:2FTS,NaN,1.89,ng/L,U,No,NaN
3,5700,Air Force,Maine,Loring AFB,BRAC,2110182,2110182-05,10/20/2021,QSM_B15,2991-50-6,NEtFOSAA,NaN,1.89,ng/L,U,No,NaN
4,5700,Air Force,Maine,Loring AFB,BRAC,2110182,2110182-05,10/20/2021,QSM_B15,2355-31-9,NMeFOSAA,NaN,1.89,ng/L,U,No,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2056,5700,Air Force,Maine,Loring AFB,BRAC,C449535,YKI774,2/15/2024,1633,79780-39-5,PFDoS,NaN,0.90,ng/L,U,No,NaN
2057,5700,Air Force,Maine,Loring AFB,BRAC,C449535,YKI774,2/15/2024,1633,812-70-4,7:3FTCA,NaN,28.00,ng/L,U,No,NaN
2058,5700,Air Force,Maine,Loring AFB,BRAC,C449535,YKI774,2/15/2024,1633,863090-89-5,PFMBA,NaN,0.45,ng/L,U,No,NaN
2059,5700,Air Force,Maine,Loring AFB,BRAC,C449535,YKI774,2/15/2024,1633,914637-49-3,5:3FTCA,NaN,28.00,ng/L,U,No,NaN
2060,5700,Air Force,Maine,Loring AFB,BRAC,C449535,YKI774,2/15/2024,1633,919005-14-4,ADONA,NaN,3.40,ng/L,U,No,NaN

In [12]:
df2 = pd.DataFrame({col: pd.Series(dtype=dt) for col, dt in columns.items()})
df2['analyte'] = me_df2['Analyte Abbreviation'].str.upper()
df2['concentration'] = me_df2['Final Result'].fillna(0)
df2['sampling_location'] = me_df2['Installation Name']
df2['DL'] = me_df2['Limit of Detection']
df2['sampling_date'] = pd.to_datetime(me_df2['Sample Date'])
df2['sample_id'] = me_df2['Laboratory Sample ID']
df2['units'] = me_df2['Final Units']
df2['state'] = me_df2['State']
df2['analytical_methods'] = me_df2['Analysis Method']
df2['data_source'] = 'DoD'
df2['source_type'] = 'drinking water'

In [13]:
df2['is_detected'] = df2['concentration'] != 0

In [14]:
me_df3 = pd.read_excel('Export_NCTAMSLANT DET CUTLER.xlsx')

In [15]:
me_df3

,Component ID,Component,State,Installation Name,Installation Type,Lab Report Id,Laboratory Sample ID,Sample Date,Analysis Method,CAS Number,Analyte Abbreviation,Final Result,Limit of Detection,Final Units,Final Qualification,Treatment System,Pre Or Post Treatment
0,1700,Navy,Maine,NCTAMSLANT DET CUTLER,Active,21-1312,F3754-FS,10/4/2021,537.0,13252-13-6,HFPO-DA,NaN,1.270,ng/L,U,No,NaN
1,1700,Navy,Maine,NCTAMSLANT DET CUTLER,Active,21-1312,F3754-FS,10/4/2021,537.0,1763-23-1,PFOS,36.1,1.270,ng/L,NaN,No,NaN
2,1700,Navy,Maine,NCTAMSLANT DET CUTLER,Active,21-1312,F3754-FS,10/4/2021,537.0,2058-94-8,PFUnA,NaN,1.270,ng/L,U,No,NaN
3,1700,Navy,Maine,NCTAMSLANT DET CUTLER,Active,21-1312,F3754-FS,10/4/2021,537.0,2355-31-9,NMeFOSAA,NaN,1.270,ng/L,U,No,NaN
4,1700,Navy,Maine,NCTAMSLANT DET CUTLER,Active,21-1312,F3754-FS,10/4/2021,537.0,2991-50-6,NEtFOSAA,NaN,1.520,ng/L,U,No,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7987,1700,Navy,Maine,NCTAMSLANT DET CUTLER,Active,23-0357,D3739-FS,3/21/2023,537.1,376-06-7,PFTeDA,NaN,1.200,ng/L,UJ,Yes,pre-treatment
7988,1700,Navy,Maine,NCTAMSLANT DET CUTLER,Active,23-0357,D3739-FS,3/21/2023,537.1,72629-94-8,PFTrDA,NaN,1.200,ng/L,UJ,Yes,pre-treatment
7989,1700,Navy,Maine,NCTAMSLANT DET CUTLER,Active,23-0357,D3739-FS,3/21/2023,537.1,756426-58-1,9Cl-PF3ONS,NaN,1.200,ng/L,U,Yes,pre-treatment
7990,1700,Navy,Maine,NCTAMSLANT DET CUTLER,Active,23-0357,D3739-FS,3/21/2023,537.1,763051-92-9,11Cl-PF3OUdS,NaN,1.200,ng/L,U,Yes,pre-treatment
7991,1700,Navy,Maine,NCTAMSLANT DET CUTLER,Active,23-0357,D3739-FS,3/21/2023,537.1,919005-14-4,ADONA,NaN,0.962,ng/L,UJ,Yes,pre-treatment

In [16]:
df3 = pd.DataFrame({col: pd.Series(dtype=dt) for col, dt in columns.items()})
df3['analyte'] = me_df3['Analyte Abbreviation'].str.upper()
df3['concentration'] = me_df3['Final Result'].fillna(0)
df3['sampling_location'] = me_df3['Installation Name']
df3['DL'] = me_df3['Limit of Detection']
df3['sampling_date'] = pd.to_datetime(me_df3['Sample Date'])
df3['sample_id'] = me_df3['Laboratory Sample ID']
df3['units'] = me_df3['Final Units']
df3['state'] = me_df3['State']
df3['analytical_methods'] = me_df3['Analysis Method']
df3['data_source'] = 'DoD'
df3['source_type'] = 'drinking water'

In [17]:
df3['is_detected'] = df3['concentration'] != 0

In [18]:
me_df4 = pd.read_csv('tabula-PFASallResults.csv')
me_df4

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Sum of the six,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,NaN,NaN,NaN,NaN,Maine‐,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2820,NaN,NaN
1,NaN,NaN,NaN,NaN,regulated PFAS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PERFLUOROOCTANE,NaN,NaN
2,NaN,NaN,NaN,Collection,analytes (2802‐,2801,2802,2803,2804,2805,2806,2807,2808,2809,2819,SULFONIC ACID,2824,2828
3,PWSID,System Name,Facility,Date,2807),(PFBS),(PFHPA),(PFHXS),(PFNA),(PFOS),(PFOA),(PFDA),(PFDOA),(PFHXA),(PFBA),6:2 FTS,(PFPEA),(PFPES)
4,ME0092649,39 LIMERICK ROAD LLC,TREAT PT 1,8/1/2023,14.2,ND,2.12,ND,ND,5.04,7.05,ND,ND,8.45,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
742,ME0091670,YARMOUTH WATER DISTRICT,TREAT PT 4,7/26/2022,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,NaN,NaN,NaN,NaN
743,ME0020883,YORK COUNTY SHELTERS,WELL HD 1,4/29/2022,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND
744,ME0091680,YORK WATER DISTRICT,TREAT PT 1,8/10/2022,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,NaN,NaN,NaN,NaN
745,ME0092619,YOULAND CONVENIENCE LLC,TREAT PT 1,1/18/2024,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,NaN,NaN,NaN,NaN
746,ME0092619,YOULAND CONVENIENCE LLC,WELL HD 1,3/29/2023,274,2.28,89,6.36,10.2,33.1,135,ND,ND,40.8,NaN,NaN,NaN,NaN

In [19]:
me_df4 = me_df4.drop([0, 1, 2])

In [20]:
me_df4.columns = list(me_df4.iloc[0])

In [23]:
me_df4 = me_df4.rename(columns={'2807)': 'PFHPA+PFHXS+PFNA+PFOS+PFOA+PFDA'})

In [25]:
me_df4 = me_df4.drop([3])

In [26]:
me_df4

,PWSID,System Name,Facility,Date,PFHPA+PFHXS+PFNA+PFOS+PFOA+PFDA,(PFBS),(PFHPA),(PFHXS),(PFNA),(PFOS),(PFOA),(PFDA),(PFDOA),(PFHXA),(PFBA),6:2 FTS,(PFPEA),(PFPES)
4,ME0092649,39 LIMERICK ROAD LLC,TREAT PT 1,8/1/2023,14.2,ND,2.12,ND,ND,5.04,7.05,ND,ND,8.45,NaN,NaN,NaN,NaN
5,ME0092373,A PLACE FOR ALL SEASONS,TREAT PT 1,11/15/2023,2.51,ND,ND,ND,ND,2.51,ND,ND,ND,ND,NaN,NaN,NaN,NaN
6,ME0094712,ACAP CHILD & FAMILY CENTER,TREAT PT 1,5/31/2022,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND
7,ME0000002,ACTON ELEMENTARY SCHOOL,WELL HD 2,6/13/2022,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,NaN,NaN,NaN,NaN
8,ME0090010,ADDISON POINT WATER DISTRICT,TREAT PT 1,2/27/2024,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
742,ME0091670,YARMOUTH WATER DISTRICT,TREAT PT 4,7/26/2022,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,NaN,NaN,NaN,NaN
743,ME0020883,YORK COUNTY SHELTERS,WELL HD 1,4/29/2022,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND
744,ME0091680,YORK WATER DISTRICT,TREAT PT 1,8/10/2022,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,NaN,NaN,NaN,NaN
745,ME0092619,YOULAND CONVENIENCE LLC,TREAT PT 1,1/18/2024,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,NaN,NaN,NaN,NaN
746,ME0092619,YOULAND CONVENIENCE LLC,WELL HD 1,3/29/2023,274,2.28,89,6.36,10.2,33.1,135,ND,ND,40.8,NaN,NaN,NaN,NaN

In [30]:
me_df4 = me_df4[me_df4['PWSID'] != 'PWSID']

In [33]:
me_df4 = me_df4.replace('ND', 0)

/var/folders/m8/kh2nk5652k94h_n7lqjvr8n00000gn/T/ipykernel_3809/791087114.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  me_df4 = me_df4.replace('ND', 0)

In [35]:
me_df4.columns = me_df4.columns.str.replace(r'\(|\)', '', regex=True)

In [36]:
me_df4.index = range(0, len(me_df4))

In [37]:
me_df4

,PWSID,System Name,Facility,Date,PFHPA+PFHXS+PFNA+PFOS+PFOA+PFDA,PFBS,PFHPA,PFHXS,PFNA,PFOS,PFOA,PFDA,PFDOA,PFHXA,PFBA,6:2 FTS,PFPEA,PFPES
0,ME0092649,39 LIMERICK ROAD LLC,TREAT PT 1,8/1/2023,14.2,0,2.12,0,0,5.04,7.05,0,0.0,8.45,NaN,NaN,NaN,NaN
1,ME0092373,A PLACE FOR ALL SEASONS,TREAT PT 1,11/15/2023,2.51,0,0,0,0,2.51,0,0,0.0,0,NaN,NaN,NaN,NaN
2,ME0094712,ACAP CHILD & FAMILY CENTER,TREAT PT 1,5/31/2022,0,0,0,0,0,0,0,0,0.0,0,0,0,0,0
3,ME0000002,ACTON ELEMENTARY SCHOOL,WELL HD 2,6/13/2022,0,0,0,0,0,0,0,0,0.0,0,NaN,NaN,NaN,NaN
4,ME0090010,ADDISON POINT WATER DISTRICT,TREAT PT 1,2/27/2024,0,0,0,0,0,0,0,0,0.0,0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
725,ME0091670,YARMOUTH WATER DISTRICT,TREAT PT 4,7/26/2022,0,0,0,0,0,0,0,0,0.0,0,NaN,NaN,NaN,NaN
726,ME0020883,YORK COUNTY SHELTERS,WELL HD 1,4/29/2022,0,0,0,0,0,0,0,0,0.0,0,0,0,0,0
727,ME0091680,YORK WATER DISTRICT,TREAT PT 1,8/10/2022,0,0,0,0,0,0,0,0,0.0,0,NaN,NaN,NaN,NaN
728,ME0092619,YOULAND CONVENIENCE LLC,TREAT PT 1,1/18/2024,0,0,0,0,0,0,0,0,0.0,0,NaN,NaN,NaN,NaN
729,ME0092619,YOULAND CONVENIENCE LLC,WELL HD 1,3/29/2023,274,2.28,89,6.36,10.2,33.1,135,0,0.0,40.8,NaN,NaN,NaN,NaN

In [43]:
len(list(me_df4.columns)[4:18])

14

In [44]:
list(me_df4.columns)[4:18]

['PFHPA+PFHXS+PFNA+PFOS+PFOA+PFDA',
 'PFBS',
 'PFHPA',
 'PFHXS',
 'PFNA',
 'PFOS',
 'PFOA',
 'PFDA',
 'PFDOA',
 'PFHXA',
 'PFBA',
 '6:2 FTS',
 'PFPEA',
 'PFPES']

In [45]:
columns_to_repeat = ['PWSID', 'System Name', 'Facility', 'Date']
df_repeated = pd.DataFrame(columns=columns_to_repeat)

for i in range(len(me_df4)):
    row_repeated = pd.concat([me_df4.iloc[[i]][columns_to_repeat]] * 14, ignore_index=True)
    df_repeated = pd.concat([df_repeated, row_repeated], ignore_index=True)

df_repeated

           PWSID              System Name    Facility       Date
0      ME0092649     39 LIMERICK ROAD LLC  TREAT PT 1   8/1/2023
1      ME0092649     39 LIMERICK ROAD LLC  TREAT PT 1   8/1/2023
2      ME0092649     39 LIMERICK ROAD LLC  TREAT PT 1   8/1/2023
3      ME0092649     39 LIMERICK ROAD LLC  TREAT PT 1   8/1/2023
4      ME0092649     39 LIMERICK ROAD LLC  TREAT PT 1   8/1/2023
...          ...                      ...         ...        ...
10215  ME0092619  YOULAND CONVENIENCE LLC   WELL HD 1  3/29/2023
10216  ME0092619  YOULAND CONVENIENCE LLC   WELL HD 1  3/29/2023
10217  ME0092619  YOULAND CONVENIENCE LLC   WELL HD 1  3/29/2023
10218  ME0092619  YOULAND CONVENIENCE LLC   WELL HD 1  3/29/2023
10219  ME0092619  YOULAND CONVENIENCE LLC   WELL HD 1  3/29/2023

[10220 rows x 4 columns]

In [46]:
df_repeated['analyte'] = list(me_df4.columns)[4:18] * len(me_df4)

In [47]:
df_repeated

,PWSID,System Name,Facility,Date,analyte
0,ME0092649,39 LIMERICK ROAD LLC,TREAT PT 1,8/1/2023,PFHPA+PFHXS+PFNA+PFOS+PFOA+PFDA
1,ME0092649,39 LIMERICK ROAD LLC,TREAT PT 1,8/1/2023,PFBS
2,ME0092649,39 LIMERICK ROAD LLC,TREAT PT 1,8/1/2023,PFHPA
3,ME0092649,39 LIMERICK ROAD LLC,TREAT PT 1,8/1/2023,PFHXS
4,ME0092649,39 LIMERICK ROAD LLC,TREAT PT 1,8/1/2023,PFNA
...,...,...,...,...,...
10215,ME0092619,YOULAND CONVENIENCE LLC,WELL HD 1,3/29/2023,PFHXA
10216,ME0092619,YOULAND CONVENIENCE LLC,WELL HD 1,3/29/2023,PFBA
10217,ME0092619,YOULAND CONVENIENCE LLC,WELL HD 1,3/29/2023,6:2 FTS
10218,ME0092619,YOULAND CONVENIENCE LLC,WELL HD 1,3/29/2023,PFPEA
10219,ME0092619,YOULAND CONVENIENCE LLC,WELL HD 1,3/29/2023,PFPES

In [48]:
analyte_list = list(me_df4.columns)[4:18]

In [49]:
me_df4[analyte_list]

,PFHPA+PFHXS+PFNA+PFOS+PFOA+PFDA,PFBS,PFHPA,PFHXS,PFNA,PFOS,PFOA,PFDA,PFDOA,PFHXA,PFBA,6:2 FTS,PFPEA,PFPES
0,14.2,0,2.12,0,0,5.04,7.05,0,0.0,8.45,NaN,NaN,NaN,NaN
1,2.51,0,0,0,0,2.51,0,0,0.0,0,NaN,NaN,NaN,NaN
2,0,0,0,0,0,0,0,0,0.0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0.0,0,NaN,NaN,NaN,NaN
4,0,0,0,0,0,0,0,0,0.0,0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
725,0,0,0,0,0,0,0,0,0.0,0,NaN,NaN,NaN,NaN
726,0,0,0,0,0,0,0,0,0.0,0,0,0,0,0
727,0,0,0,0,0,0,0,0,0.0,0,NaN,NaN,NaN,NaN
728,0,0,0,0,0,0,0,0,0.0,0,NaN,NaN,NaN,NaN
729,274,2.28,89,6.36,10.2,33.1,135,0,0.0,40.8,NaN,NaN,NaN,NaN

In [52]:
me_df4[analyte_list] = me_df4[analyte_list].astype(float)

In [53]:
me_df4[analyte_list].values.flatten().tolist()

[14.2,
 0.0,
 2.12,
 0.0,
 0.0,
 5.04,
 7.05,
 0.0,
 0.0,
 8.45,
 nan,
 nan,
 nan,
 nan,
 2.51,
 0.0,
 0.0,
 0.0,
 0.0,
 2.51,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 16.6,
 0.0,
 3.12,
 0.0,
 3.49,
 0.0,
 9.96,
 0.0,
 0.0,
 12.7,
 nan,
 nan,
 nan,
 nan,
 12.8,
 4.24,
 0.0,
 8.05,
 0.0,
 0.0,
 4.74,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 11.8,
 0.0,
 30.6,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 20.8,
 2.9,
 3.84,
 0.0,
 2.82,
 4.55,
 9.54,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 3.31,
 0.0,
 0.0,
 0.0,
 3.31,
 0.0,
 0.0,
 0.0,
 0.0,
 2.26,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 3.64,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 22.15,
 2.42,
 6.44,
 0.0,
 0.0,
 3.71,
 12.0,
 0.0,
 0.0,
 8.23,
 5.52,
 0.0,
 11.1,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 9.27,
 0.0,
 0.0,
 7.1,
 0.0,
 2.17,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 13.9,
 2.76,
 0.0,
 0.0,
 0.0,
 4.24,
 9.61,
 0.0,
 0.0,
 2.94,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 5.16,
 9.5,
 0.0,
 0.0,
 0.0,
 3.14,
 2.02,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 4.82,
 0.0,
 0.0,
 0.0,
 0.0,
 4.82,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 3.95,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 3.95,
 0.0,
 0.0,
 3.34,
 4.49,
 0.0,
 4.38,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 4.64,
 0.0,
 0.0,
 0.0,
 0.0,
 2.57,
 2.07,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 2.36,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 2.36,
 0.0,
 0.0,
 4.32,
 7.36,
 0.0,
 2.87,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 8.29,
 3.23,
 0.0,
 0.0,
 0.0,
 2.95,
 5.34,
 0.0,
 0.0,
 11.4,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 ...]

In [54]:
len(me_df4[analyte_list].values.flatten().tolist())

10220

In [55]:
df_repeated['concentration'] = me_df4[analyte_list].values.flatten().tolist()

In [56]:
def set_is_detected(concentration):
    if pd.isna(concentration):
        return np.nan
    return concentration != 0

In [57]:
df_repeated['is_detected'] = df_repeated['concentration'].apply(set_is_detected)

In [58]:
df_repeated

,PWSID,System Name,Facility,Date,analyte,concentration,is_detected
0,ME0092649,39 LIMERICK ROAD LLC,TREAT PT 1,8/1/2023,PFHPA+PFHXS+PFNA+PFOS+PFOA+PFDA,14.20,True
1,ME0092649,39 LIMERICK ROAD LLC,TREAT PT 1,8/1/2023,PFBS,0.00,False
2,ME0092649,39 LIMERICK ROAD LLC,TREAT PT 1,8/1/2023,PFHPA,2.12,True
3,ME0092649,39 LIMERICK ROAD LLC,TREAT PT 1,8/1/2023,PFHXS,0.00,False
4,ME0092649,39 LIMERICK ROAD LLC,TREAT PT 1,8/1/2023,PFNA,0.00,False
...,...,...,...,...,...,...,...
10215,ME0092619,YOULAND CONVENIENCE LLC,WELL HD 1,3/29/2023,PFHXA,40.80,True
10216,ME0092619,YOULAND CONVENIENCE LLC,WELL HD 1,3/29/2023,PFBA,NaN,NaN
10217,ME0092619,YOULAND CONVENIENCE LLC,WELL HD 1,3/29/2023,6:2 FTS,NaN,NaN
10218,ME0092619,YOULAND CONVENIENCE LLC,WELL HD 1,3/29/2023,PFPEA,NaN,NaN
10219,ME0092619,YOULAND CONVENIENCE LLC,WELL HD 1,3/29/2023,PFPES,NaN,NaN

In [59]:
df4 = pd.DataFrame({col: pd.Series(dtype=dt) for col, dt in columns.items()})
df4['analyte'] = df_repeated['analyte'].str.upper()
df4['concentration'] = df_repeated['concentration']
df4['sampling_location'] = df_repeated['System Name']
df4['sampling_date'] = pd.to_datetime(df_repeated['Date'])
df4['units'] = 'ng/L'
df4['state'] = 'Maine'
df4['data_source'] = 'Maine DWP'
df4['source_type'] = 'drinking water'
df4['pws_id'] = df_repeated['PWSID']
df4['is_detected'] = df_repeated['is_detected']

In [60]:
df4

,sample_id,sampling_location,data_source,latitude,longitude,sampling_date,pws_id,water_system_name,population,well_type,...,city,county,MRL,DL,analytical_methods,is_detected,analyte,concentration,pfas_total,note
0,NaN,39 LIMERICK ROAD LLC,Maine DWP,NaN,NaN,2023-08-01,ME0092649,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,True,PFHPA+PFHXS+PFNA+PFOS+PFOA+PFDA,14.20,NaN,NaN
1,NaN,39 LIMERICK ROAD LLC,Maine DWP,NaN,NaN,2023-08-01,ME0092649,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,False,PFBS,0.00,NaN,NaN
2,NaN,39 LIMERICK ROAD LLC,Maine DWP,NaN,NaN,2023-08-01,ME0092649,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,True,PFHPA,2.12,NaN,NaN
3,NaN,39 LIMERICK ROAD LLC,Maine DWP,NaN,NaN,2023-08-01,ME0092649,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,False,PFHXS,0.00,NaN,NaN
4,NaN,39 LIMERICK ROAD LLC,Maine DWP,NaN,NaN,2023-08-01,ME0092649,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,False,PFNA,0.00,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10215,NaN,YOULAND CONVENIENCE LLC,Maine DWP,NaN,NaN,2023-03-29,ME0092619,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,True,PFHXA,40.80,NaN,NaN
10216,NaN,YOULAND CONVENIENCE LLC,Maine DWP,NaN,NaN,2023-03-29,ME0092619,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,PFBA,NaN,NaN,NaN
10217,NaN,YOULAND CONVENIENCE LLC,Maine DWP,NaN,NaN,2023-03-29,ME0092619,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,6:2 FTS,NaN,NaN,NaN
10218,NaN,YOULAND CONVENIENCE LLC,Maine DWP,NaN,NaN,2023-03-29,ME0092619,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,PFPEA,NaN,NaN,NaN
10219,NaN,YOULAND CONVENIENCE LLC,Maine DWP,NaN,NaN,2023-03-29,ME0092619,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,PFPES,NaN,NaN,NaN

In [61]:
df = pd.concat([df1, df2, df3, df4])

In [62]:
df.index = range(0, len(df))

In [63]:
df

,sample_id,sampling_location,data_source,latitude,longitude,sampling_date,pws_id,water_system_name,population,well_type,...,city,county,MRL,DL,analytical_methods,is_detected,analyte,concentration,pfas_total,note
0,F4748-FS,Brunswick NAS,DoD,NaN,NaN,2021-10-19,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.32,537.1,False,HFPO-DA,0.00,NaN,NaN
1,F4748-FS,Brunswick NAS,DoD,NaN,NaN,2021-10-19,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.32,537.1,True,PFOS,4.79,NaN,NaN
2,F4748-FS,Brunswick NAS,DoD,NaN,NaN,2021-10-19,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.32,537.1,False,PFUNA,0.00,NaN,NaN
3,F4748-FS,Brunswick NAS,DoD,NaN,NaN,2021-10-19,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.32,537.1,False,NMEFOSAA,0.00,NaN,NaN
4,F4748-FS,Brunswick NAS,DoD,NaN,NaN,2021-10-19,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.59,537.1,False,NETFOSAA,0.00,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20808,NaN,YOULAND CONVENIENCE LLC,Maine DWP,NaN,NaN,2023-03-29,ME0092619,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,True,PFHXA,40.80,NaN,NaN
20809,NaN,YOULAND CONVENIENCE LLC,Maine DWP,NaN,NaN,2023-03-29,ME0092619,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,PFBA,NaN,NaN,NaN
20810,NaN,YOULAND CONVENIENCE LLC,Maine DWP,NaN,NaN,2023-03-29,ME0092619,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,6:2 FTS,NaN,NaN,NaN
20811,NaN,YOULAND CONVENIENCE LLC,Maine DWP,NaN,NaN,2023-03-29,ME0092619,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,PFPEA,NaN,NaN,NaN
20812,NaN,YOULAND CONVENIENCE LLC,Maine DWP,NaN,NaN,2023-03-29,ME0092619,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,PFPES,NaN,NaN,NaN

In [3]:
df = pd.read_csv('maine_dw.csv', index_col=0)

In [4]:
df

,sample_id,sampling_location,data_source,latitude,longitude,sampling_date,pws_id,water_system_name,population,well_type,...,city,county,MRL,DL,analytical_methods,is_detected,analyte,concentration,pfas_total,note
0,F4748-FS,Brunswick NAS,DoD,NaN,NaN,2021-10-19,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.32,537.1,False,HFPO-DA,0.00,NaN,NaN
1,F4748-FS,Brunswick NAS,DoD,NaN,NaN,2021-10-19,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.32,537.1,True,PFOS,4.79,NaN,NaN
2,F4748-FS,Brunswick NAS,DoD,NaN,NaN,2021-10-19,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.32,537.1,False,PFUNA,0.00,NaN,NaN
3,F4748-FS,Brunswick NAS,DoD,NaN,NaN,2021-10-19,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.32,537.1,False,NMEFOSAA,0.00,NaN,NaN
4,F4748-FS,Brunswick NAS,DoD,NaN,NaN,2021-10-19,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.59,537.1,False,NETFOSAA,0.00,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20808,NaN,YOULAND CONVENIENCE LLC,Maine DWP,NaN,NaN,2023-03-29,ME0092619,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,True,PFHXA,40.80,NaN,NaN
20809,NaN,YOULAND CONVENIENCE LLC,Maine DWP,NaN,NaN,2023-03-29,ME0092619,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,PFBA,NaN,NaN,NaN
20810,NaN,YOULAND CONVENIENCE LLC,Maine DWP,NaN,NaN,2023-03-29,ME0092619,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,6:2 FTS,NaN,NaN,NaN
20811,NaN,YOULAND CONVENIENCE LLC,Maine DWP,NaN,NaN,2023-03-29,ME0092619,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,PFPEA,NaN,NaN,NaN
20812,NaN,YOULAND CONVENIENCE LLC,Maine DWP,NaN,NaN,2023-03-29,ME0092619,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,PFPES,NaN,NaN,NaN

In [5]:
from concurrent.futures import ThreadPoolExecutor
import pandas as pd
from geopy.geocoders import OpenCage

geolocator = OpenCage(api_key="c7f16120befe4e3fb85e7a082e620fdb")

def geocode_address(address):
    try:
        location = geolocator.geocode(address)
        if location:
            return (address, location.latitude, location.longitude)
        else:
            return (address, None, None)
    except Exception as e:
        print(f"Error geocoding {address}: {e}")
        return (address, None, None)

addresses_to_query = df.loc[df['latitude'].isna() | df['longitude'].isna(), 'sampling_location'].unique()

with ThreadPoolExecutor(max_workers=10) as executor:
    results = list(executor.map(geocode_address, addresses_to_query))

location_cache = {address: (lat, lon) for address, lat, lon in results}

In [6]:
location_cache

{'Brunswick NAS': (25.05823, -77.34306),
 'Loring AFB': (46.9496653, -67.8927389),
 'NCTAMSLANT DET CUTLER': (44.6601326, -67.2922067),
 '39 LIMERICK ROAD LLC': (40.2034318, -75.5392418),
 'A PLACE FOR ALL SEASONS': (None, None),
 'ACAP CHILD & FAMILY CENTER': (7.25, 2.16667),
 'ACTON ELEMENTARY SCHOOL': (43.5073553, -70.898009),
 'ADDISON POINT WATER DISTRICT': (None, None),
 'ALFRED WATER DISTRICT': (43.4793472, -70.7174894),
 'ALLEN WATER COMPANY': (None, None),
 'ANDOVER WATER DISTRICT': (44.6366102, -70.7472415),
 'ANSON AND MADISON WATER DISTRICT': (None, None),
 'AOS 77 ALEXANDER ELEMENTARY SCHOOL': (45.14914, 11.82057),
 'AOS 77 CHARLOTTE ELEMENTARY SCHOOL': (45.14914, 11.82057),
 'AOS 77 PEMBROKE ELEMENTARY SCHOOL': (45.14914, 11.82057),
 'AOS 77 PERRY ELEMENTARY SCHOOL': (45.14914, 11.82057),
 'AOS 90 EAST RANGE II CSD SCHOOL': (45.14914, 11.82057),
 'AOS 90 PRINCETON ELEMENTARY SCHOOL': (45.14914, 11.82057),
 'AOS 91 MT DESERT ISLAND HIGH SCHOOL': (37.78639, -122.28639),
 'AOS 91 TREMONT CONSOLIDATED SCHOOL': (45.14914, 11.82057),
 'AOS 92 VASSALBORO COMMUNITY SCHOOL': (45.14914, 11.82057),
 'AOS 93 BRISTOL CONSOLIDATED SCHOOL': (45.14914, 11.82057),
 'AOS 93 JEFFERSON VILLAGE SCHOOL': (45.14914, 11.82057),
 'AOS 93 NOBLEBORO CENTRAL SCHOOL': (45.14914, 11.82057),
 'AOS 93 SOUTH  BRISTOL ELEMENTARY SCHOOL': (45.14914, 11.82057),
 'AOS 96  BAY RIDGE ELEMENTARY': (None, None),
 'AOS 96 ELM STREET SCHOOL': (45.14914, 11.82057),
 'AOS 96 FORT OBRIEN SCHOOL': (45.14914, 11.82057),
 'AOS 96 JONESBORO ELEMENTARY SCHOOL': (45.14914, 11.82057),
 'AOS 96 WHITING VILLAGE SCHOOL': (45.14914, 11.82057),
 'AOS 98 EDGECOMB EDDY ELEMENTARY II': (65.31735, 25.3731),
 'AOS 98 GEORGETOWN CENTRAL SCHOOL': (45.14914, 11.82057),
 'APPLEWOOD': (35.0232314, -82.1159594),
 'AROOSTOOK RENTAL HOUSING LLC': (None, None),
 'ASHLAND WATER & SEWER DISTRICT': (None, None),
 'ASHWOOD WALDORF SCHOOL': (45.14914, 11.82057),
 'AUBURN WATER DISTRICT': (44.0976565, -70.2325788),
 'AUTUMN COURT LLC': (39.1469703, -76.8088183),
 'AVERILLS MOBILE HOME PARK': (29.69225, -91.17896),
 'BAILEYVILLE UTILITIES DISTRICT': (None, None),
 'BANGOR WATER DISTRICT': (44.812088, -68.7437984),
 'BATH WATER DISTRICT': (54.9433786, 20.1544755),
 'BAY BRIDGE ESTATES LLC': (None, None),
 'BAY SCHOOL': (30.3669074, -86.1188395),
 'BECKET ACADEMY CENTRAL ME LEARNING CTR': (None, None),
 'BEGIN TRAILER PARK': (25.95904, -109.05496),
 'BELFAST AREA CHILDRENS CENTER': (7.25, 2.16667),
 'BELFAST COHOUSING & ECOVILLAGE CONDOS': (None, None),
 'BELFAST UNITED METHODIST CHURCH': (42.3438889, -78.1105556),
 'BELFAST WATER DISTRICT': (None, None),
 'BENJAMIN RIVER APTS': (None, None),
 'BERWICK EARLY LEARNING CENTER': (43.289229, -70.7881859),
 'BERWICK WATER DEPARTMENT': (None, None),
 'BETHEL WATER DISTRICT': (None, None),
 'BIG CATS CATERING‐TINY TYKES DAYCARE': (None, None),
 'BINGHAM WATER DISTRICT': (None, None),
 'BIRCH HAVEN TRAILER PARK': (25.95904, -109.05496),
 'BIRCH TREE MEADOWS MHP': (None, None),
 'BIRCHWOOD TRAILER PARK': (46.2963556, -93.8269962),
 'BLACK HORSE INN': (53.0193744, -1.6128157),
 'BLUE HILL TERRACE': (41.012438, -74.19269),
 'BLUEBERRY RIDGE MOBILE VILLAGE': (None, None),
 'BOOTHBAY REGION WATER DISTRICT': (43.8890753, -69.6342879),
 'BOUDREAU TRAILER PARK': (25.95904, -109.05496),
 'BOULIER PLACE APTS': (None, None),
 'BOWDOINHAM WATER DISTRICT': (44.0167256, -69.9372665),
 'BREWER WATER DEPARTMENT': (44.7979668, -68.5942878),
 'BRIARWOOD CHILDRENS HOUSE': (34.64673, -103.90441),
 'BRIDGTON WATER DISTRICT': (44.0681357, -70.7177556),
 'BRIGHT IDEAS CHILD CARE CENTER': (41.5343, -71.2936),
 'BROCKS MOBILE HOME PARK': (29.69225, -91.17896),
 'BROOK HOLLOW': (36.0772317, -79.2802654),
 'BROOKSIDE MHP': (38.662101, -121.333575),
 'BROOKSIDE MOBILE HOME COURT': (47.23956, 7.33655),
 'BROWNFIELD‐DENMARK ELEMENTARY SCHOOL': (43.964895, -70.8619554),
 'BROWNVILLE JCT WATER DEPT': (None, None),
 'BROWNVILLE WATER DEPARTMENT': (None, None),
 'BRUNSWICK/TOPSHAM WATER DISTRICT': (43.9220834, -69.9761943),
 'BUCKFIELD VILLAGE CORPORATION': (None, None),
 'BURNT MILL SETTLEMENT': (None, None),
 'CALAIS HIGH SCHOOL': (45.1631098, -67.2442795),
 'CALAIS WATER DEPT': (None, None),
 'CALVARY BAPTIST CHURCH/ACADEMY': (39.14363, -76.60006),
 'CANTON POINT PARK': (22.3075878, 114.1684457),
 'CANTON WATER DISTRICT': (22.2475886, 114.1761994),
 'CARIBOU STREAM MOBILE HOME PK': (30.0, 70.0),
 'CARIBOU UTILITIES DISTRICT': (None, None),
 'CARRABASSETT VALLEY ACADEMY': (45.0760115, -70.3151397),
 'CARRABASSETT VALLEY ACADEMY DORM': (None, None),
 'CASCO INN RESIDENTIAL CARE': (None, None),
 'CASTINE WATER DEPARTMENT': (None, None),
 'CASWELL ELEM/AKA DAWN BARNES': (39.71195, -96.87447),
 'CEDAR HAVEN MHC': (None, None),
 'CENTER DRIVE SCHOOL': (44.7270777, -68.8152511),
 'CENTER FOR TEACHING/LEARNING': (43.9794754, -69.649223),
 'CHARTER OAKS VILLAGE COOPERATIVE': (None, None),
 'CHEBEAGUE ISLAND SCHOOL': (43.7290971, -70.1272737),
 'CHERRYFIELD SCHOOL DEPARTMENT': (None, None),
 'CHEWONKI FOUNDATION #1': (47.27541, 8.4897),
 'CHEWONKI FOUNDATION #2': (47.28167, 8.45023),
 'CHILDRENS VILLAGE CHILD CARE CENTER': (7.25, 2.16667),
 'CLARKS MILLS APARTMENTS': (43.5846109, -70.6008806),
 'CLC YMCA CHILD CARE': (None, None),
 'CLIFFORD ARTS & STUDENT CENTER': (7.25, 2.16667),
 'CLINTON WATER DISTRICT': (32.4131921, -87.0199897),
 'COASTAL CHRISTIAN SCHOOL': (44.1299797, -69.4301498),
 'COASTAL WASHINGTON CIT': (None, None),
 'COCOONS DAY SCHOOL': (45.14914, 11.82057),
 'COLD SPRING WATER COMPANY': (None, None),
 'COLONIAL MOBILE HOME PARK': (43.4681026, -70.7268503),
 'CONNOR CONSOLIDATED SCHOOL': (45.14914, 11.82057),
 'CORINNA WATER DISTRICT': (None, None),
 'CORINTHIAN MANOR': (30.34076, -97.55695),
 'CORNISH WATER DISTRICT': (43.8010249, -70.8267066),
 'CORNVILLE REGIONAL CHARTER SCHOOL': (45.14914, 11.82057),
 'COUNTRY ACRES TRAILER PARK': (43.04806, -73.87222),
 'COUNTRY KIDS': (43.9015994, -79.6540017),
 'COUNTRY MOBILE HOME PARK': (33.3781526, -112.5610644),
 'COUNTRY VIEW APARTMENTS': (39.4061651, -86.4200153),
 'COUNTRYSIDE APARTMENTS': (43.1349554, -75.4111685),
 'COVERED BRIDGE APARTMENTS': (36.7651505, -76.6014758),
 'CRANTON‐THOMES DAY SCHOOL': (45.14914, 11.82057),
 'CRAWFORD COMMONS': (36.8362346, -76.2979611),
 'CRESCENT MOBILE HOME PARK LLC': (None, None),
 'CREST VIEW MANOR': (42.8423163, -103.0036227),
 'CROSSROADS COMMUNITY MHP': (None, None),
 'CRYSTAL SPRING ESTATES': (47.2346301, -122.5478829),
 'CSD 8 AIRLINE COMMUNITY SCHOOL': (45.14914, 11.82057),
 'DAMARISCOTTA MONTESSORI SCHOOL': (45.14914, 11.82057),
 'DANFORTH WATER DISTRICT': (None, None),
 'DAYTON SCHOOL DEPARTMENT': (None, None),
 'DEDHAM ELEMENTARY SCHOOL': (45.14914, 11.82057),
 'DEER RIDGE MOBILE HOME PARK': (41.06194, -83.62694),
 'DEER RUN APTS': (44.2279061, -68.6756032),
 'DEL‐WOOD TRAILER PARK': (25.95904, -109.05496),
 'DENNYSVILLE HOUSING': (None, None),
 'DEXTER UTILITY  DISTRICT': (None, None),
 'DINGLEY SPRING ESTATES': (None, None),
 'DIPPER COVE ASSOCIATION': (None, None),
 'DIRIGO MOBILE HOME PARK': (29.69225, -91.17896),
 'DIXFIELD WATER & SEWER DEPT': (None, None),
 'DOVER REALTY VENTURES MHP LLC': (None, None),
 'DOVER‐FOXCROFT WATER DISTRICT': (45.176076, -69.2334757),
 'DOWNEAST CORRECTIONAL FACILITY': (44.6283289, -67.397016),
 'DRESDEN ELEM SCHOOL': (45.14914, 11.82057),
 'DRESDEN WATER DEPARTMENT': (None, None),
 'DUCK‐A‐WAY ON CASCO BAY': (43.63342, -70.04949),
 'DUCKTRAP HARBOR CONDOMINIUMS': (None, None),
 'EAGLE LAKE WATER & SEWER DISTRICT': (None, None),
 'EAST MILLINOCKET WATER WORKS': (18.24834, -78.05343),
 'EAST PITTSTON WATER DISTRICT': (None, None),
 'EAST RIDGE MOBILE HOME PARK': (44.1122842, -69.3452139),
 'EAST VASSALBORO WATER COMPANY LLC': (None, None),
 'EASTON ELEMENTARY SCHOOL': (46.6409885, -67.9011138),
 'EASTON HIGH SCHOOL': (38.7551404, -76.0653199),
 'EDMUNDS CONSOLIDATED SCHOOL': (44.8972999, -67.2233205),
 'ELLIOTT APARTMENTS': (41.5858902, -93.6215949),
 'ELLSWORTH WATER DEPARTMENT': (None, None),
 'ELWELL FARMS': (43.6680416, -70.5805858),
 'ERSKINE ACADEMY': (44.3735853, -69.5765177),
 'ESTES LAKE MOBILE HOME PARK': (29.69225, -91.17896),
 'EUSTIS WATER DEPARTMENT': (None, None),
 'EVERGREEN COMMUNITY MH PARK': (39.11251, -100.35875),
 'EVERGREEN ESTATES OF LEBANON LLC': (None, None),
 'EVERGREEN MOBILE HOME PARK': (45.0944444, -94.5111111),
 'EXETER WATER DEPARTMENT': (None, None),
 'FAIRGROUND APARTMENTS': (41.016349, -80.7487474),
 'FAITH BIBLE COLLEGE INTERNATIONAL': (45.0832691, -69.0408368),
 'FARMINGTON FALLS STD WATER DIST': (None, None),
 'FARMINGTON VILLAGE CORP WATER DEPT': (None, None),
 'FAYETTE CENTRAL SCHOOL': (44.4073412, -70.039145),
 'FHC INC': (44.0334837, -69.9604912),
 'FIRST UNITED PENTECOSTAL CHURCH‐AUGUSTA': (None, None),
 'FORT FAIRFIELD UTILITIES DISTRICT': (None, None),
 'FORT KENT W & W DEPARTMENT': (None, None),
 'FOUR WINDS HOMEOWNERS ASSN': (None, None),
 'FRANKLIN WATER DEPARTMENT': (None, None),
 'FRIENDLY VILLAGE OF GORHAM MHP': (None, None),
 'FRIENDSHIP WATER DEPARTMENT': (None, None),
 'FRYEBURG WATER COMPANY': (None, None),
 'GAELIC SQUARE HOUSING': (None, None),
 'GARDINER WATER DISTRICT': (None, None),
 'GEORGE POND ESTATES LLC': (None, None),
 'GEORGE STEVENS ACADEMY': (44.4136271, -68.5898724),
 'GLENBURN ELEM SCHOOL': (45.14914, 11.82057),
 'GOLDEN SUN CHILD CARE': (None, None),
 'GOOD WILL HOME ASSOCIATION': (None, None),
 'GRAND ISLE WATER SYSTEM': (None, None),
 'GRANDEUR MOBILE HOME ESTATES': (35.92293, -77.58219),
 'GRAY WATER DISTRICT': (None, None),
 'GREAT SALT BAY SANITARY DISTRICT': (None, None),
 'GREATER AUGUSTA UTILITY DISTRICT': (44.3359501, -69.8046875),
 'GREENLEDGE PARK LLC': (None, None),
 'GREENWOOD GARDEN APARTMENTS': (None, None),
 'GUILFORD‐SANGERVILLE WATER DISTRICT': (None, None),
 'HADLEYS LAKE APARTMENTS': (None, None),
 'HALLOWELL ROAD MOBILE HOME PARK': (29.69225, -91.17896),
 'HALLOWELL WATER DISTRICT': (44.2903542, -69.797008),
 'HAMPDEN WATER DISTRICT': (51.8107154, -1.2766249),
 'HANCOCK GRAMMAR SCHOOL': (44.5305046, -68.2514818),
 'HANCOCK VILLAGE MHP': (41.150323, -83.423598),
 'HAPPY TRAILS MHP': (27.960419, -82.743294),
 'HARBORVIEW I & II': (48.2849839, -122.6671396),
 'HARMON PINES DEVELOPMENT': (None, None),
 'HARMONY ELEMENTARY SCHOOL': (45.6367551, -122.4935015),
 'HARRIMAN COVE PARK LLC': (None, None),
 'HARRISON WATER DISTRICT': (44.1180823, -70.6844281),
 'HAVASU PINES MHP': (None, None),
 'HAVASU PINES MHP #1': (47.27541, 8.4897),
 'HEBRON WATER COMPANY': (None, None),
 'HELEN S DUNN SCHOOL': (45.1203253, -68.6081164),
 'HERITAGE VIEW APTS': (None, None),
 'HERMON HIGH SCHOOL': (44.809796, -68.8990849),
 'HERMON MHP LLC': (None, None),
 'HERMON MIDDLE SCHOOL #2': (47.28167, 8.45023),
 'HIDDEN LAKE VILLAGE LLC': (None, None),
 'HIGHPINE MOBILE HOME COURT': (47.23956, 7.33655),
 'HIGHPINE VILLAGE': (None, None),
 'HIGHVIEW CHRISTIAN ACADEMY': (33.506907, -82.1457429),
 'HILLHOUSE INC': (38.46806, 106.27306),
 'HILLVIEW ESTATES': (39.6826112, -75.9274431),
 'HINGHAM HEIGHTS': (38.670547, -77.286259),
 'HODGDON HOMESTEAD': (37.5392237, -119.6559941),
 'HOLDEN SQUARE APARTMENTS': (None, None),
 'HOME INC & LEARNING CENTER': (25.507589, -80.3975243),
 'HOMESTEAD ESTATES LLC': (None, None),
 'HOPE ELEMENTARY SCHOOL': (41.7359334, -71.5625625),
 'HOULTON MOBILE HOME PARK': (45.066755, -92.7895623),
 'HOULTON WATER COMPANY': (None, None),
 'HOWARDS TRAILER PARK': (25.95904, -109.05496),
 'INDIAN RUN ESTATES LLC': (None, None),
 'INDIAN TOWNSHIP TRIBAL WATER SYSTEM': (None, None),
 'ISLAND FALLS WATER DEPT': (None, None),
 'JACKMAN UTILITY DISTRICT': (None, None),
 'JAY VILLAGE WATER DISTRICT': (None, None),
 'JORDAN‐SMALL MIDDLE SCHOOL': (43.9370883, -70.4444668),
 'KELLYS PLACE LEARNING CENTER LLC': (None, None),
 'KENNEBEC MOBILE HOME PARK': (44.3102197, -69.801877),
 'KENNEBEC WATER DISTRICT': (44.455063, -69.6114723),
 'KENNEBUNK, KENNEBUNKPORT & WELLS WD': (None, None),
 'KENTS HILL SCHOOL': (52.0255261, -0.6972361),
 'KEREBEAR CHILD CARE': (None, None),
 'KEYWOOD MANOR MOBILE HOME PARK LP': (None, None),
 'KIDQUARTERS CHILD CARE CENTER': (7.25, 2.16667),
 'KIDS & CO CHILDCARE CENTER': (7.25, 2.16667),
 'KIDS COUNT LEARNING CENTER': (7.25, 2.16667),
 'KIDSPEACE‐NEW ENGLAND‐CAFETERIA': (None, None),
 'KINGFIELD WATER DISTRICT': (None, None),
 'KITTERY WATER DISTRICT': (43.1625049, -70.6928417),
 'KNIGHTS HILL ASSOCIATION': (None, None),
 'LAKE ARROWHEAD COMMUNITY INC': (38.46806, 106.27306),
 'LAKE ST GEORGE APARTMENTS': (None, None),
 'LAKES REGION APARTMENTS': (None, None),
 'LEE ACADEMY #1': (31.729425, -84.166296),
 'LEE ACADEMY #3': (31.729425, -84.166296),
 'LEE ACADEMY‐COBB CENTER': (7.25, 2.16667),
 'LEIGHTONS LITTLE BEAR DEN': (47.75141, -103.00463),
 'LEWISTON WATER & SEWER DIVISION': (None, None),
 'LIFE CHURCH‐SUNNY DAYS CHILDCARE': (None, None),
 'LIMERICK MOBILE HOME PARK LLC': (None, None),
 'LIMERICK WATER DISTRICT': (None, None),
 'LIMESTONE WATER & SEWER DISTRICT': (46.9191742, -67.8285171),
 'LINCOLN WATER DISTRICT': (None, None),
 'LISBON WATER DEPARTMENT': (None, None),
 'LITTLE BUDDIES CHILDCARE LLC': (None, None),
 'LITTLE FARM SCHOOL': (40.29455, -75.17267),
 'LITTLE LEARNERS CHILD CARE CENTER': (7.25, 2.16667),
 'LITTLE LEARNERS CHILDCARE': (55.0236292, -1.479405),
 'LITTLE TYKES II CHILD CARE': (None, None),
 'LIVERMORE FALLS WATER DISTRICT': (None, None),
 'LIVING WATERS CHRISTIAN SCHOOL': (45.14914, 11.82057),
 'LONG POND WATER DISTRICT': (None, None),
 'LORING DEVELOPMENT AUTHORITY': (None, None),
 'LORING WOODS PARK': (38.89728, -77.2382244),
 'LUBEC WATER  DISTRICT': (None, None),
 'LYNNS WAY': (40.899833, -73.7709),
 'MACHIAS TRAILER PARK': (25.95904, -109.05496),
 'MACHIAS WATER COMPANY': (44.6911637, -67.4818328),
 'MADAWASKA WATER DISTRICT': (None, None),
 'MAINE WATER COMPANY BIDDEFORD SACO DIV': (5.83739, -5.35723),
 'MAINE WATER COMPANY BUCKSPORT DIVISION': (None, None),
 'MAINE WATER COMPANY CAMDEN & ROCKLAND': (42.13066, -70.91616),
 'MAINE WATER COMPANY FREEPORT DIVISION': (None, None),
 'MAINE WATER COMPANY GREENVILLE DIVISION': (None, None),
 'MAINE WATER COMPANY HARTLAND DIVISION': (None, None),
 'MAINE WATER COMPANY KEZAR FALLS DIVISION': (None, None),
 'MAINE WATER COMPANY MILLINOCKET DIVISION': (None, None),
 'MAINE WATER COMPANY OAKLAND DIVISION': (None, None),
 'MAINE WATER COMPANY SKOWHEGAN DIVISION': (None, None),
 'MAINE WATER COMPANY UNION DIVISION': (None, None),
 'MAINE WATER COMPANY WARREN DIVISION': (None, None),
 'MAPLE RIDGE MOBILE HOME PARK': (36.0889916, -78.9803876),
 'MAPLE TREE ESTATES': (34.9817216, -92.0265818),
 'MAPLESTONE SCHOOL': (45.14914, 11.82057),
 'MAPLEWOOD MOBILE HOME PARK': (32.7708054, -86.583889),
 'MARS HILL AND BLAINE WATER COMPANY': (None, None),
 'MARSH BROOK ESTATES': (43.414066, -70.6620775),
 'MARSHWOOD ESTATES': (43.163129, -70.8072464),
 'MATTAWAMKEAG HOUSING CORP': (45.17805, 5.86432),
 'MAYBERRY HILL PRESCHOOL': (None, None),
 'MCCULLEY COMMONS APARTMENTS': (None, None),
 'MEADOWVIEW APARTMENTS': (39.6696513, -75.5093256),
 'MECHANIC FALLS WATER DEPT': (44.1043909, -70.3902465),
 'MEXICO WATER DISTRICT': (36.5116628, -104.9160755),
 'MIDCOAST REGIONAL REDEVELOP AUTHORITY': (None, None),
 'MILBRIDGE WATER DISTRICT': (None, None),
 'MILDRED L DAY SCHOOL ‐ ARUNDEL': (43.4473765, -70.536395),
 'MILESTONES PRESCHOOL & CHILDCARE': (None, None),
 'MILLSTONE APARTMENTS': (40.3420145, -74.628674),
 'MILO WATER DISTRICT': (None, None),
 'MMCA‐SALT BAY HEAD START': (32.48653, -91.85929),
 'MONMOUTH WATER ASSOCIATION': (None, None),
 'MONSON UTILITIES DISTRICT': (None, None),
 'MONTFORT HEIGHTS': (50.9880991, -1.4710891),
 'MONTICELLO HOUSING CORPORATION': (None, None),
 'MOOSEHEAD TRAIL VILLAGE': (None, None),
 'MORRILL VILLAGE WATER DISTRICT': (None, None),
 'MOSCOW WATER DISTRICT': (55.7025057, 37.6247939),
 'MOUNT DESERT WATER DIST NORTH': (50.33333, 3.66667),
 'MOUNT DESERT WATER DIST ‐SEAL': (None, None),
 'MOUNTAIN VIEW CORRECTIONAL FACILITY': (34.558326, -117.4361598),
 'MOUNTAIN VIEW TRAILER PARK': (37.8816155, -109.3418704),
 'MOUNTAINSIDE MOBILE HOME PARK': (32.1382742, -111.0384348),
 'MSAD 01 MAPLETON ELEM SCHOOL': (45.14914, 11.82057),
 'MSAD 06 BONNY EAGLE HIGH SCHOOL': (43.69696, -70.59866),
 'MSAD 06 BONNY EAGLE MIDDLE SCHOOL': (43.69492, -70.59661),
 'MSAD 06 BUXTON CENTER ELEMENTARY SCHOOL': (45.14914, 11.82057),
 'MSAD 06 FRANK JEWETT SCHOOL': (45.14914, 11.82057),
 'MSAD 06 HB EMERY JR MEMORIAL SCHOOL': (45.14914, 11.82057),
 'MSAD 06 HOLLIS CONSOLIDATED SCHOOL': (45.14914, 11.82057),
 'MSAD 09 CAPE COD HILL SCHOOL': (45.14914, 11.82057),
 'MSAD 11 HELEN THOMPSON SCHOOL': (45.14914, 11.82057),
 'MSAD 17 HARRISON ELEMENTARY SCHOOL': (40.80393, -74.31293),
 'MSAD 17 HEBRON STATION SCHOOL': (45.14914, 11.82057),
 'MSAD 17 OTISFIELD COMMUNITY SCHOOL': (45.14914, 11.82057),
 'MSAD 17 WATERFORD MEMORIAL SCHOOL': (45.14914, 11.82057),
 'MSAD 30 LEE‐WINN ELEMENTARY SCHOOL': (45.14914, 11.82057),
 'MSAD 30 MT JEFFERSON JUNIOR HIGH': (None, None),
 'MSAD 31 ENFIELD STATION ELEMENTARY': (None, None),
 'MSAD 33 WISDOM JR‐SR HIGH SCHOOL': (40.56893, -90.03428),
 'MSAD 37 DANIEL W MERRIT SCHOOL': (45.14914, 11.82057),
 'MSAD 37 HARRINGTON ELEM SCHOOL': (45.14914, 11.82057),
 'MSAD 37 MILBRIDGE ELEMENTARY SCHOOL': (45.14914, 11.82057),
 'MSAD 41 BROWNVILLE ELEM SCHOOL': (45.14914, 11.82057),
 'MSAD 41 MARION C COOK SCHOOL': (45.14914, 11.82057),
 'MSAD 44 WOODSTOCK ELEM SCHOOL': (45.14914, 11.82057),
 'MSAD 49 ALBION ELEMENTARY SCHOOL': (41.39727, -85.41831),
 'MSAD 52 ALTERNATIVE/ADMIN SCHOOL': (45.14914, 11.82057),
 'MSAD 52 GREENE CENTRAL SCHOOL': (45.14914, 11.82057),
 'MSAD 52 LEAVITT AREA HIGH SCHOOL': (40.56893, -90.03428),
 'MSAD 52 LEEDS CENTRAL SCHOOL': (45.14914, 11.82057),
 'MSAD 52 TRIPP MIDDLE SCHOOL': (45.14914, 11.82057),
 'MSAD 52 TURNER ELEMENTARY SCHOOL': (45.14914, 11.82057),
 'MSAD 52 TURNER PRIMARY SCHOOL': (45.14914, 11.82057),
 'MSAD 54 CANAAN ELEMENTARY SCHOOL': (45.14914, 11.82057),
 'MSAD 60 HANSON ELEMENTARY SCHOOL': (45.14914, 11.82057),
 'MSAD 60 KNOWLTON SCHOOL': (45.14914, 11.82057),
 'MSAD 60 LEBANON ELEM SCHOOL': (45.14914, 11.82057),
 'MSAD 60 NOBLE MIDDLE SCHOOL': (45.14914, 11.82057),
 'MSAD 61 CROOKED RIVER SCHOOL': (45.14914, 11.82057),
 'MSAD 61 LAKE REGION HIGH‐ ESB': (None, None),
 'MSAD 61 LAKE REGION MIDDLE SCHOOL': (45.14914, 11.82057),
 'MSAD 61 SONGO LOCKS ELEMENTARY SCHOOL': (45.14914, 11.82057),
 'MSAD 70 HODGDON ELEMENTARY SCHOOL': (45.14914, 11.82057),
 'MSAD 70 HODGDON HIGH SCHOOL': (40.56893, -90.03428),
 'MSAD 72 NEW SUNCOOK SCHOOL': (45.14914, 11.82057),
 'MSAD 75 BOWDOIN CENTRAL SCHOOL': (45.14914, 11.82057),
 'MSAD 75 HARPSWELL ISLAND SCHOOL': (45.14914, 11.82057),
 'MSAD 76 SWANS ISLAND SCHOOL': (45.14914, 11.82057),
 'MSU 103 BEALS ELEMENTARY SCHOOL': (45.14914, 11.82057),
 'MSU 103 JONESPORT ELEM/JBHS': (None, None),
 'MSU 122 WOODLAND CONSOLIDATED SCHOOL': (45.14914, 11.82057),
 'MSU 69 APPLETON VILLAGE SCHOOL': (45.14914, 11.82057),
 'MSU 69 LINCOLNVILLE CENTRAL SCHOOL': (45.14914, 11.82057),
 'MSU 76 BROOKLIN NEW ELEMENTARY SCHOOL': (45.14914, 11.82057),
 'MSU 76 DEER ISLE/STONINGTON K‐8 SCHOOL': (45.14914, 11.82057),
 'MSU 76 DEER ISLE‐STONINGTON JR/SR HS': (None, None),
 'MSU 76 SEDGWICK ELEMENTARY SCHOOL': (45.14914, 11.82057),
 'MSU 93 BLUE HILL CONSOLIDATED SCHOOL': (45.14914, 11.82057),
 'MSU 93 BROOKSVILLE ELEMENTARY SCHOOL': (45.14914, 11.82057),
 'MSU 93 PENOBSCOT ELEMENTARY SCHOOL': (45.14914, 11.82057),
 'MT ABRAM CHALET ASSOCIATION': (None, None),
 'MT ABRAM HIGH SCHOOL': (44.9050465, -70.2711813),
 'MT BLUE STANDARD WATER DISTRICT': (None, None),
 'NARRAGUAGUS ESTATES': (None, None),
 'NEW ENGLAND MUSIC CAMP‐E&PAC': (None, None),
 'NEW GLOUCESTER WATER DISTRICT': (None, None),
 'NEW PORTLAND WATER DISTRICT': (None, None),
 'NEW SHARON WATER DISTRICT': (None, None),
 'NEWBURGH TOWN HALL‐RSU 22': (None, None),
 'NEWPORT WATER DISTRICT': (51.0143102, -4.1988073),
 'NEZINSCOT VILLAGE': (None, None),

In [7]:
df.loc[df['latitude'].isna(), 'latitude'] = df.loc[df['latitude'].isna(), 'sampling_location'].map(
    lambda x: location_cache.get(x, (None, None))[0]
)

df.loc[df['longitude'].isna(), 'longitude'] = df.loc[df['longitude'].isna(), 'sampling_location'].map(
    lambda x: location_cache.get(x, (None, None))[1]
)

In [8]:
df

,sample_id,sampling_location,data_source,latitude,longitude,sampling_date,pws_id,water_system_name,population,well_type,...,city,county,MRL,DL,analytical_methods,is_detected,analyte,concentration,pfas_total,note
0,F4748-FS,Brunswick NAS,DoD,25.05823,-77.34306,2021-10-19,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.32,537.1,False,HFPO-DA,0.00,NaN,NaN
1,F4748-FS,Brunswick NAS,DoD,25.05823,-77.34306,2021-10-19,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.32,537.1,True,PFOS,4.79,NaN,NaN
2,F4748-FS,Brunswick NAS,DoD,25.05823,-77.34306,2021-10-19,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.32,537.1,False,PFUNA,0.00,NaN,NaN
3,F4748-FS,Brunswick NAS,DoD,25.05823,-77.34306,2021-10-19,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.32,537.1,False,NMEFOSAA,0.00,NaN,NaN
4,F4748-FS,Brunswick NAS,DoD,25.05823,-77.34306,2021-10-19,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.59,537.1,False,NETFOSAA,0.00,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20808,NaN,YOULAND CONVENIENCE LLC,Maine DWP,NaN,NaN,2023-03-29,ME0092619,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,True,PFHXA,40.80,NaN,NaN
20809,NaN,YOULAND CONVENIENCE LLC,Maine DWP,NaN,NaN,2023-03-29,ME0092619,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,PFBA,NaN,NaN,NaN
20810,NaN,YOULAND CONVENIENCE LLC,Maine DWP,NaN,NaN,2023-03-29,ME0092619,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,6:2 FTS,NaN,NaN,NaN
20811,NaN,YOULAND CONVENIENCE LLC,Maine DWP,NaN,NaN,2023-03-29,ME0092619,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,PFPEA,NaN,NaN,NaN
20812,NaN,YOULAND CONVENIENCE LLC,Maine DWP,NaN,NaN,2023-03-29,ME0092619,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,PFPES,NaN,NaN,NaN

In [9]:
df.to_csv('maine_dw.csv')