In [1]:
import pandas as pd
import os
import numpy as np

In [2]:
os.getcwd()

'/Users/chuqiwang/Desktop/US_PFAS_Project/Maine'

In [3]:
me_df1 = pd.read_excel('Export_Brunswick NAS.xlsx')

In [4]:
me_df1

,Component ID,Component,State,Installation Name,Installation Type,Lab Report Id,Laboratory Sample ID,Sample Date,Analysis Method,CAS Number,Analyte Abbreviation,Final Result,Limit of Detection,Final Units,Final Qualification,Treatment System,Pre Or Post Treatment
0,1700,Navy,Maine,Brunswick NAS,BRAC,21-1421,F4748-FS,10/19/2021,537.1,13252-13-6,HFPO-DA,NaN,1.320,ng/L,U,No,NaN
1,1700,Navy,Maine,Brunswick NAS,BRAC,21-1421,F4748-FS,10/19/2021,537.1,1763-23-1,PFOS,4.79,1.320,ng/L,NaN,No,NaN
2,1700,Navy,Maine,Brunswick NAS,BRAC,21-1421,F4748-FS,10/19/2021,537.1,2058-94-8,PFUnA,NaN,1.320,ng/L,U,No,NaN
3,1700,Navy,Maine,Brunswick NAS,BRAC,21-1421,F4748-FS,10/19/2021,537.1,2355-31-9,NMeFOSAA,NaN,1.320,ng/L,U,No,NaN
4,1700,Navy,Maine,Brunswick NAS,BRAC,21-1421,F4748-FS,10/19/2021,537.1,2991-50-6,NEtFOSAA,NaN,1.590,ng/L,U,No,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
535,1700,Navy,Maine,Brunswick NAS,BRAC,22-0491,F9632-FS1,3/23/2022,537.0,376-06-7,PFTeDA,NaN,1.240,ng/L,UJ,No,NaN
536,1700,Navy,Maine,Brunswick NAS,BRAC,22-0491,F9632-FS1,3/23/2022,537.0,72629-94-8,PFTrDA,NaN,1.240,ng/L,UJ,No,NaN
537,1700,Navy,Maine,Brunswick NAS,BRAC,22-0491,F9632-FS1,3/23/2022,537.0,756426-58-1,9Cl-PF3ONS,NaN,1.240,ng/L,U,No,NaN
538,1700,Navy,Maine,Brunswick NAS,BRAC,22-0491,F9632-FS1,3/23/2022,537.0,763051-92-9,11Cl-PF3OUdS,NaN,1.240,ng/L,U,No,NaN
539,1700,Navy,Maine,Brunswick NAS,BRAC,22-0491,F9632-FS1,3/23/2022,537.0,919005-14-4,ADONA,NaN,0.988,ng/L,U,No,NaN

In [5]:
columns = {
    'sample_id': str,
    'sampling_location': str,
    'data_source': str,
    'latitude': float,
    'longitude': float,
    'sampling_date': 'datetime64[ns]',
    'pws_id': str,
    'water_system_name': str,
    'population': int,
    'well_type': str,
    'well_depth': float,
    'units': str,
    'source_type': str,
    'state': str,
    'city': str,
    'county': str,
    'MRL': float,
    'DL': float,
    'analytical_methods': str,
    'is_detected': bool,
    'analyte': str,
    'concentration': float,
    'pfas_total': float,
    'note': str   
}

In [6]:
df1 = pd.DataFrame({col: pd.Series(dtype=dt) for col, dt in columns.items()})

In [7]:
df1['analyte'] = me_df1['Analyte Abbreviation'].str.upper()
df1['concentration'] = me_df1['Final Result'].fillna(0)
df1['sampling_location'] = me_df1['Installation Name']
df1['DL'] = me_df1['Limit of Detection']
df1['sampling_date'] = pd.to_datetime(me_df1['Sample Date'])
df1['sample_id'] = me_df1['Laboratory Sample ID']
df1['units'] = me_df1['Final Units']
df1['state'] = me_df1['State']
df1['analytical_methods'] = me_df1['Analysis Method']
df1['data_source'] = 'DoD'
df1['source_type'] = 'drinking water'

In [8]:
df1['is_detected'] = df1['concentration'] != 0

In [9]:
df1

,sample_id,sampling_location,data_source,latitude,longitude,sampling_date,pws_id,water_system_name,population,well_type,...,city,county,MRL,DL,analytical_methods,is_detected,analyte,concentration,pfas_total,note
0,F4748-FS,Brunswick NAS,DoD,NaN,NaN,2021-10-19,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.320,537.1,False,HFPO-DA,0.00,NaN,NaN
1,F4748-FS,Brunswick NAS,DoD,NaN,NaN,2021-10-19,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.320,537.1,True,PFOS,4.79,NaN,NaN
2,F4748-FS,Brunswick NAS,DoD,NaN,NaN,2021-10-19,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.320,537.1,False,PFUNA,0.00,NaN,NaN
3,F4748-FS,Brunswick NAS,DoD,NaN,NaN,2021-10-19,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.320,537.1,False,NMEFOSAA,0.00,NaN,NaN
4,F4748-FS,Brunswick NAS,DoD,NaN,NaN,2021-10-19,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.590,537.1,False,NETFOSAA,0.00,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
535,F9632-FS1,Brunswick NAS,DoD,NaN,NaN,2022-03-23,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.240,537.0,False,PFTEDA,0.00,NaN,NaN
536,F9632-FS1,Brunswick NAS,DoD,NaN,NaN,2022-03-23,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.240,537.0,False,PFTRDA,0.00,NaN,NaN
537,F9632-FS1,Brunswick NAS,DoD,NaN,NaN,2022-03-23,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.240,537.0,False,9CL-PF3ONS,0.00,NaN,NaN
538,F9632-FS1,Brunswick NAS,DoD,NaN,NaN,2022-03-23,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.240,537.0,False,11CL-PF3OUDS,0.00,NaN,NaN
539,F9632-FS1,Brunswick NAS,DoD,NaN,NaN,2022-03-23,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.988,537.0,False,ADONA,0.00,NaN,NaN

In [10]:
me_df2 = pd.read_excel('Export_Loring AFB.xlsx')

In [11]:
me_df2

,Component ID,Component,State,Installation Name,Installation Type,Lab Report Id,Laboratory Sample ID,Sample Date,Analysis Method,CAS Number,Analyte Abbreviation,Final Result,Limit of Detection,Final Units,Final Qualification,Treatment System,Pre Or Post Treatment
0,5700,Air Force,Maine,Loring AFB,BRAC,2110182,2110182-05,10/20/2021,QSM_B15,757124-72-4,4:2FTS,NaN,1.89,ng/L,U,No,NaN
1,5700,Air Force,Maine,Loring AFB,BRAC,2110182,2110182-05,10/20/2021,QSM_B15,27619-97-2,6:2FTS,NaN,1.89,ng/L,U,No,NaN
2,5700,Air Force,Maine,Loring AFB,BRAC,2110182,2110182-05,10/20/2021,QSM_B15,39108-34-4,8:2FTS,NaN,1.89,ng/L,U,No,NaN
3,5700,Air Force,Maine,Loring AFB,BRAC,2110182,2110182-05,10/20/2021,QSM_B15,2991-50-6,NEtFOSAA,NaN,1.89,ng/L,U,No,NaN
4,5700,Air Force,Maine,Loring AFB,BRAC,2110182,2110182-05,10/20/2021,QSM_B15,2355-31-9,NMeFOSAA,NaN,1.89,ng/L,U,No,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2056,5700,Air Force,Maine,Loring AFB,BRAC,C449535,YKI774,2/15/2024,1633,79780-39-5,PFDoS,NaN,0.90,ng/L,U,No,NaN
2057,5700,Air Force,Maine,Loring AFB,BRAC,C449535,YKI774,2/15/2024,1633,812-70-4,7:3FTCA,NaN,28.00,ng/L,U,No,NaN
2058,5700,Air Force,Maine,Loring AFB,BRAC,C449535,YKI774,2/15/2024,1633,863090-89-5,PFMBA,NaN,0.45,ng/L,U,No,NaN
2059,5700,Air Force,Maine,Loring AFB,BRAC,C449535,YKI774,2/15/2024,1633,914637-49-3,5:3FTCA,NaN,28.00,ng/L,U,No,NaN
2060,5700,Air Force,Maine,Loring AFB,BRAC,C449535,YKI774,2/15/2024,1633,919005-14-4,ADONA,NaN,3.40,ng/L,U,No,NaN

In [12]:
df2 = pd.DataFrame({col: pd.Series(dtype=dt) for col, dt in columns.items()})
df2['analyte'] = me_df2['Analyte Abbreviation'].str.upper()
df2['concentration'] = me_df2['Final Result'].fillna(0)
df2['sampling_location'] = me_df2['Installation Name']
df2['DL'] = me_df2['Limit of Detection']
df2['sampling_date'] = pd.to_datetime(me_df2['Sample Date'])
df2['sample_id'] = me_df2['Laboratory Sample ID']
df2['units'] = me_df2['Final Units']
df2['state'] = me_df2['State']
df2['analytical_methods'] = me_df2['Analysis Method']
df2['data_source'] = 'DoD'
df2['source_type'] = 'drinking water'

In [13]:
df2['is_detected'] = df2['concentration'] != 0

In [14]:
me_df3 = pd.read_excel('Export_NCTAMSLANT DET CUTLER.xlsx')

In [15]:
me_df3

,Component ID,Component,State,Installation Name,Installation Type,Lab Report Id,Laboratory Sample ID,Sample Date,Analysis Method,CAS Number,Analyte Abbreviation,Final Result,Limit of Detection,Final Units,Final Qualification,Treatment System,Pre Or Post Treatment
0,1700,Navy,Maine,NCTAMSLANT DET CUTLER,Active,21-1312,F3754-FS,10/4/2021,537.0,13252-13-6,HFPO-DA,NaN,1.270,ng/L,U,No,NaN
1,1700,Navy,Maine,NCTAMSLANT DET CUTLER,Active,21-1312,F3754-FS,10/4/2021,537.0,1763-23-1,PFOS,36.1,1.270,ng/L,NaN,No,NaN
2,1700,Navy,Maine,NCTAMSLANT DET CUTLER,Active,21-1312,F3754-FS,10/4/2021,537.0,2058-94-8,PFUnA,NaN,1.270,ng/L,U,No,NaN
3,1700,Navy,Maine,NCTAMSLANT DET CUTLER,Active,21-1312,F3754-FS,10/4/2021,537.0,2355-31-9,NMeFOSAA,NaN,1.270,ng/L,U,No,NaN
4,1700,Navy,Maine,NCTAMSLANT DET CUTLER,Active,21-1312,F3754-FS,10/4/2021,537.0,2991-50-6,NEtFOSAA,NaN,1.520,ng/L,U,No,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7987,1700,Navy,Maine,NCTAMSLANT DET CUTLER,Active,23-0357,D3739-FS,3/21/2023,537.1,376-06-7,PFTeDA,NaN,1.200,ng/L,UJ,Yes,pre-treatment
7988,1700,Navy,Maine,NCTAMSLANT DET CUTLER,Active,23-0357,D3739-FS,3/21/2023,537.1,72629-94-8,PFTrDA,NaN,1.200,ng/L,UJ,Yes,pre-treatment
7989,1700,Navy,Maine,NCTAMSLANT DET CUTLER,Active,23-0357,D3739-FS,3/21/2023,537.1,756426-58-1,9Cl-PF3ONS,NaN,1.200,ng/L,U,Yes,pre-treatment
7990,1700,Navy,Maine,NCTAMSLANT DET CUTLER,Active,23-0357,D3739-FS,3/21/2023,537.1,763051-92-9,11Cl-PF3OUdS,NaN,1.200,ng/L,U,Yes,pre-treatment
7991,1700,Navy,Maine,NCTAMSLANT DET CUTLER,Active,23-0357,D3739-FS,3/21/2023,537.1,919005-14-4,ADONA,NaN,0.962,ng/L,UJ,Yes,pre-treatment

In [16]:
df3 = pd.DataFrame({col: pd.Series(dtype=dt) for col, dt in columns.items()})
df3['analyte'] = me_df3['Analyte Abbreviation'].str.upper()
df3['concentration'] = me_df3['Final Result'].fillna(0)
df3['sampling_location'] = me_df3['Installation Name']
df3['DL'] = me_df3['Limit of Detection']
df3['sampling_date'] = pd.to_datetime(me_df3['Sample Date'])
df3['sample_id'] = me_df3['Laboratory Sample ID']
df3['units'] = me_df3['Final Units']
df3['state'] = me_df3['State']
df3['analytical_methods'] = me_df3['Analysis Method']
df3['data_source'] = 'DoD'
df3['source_type'] = 'drinking water'

In [17]:
df3['is_detected'] = df3['concentration'] != 0

In [18]:
me_df4 = pd.read_csv('tabula-PFASallResults.csv')
me_df4

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Sum of the six,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,NaN,NaN,NaN,NaN,Maine‐,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2820,NaN,NaN
1,NaN,NaN,NaN,NaN,regulated PFAS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PERFLUOROOCTANE,NaN,NaN
2,NaN,NaN,NaN,Collection,analytes (2802‐,2801,2802,2803,2804,2805,2806,2807,2808,2809,2819,SULFONIC ACID,2824,2828
3,PWSID,System Name,Facility,Date,2807),(PFBS),(PFHPA),(PFHXS),(PFNA),(PFOS),(PFOA),(PFDA),(PFDOA),(PFHXA),(PFBA),6:2 FTS,(PFPEA),(PFPES)
4,ME0092649,39 LIMERICK ROAD LLC,TREAT PT 1,8/1/2023,14.2,ND,2.12,ND,ND,5.04,7.05,ND,ND,8.45,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
742,ME0091670,YARMOUTH WATER DISTRICT,TREAT PT 4,7/26/2022,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,NaN,NaN,NaN,NaN
743,ME0020883,YORK COUNTY SHELTERS,WELL HD 1,4/29/2022,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND
744,ME0091680,YORK WATER DISTRICT,TREAT PT 1,8/10/2022,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,NaN,NaN,NaN,NaN
745,ME0092619,YOULAND CONVENIENCE LLC,TREAT PT 1,1/18/2024,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,NaN,NaN,NaN,NaN
746,ME0092619,YOULAND CONVENIENCE LLC,WELL HD 1,3/29/2023,274,2.28,89,6.36,10.2,33.1,135,ND,ND,40.8,NaN,NaN,NaN,NaN

In [19]:
me_df4 = me_df4.drop([0, 1, 2])

In [20]:
me_df4.columns = list(me_df4.iloc[0])

In [23]:
me_df4 = me_df4.rename(columns={'2807)': 'PFHPA+PFHXS+PFNA+PFOS+PFOA+PFDA'})

In [25]:
me_df4 = me_df4.drop([3])

In [26]:
me_df4

,PWSID,System Name,Facility,Date,PFHPA+PFHXS+PFNA+PFOS+PFOA+PFDA,(PFBS),(PFHPA),(PFHXS),(PFNA),(PFOS),(PFOA),(PFDA),(PFDOA),(PFHXA),(PFBA),6:2 FTS,(PFPEA),(PFPES)
4,ME0092649,39 LIMERICK ROAD LLC,TREAT PT 1,8/1/2023,14.2,ND,2.12,ND,ND,5.04,7.05,ND,ND,8.45,NaN,NaN,NaN,NaN
5,ME0092373,A PLACE FOR ALL SEASONS,TREAT PT 1,11/15/2023,2.51,ND,ND,ND,ND,2.51,ND,ND,ND,ND,NaN,NaN,NaN,NaN
6,ME0094712,ACAP CHILD & FAMILY CENTER,TREAT PT 1,5/31/2022,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND
7,ME0000002,ACTON ELEMENTARY SCHOOL,WELL HD 2,6/13/2022,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,NaN,NaN,NaN,NaN
8,ME0090010,ADDISON POINT WATER DISTRICT,TREAT PT 1,2/27/2024,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
742,ME0091670,YARMOUTH WATER DISTRICT,TREAT PT 4,7/26/2022,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,NaN,NaN,NaN,NaN
743,ME0020883,YORK COUNTY SHELTERS,WELL HD 1,4/29/2022,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND
744,ME0091680,YORK WATER DISTRICT,TREAT PT 1,8/10/2022,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,NaN,NaN,NaN,NaN
745,ME0092619,YOULAND CONVENIENCE LLC,TREAT PT 1,1/18/2024,ND,ND,ND,ND,ND,ND,ND,ND,ND,ND,NaN,NaN,NaN,NaN
746,ME0092619,YOULAND CONVENIENCE LLC,WELL HD 1,3/29/2023,274,2.28,89,6.36,10.2,33.1,135,ND,ND,40.8,NaN,NaN,NaN,NaN

In [30]:
me_df4 = me_df4[me_df4['PWSID'] != 'PWSID']

In [33]:
me_df4 = me_df4.replace('ND', 0)

/var/folders/m8/kh2nk5652k94h_n7lqjvr8n00000gn/T/ipykernel_3809/791087114.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  me_df4 = me_df4.replace('ND', 0)

In [35]:
me_df4.columns = me_df4.columns.str.replace(r'\(|\)', '', regex=True)

In [36]:
me_df4.index = range(0, len(me_df4))

In [37]:
me_df4

,PWSID,System Name,Facility,Date,PFHPA+PFHXS+PFNA+PFOS+PFOA+PFDA,PFBS,PFHPA,PFHXS,PFNA,PFOS,PFOA,PFDA,PFDOA,PFHXA,PFBA,6:2 FTS,PFPEA,PFPES
0,ME0092649,39 LIMERICK ROAD LLC,TREAT PT 1,8/1/2023,14.2,0,2.12,0,0,5.04,7.05,0,0.0,8.45,NaN,NaN,NaN,NaN
1,ME0092373,A PLACE FOR ALL SEASONS,TREAT PT 1,11/15/2023,2.51,0,0,0,0,2.51,0,0,0.0,0,NaN,NaN,NaN,NaN
2,ME0094712,ACAP CHILD & FAMILY CENTER,TREAT PT 1,5/31/2022,0,0,0,0,0,0,0,0,0.0,0,0,0,0,0
3,ME0000002,ACTON ELEMENTARY SCHOOL,WELL HD 2,6/13/2022,0,0,0,0,0,0,0,0,0.0,0,NaN,NaN,NaN,NaN
4,ME0090010,ADDISON POINT WATER DISTRICT,TREAT PT 1,2/27/2024,0,0,0,0,0,0,0,0,0.0,0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
725,ME0091670,YARMOUTH WATER DISTRICT,TREAT PT 4,7/26/2022,0,0,0,0,0,0,0,0,0.0,0,NaN,NaN,NaN,NaN
726,ME0020883,YORK COUNTY SHELTERS,WELL HD 1,4/29/2022,0,0,0,0,0,0,0,0,0.0,0,0,0,0,0
727,ME0091680,YORK WATER DISTRICT,TREAT PT 1,8/10/2022,0,0,0,0,0,0,0,0,0.0,0,NaN,NaN,NaN,NaN
728,ME0092619,YOULAND CONVENIENCE LLC,TREAT PT 1,1/18/2024,0,0,0,0,0,0,0,0,0.0,0,NaN,NaN,NaN,NaN
729,ME0092619,YOULAND CONVENIENCE LLC,WELL HD 1,3/29/2023,274,2.28,89,6.36,10.2,33.1,135,0,0.0,40.8,NaN,NaN,NaN,NaN

In [43]:
len(list(me_df4.columns)[4:18])

14

In [44]:
list(me_df4.columns)[4:18]

['PFHPA+PFHXS+PFNA+PFOS+PFOA+PFDA',
 'PFBS',
 'PFHPA',
 'PFHXS',
 'PFNA',
 'PFOS',
 'PFOA',
 'PFDA',
 'PFDOA',
 'PFHXA',
 'PFBA',
 '6:2 FTS',
 'PFPEA',
 'PFPES']

In [45]:
columns_to_repeat = ['PWSID', 'System Name', 'Facility', 'Date']
df_repeated = pd.DataFrame(columns=columns_to_repeat)

for i in range(len(me_df4)):
    row_repeated = pd.concat([me_df4.iloc[[i]][columns_to_repeat]] * 14, ignore_index=True)
    df_repeated = pd.concat([df_repeated, row_repeated], ignore_index=True)

df_repeated

           PWSID              System Name    Facility       Date
0      ME0092649     39 LIMERICK ROAD LLC  TREAT PT 1   8/1/2023
1      ME0092649     39 LIMERICK ROAD LLC  TREAT PT 1   8/1/2023
2      ME0092649     39 LIMERICK ROAD LLC  TREAT PT 1   8/1/2023
3      ME0092649     39 LIMERICK ROAD LLC  TREAT PT 1   8/1/2023
4      ME0092649     39 LIMERICK ROAD LLC  TREAT PT 1   8/1/2023
...          ...                      ...         ...        ...
10215  ME0092619  YOULAND CONVENIENCE LLC   WELL HD 1  3/29/2023
10216  ME0092619  YOULAND CONVENIENCE LLC   WELL HD 1  3/29/2023
10217  ME0092619  YOULAND CONVENIENCE LLC   WELL HD 1  3/29/2023
10218  ME0092619  YOULAND CONVENIENCE LLC   WELL HD 1  3/29/2023
10219  ME0092619  YOULAND CONVENIENCE LLC   WELL HD 1  3/29/2023

[10220 rows x 4 columns]

In [46]:
df_repeated['analyte'] = list(me_df4.columns)[4:18] * len(me_df4)

In [47]:
df_repeated

,PWSID,System Name,Facility,Date,analyte
0,ME0092649,39 LIMERICK ROAD LLC,TREAT PT 1,8/1/2023,PFHPA+PFHXS+PFNA+PFOS+PFOA+PFDA
1,ME0092649,39 LIMERICK ROAD LLC,TREAT PT 1,8/1/2023,PFBS
2,ME0092649,39 LIMERICK ROAD LLC,TREAT PT 1,8/1/2023,PFHPA
3,ME0092649,39 LIMERICK ROAD LLC,TREAT PT 1,8/1/2023,PFHXS
4,ME0092649,39 LIMERICK ROAD LLC,TREAT PT 1,8/1/2023,PFNA
...,...,...,...,...,...
10215,ME0092619,YOULAND CONVENIENCE LLC,WELL HD 1,3/29/2023,PFHXA
10216,ME0092619,YOULAND CONVENIENCE LLC,WELL HD 1,3/29/2023,PFBA
10217,ME0092619,YOULAND CONVENIENCE LLC,WELL HD 1,3/29/2023,6:2 FTS
10218,ME0092619,YOULAND CONVENIENCE LLC,WELL HD 1,3/29/2023,PFPEA
10219,ME0092619,YOULAND CONVENIENCE LLC,WELL HD 1,3/29/2023,PFPES

In [48]:
analyte_list = list(me_df4.columns)[4:18]

In [49]:
me_df4[analyte_list]

,PFHPA+PFHXS+PFNA+PFOS+PFOA+PFDA,PFBS,PFHPA,PFHXS,PFNA,PFOS,PFOA,PFDA,PFDOA,PFHXA,PFBA,6:2 FTS,PFPEA,PFPES
0,14.2,0,2.12,0,0,5.04,7.05,0,0.0,8.45,NaN,NaN,NaN,NaN
1,2.51,0,0,0,0,2.51,0,0,0.0,0,NaN,NaN,NaN,NaN
2,0,0,0,0,0,0,0,0,0.0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0.0,0,NaN,NaN,NaN,NaN
4,0,0,0,0,0,0,0,0,0.0,0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
725,0,0,0,0,0,0,0,0,0.0,0,NaN,NaN,NaN,NaN
726,0,0,0,0,0,0,0,0,0.0,0,0,0,0,0
727,0,0,0,0,0,0,0,0,0.0,0,NaN,NaN,NaN,NaN
728,0,0,0,0,0,0,0,0,0.0,0,NaN,NaN,NaN,NaN
729,274,2.28,89,6.36,10.2,33.1,135,0,0.0,40.8,NaN,NaN,NaN,NaN

In [52]:
me_df4[analyte_list] = me_df4[analyte_list].astype(float)

In [53]:
me_df4[analyte_list].values.flatten().tolist()

[14.2,
 0.0,
 2.12,
 0.0,
 0.0,
 5.04,
 7.05,
 0.0,
 0.0,
 8.45,
 nan,
 nan,
 nan,
 nan,
 2.51,
 0.0,
 0.0,
 0.0,
 0.0,
 2.51,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 16.6,
 0.0,
 3.12,
 0.0,
 3.49,
 0.0,
 9.96,
 0.0,
 0.0,
 12.7,
 nan,
 nan,
 nan,
 nan,
 12.8,
 4.24,
 0.0,
 8.05,
 0.0,
 0.0,
 4.74,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 11.8,
 0.0,
 30.6,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 20.8,
 2.9,
 3.84,
 0.0,
 2.82,
 4.55,
 9.54,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 3.31,
 0.0,
 0.0,
 0.0,
 3.31,
 0.0,
 0.0,
 0.0,
 0.0,
 2.26,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 3.64,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 22.15,
 2.42,
 6.44,
 0.0,
 0.0,
 3.71,
 12.0,
 0.0,
 0.0,
 8.23,
 5.52,
 0.0,
 11.1,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 9.27,
 0.0,
 0.0,
 7.1,
 0.0,
 2.17,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 13.9,
 2.76,
 0.0,
 0.0,
 0.0,
 4.24,
 9.61,
 0.0,
 0.0,
 2.94,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 5.16,
 9.5,
 0.0,
 0.0,
 0.0,
 3.14,
 2.02,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 4.82,
 0.0,
 0.0,
 0.0,
 0.0,
 4.82,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 3.95,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 3.95,
 0.0,
 0.0,
 3.34,
 4.49,
 0.0,
 4.38,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 4.64,
 0.0,
 0.0,
 0.0,
 0.0,
 2.57,
 2.07,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 2.36,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 2.36,
 0.0,
 0.0,
 4.32,
 7.36,
 0.0,
 2.87,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 8.29,
 3.23,
 0.0,
 0.0,
 0.0,
 2.95,
 5.34,
 0.0,
 0.0,
 11.4,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 nan,
 nan,
 nan,
 nan,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 ...]

In [54]:
len(me_df4[analyte_list].values.flatten().tolist())

10220

In [55]:
df_repeated['concentration'] = me_df4[analyte_list].values.flatten().tolist()

In [56]:
def set_is_detected(concentration):
    if pd.isna(concentration):
        return np.nan
    return concentration != 0

In [57]:
df_repeated['is_detected'] = df_repeated['concentration'].apply(set_is_detected)

In [58]:
df_repeated

,PWSID,System Name,Facility,Date,analyte,concentration,is_detected
0,ME0092649,39 LIMERICK ROAD LLC,TREAT PT 1,8/1/2023,PFHPA+PFHXS+PFNA+PFOS+PFOA+PFDA,14.20,True
1,ME0092649,39 LIMERICK ROAD LLC,TREAT PT 1,8/1/2023,PFBS,0.00,False
2,ME0092649,39 LIMERICK ROAD LLC,TREAT PT 1,8/1/2023,PFHPA,2.12,True
3,ME0092649,39 LIMERICK ROAD LLC,TREAT PT 1,8/1/2023,PFHXS,0.00,False
4,ME0092649,39 LIMERICK ROAD LLC,TREAT PT 1,8/1/2023,PFNA,0.00,False
...,...,...,...,...,...,...,...
10215,ME0092619,YOULAND CONVENIENCE LLC,WELL HD 1,3/29/2023,PFHXA,40.80,True
10216,ME0092619,YOULAND CONVENIENCE LLC,WELL HD 1,3/29/2023,PFBA,NaN,NaN
10217,ME0092619,YOULAND CONVENIENCE LLC,WELL HD 1,3/29/2023,6:2 FTS,NaN,NaN
10218,ME0092619,YOULAND CONVENIENCE LLC,WELL HD 1,3/29/2023,PFPEA,NaN,NaN
10219,ME0092619,YOULAND CONVENIENCE LLC,WELL HD 1,3/29/2023,PFPES,NaN,NaN

In [59]:
df4 = pd.DataFrame({col: pd.Series(dtype=dt) for col, dt in columns.items()})
df4['analyte'] = df_repeated['analyte'].str.upper()
df4['concentration'] = df_repeated['concentration']
df4['sampling_location'] = df_repeated['System Name']
df4['sampling_date'] = pd.to_datetime(df_repeated['Date'])
df4['units'] = 'ng/L'
df4['state'] = 'Maine'
df4['data_source'] = 'Maine DWP'
df4['source_type'] = 'drinking water'
df4['pws_id'] = df_repeated['PWSID']
df4['is_detected'] = df_repeated['is_detected']

In [60]:
df4

,sample_id,sampling_location,data_source,latitude,longitude,sampling_date,pws_id,water_system_name,population,well_type,...,city,county,MRL,DL,analytical_methods,is_detected,analyte,concentration,pfas_total,note
0,NaN,39 LIMERICK ROAD LLC,Maine DWP,NaN,NaN,2023-08-01,ME0092649,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,True,PFHPA+PFHXS+PFNA+PFOS+PFOA+PFDA,14.20,NaN,NaN
1,NaN,39 LIMERICK ROAD LLC,Maine DWP,NaN,NaN,2023-08-01,ME0092649,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,False,PFBS,0.00,NaN,NaN
2,NaN,39 LIMERICK ROAD LLC,Maine DWP,NaN,NaN,2023-08-01,ME0092649,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,True,PFHPA,2.12,NaN,NaN
3,NaN,39 LIMERICK ROAD LLC,Maine DWP,NaN,NaN,2023-08-01,ME0092649,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,False,PFHXS,0.00,NaN,NaN
4,NaN,39 LIMERICK ROAD LLC,Maine DWP,NaN,NaN,2023-08-01,ME0092649,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,False,PFNA,0.00,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10215,NaN,YOULAND CONVENIENCE LLC,Maine DWP,NaN,NaN,2023-03-29,ME0092619,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,True,PFHXA,40.80,NaN,NaN
10216,NaN,YOULAND CONVENIENCE LLC,Maine DWP,NaN,NaN,2023-03-29,ME0092619,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,PFBA,NaN,NaN,NaN
10217,NaN,YOULAND CONVENIENCE LLC,Maine DWP,NaN,NaN,2023-03-29,ME0092619,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,6:2 FTS,NaN,NaN,NaN
10218,NaN,YOULAND CONVENIENCE LLC,Maine DWP,NaN,NaN,2023-03-29,ME0092619,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,PFPEA,NaN,NaN,NaN
10219,NaN,YOULAND CONVENIENCE LLC,Maine DWP,NaN,NaN,2023-03-29,ME0092619,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,PFPES,NaN,NaN,NaN

In [61]:
df = pd.concat([df1, df2, df3, df4])

In [62]:
df.index = range(0, len(df))

In [63]:
df

,sample_id,sampling_location,data_source,latitude,longitude,sampling_date,pws_id,water_system_name,population,well_type,...,city,county,MRL,DL,analytical_methods,is_detected,analyte,concentration,pfas_total,note
0,F4748-FS,Brunswick NAS,DoD,NaN,NaN,2021-10-19,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.32,537.1,False,HFPO-DA,0.00,NaN,NaN
1,F4748-FS,Brunswick NAS,DoD,NaN,NaN,2021-10-19,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.32,537.1,True,PFOS,4.79,NaN,NaN
2,F4748-FS,Brunswick NAS,DoD,NaN,NaN,2021-10-19,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.32,537.1,False,PFUNA,0.00,NaN,NaN
3,F4748-FS,Brunswick NAS,DoD,NaN,NaN,2021-10-19,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.32,537.1,False,NMEFOSAA,0.00,NaN,NaN
4,F4748-FS,Brunswick NAS,DoD,NaN,NaN,2021-10-19,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.59,537.1,False,NETFOSAA,0.00,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20808,NaN,YOULAND CONVENIENCE LLC,Maine DWP,NaN,NaN,2023-03-29,ME0092619,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,True,PFHXA,40.80,NaN,NaN
20809,NaN,YOULAND CONVENIENCE LLC,Maine DWP,NaN,NaN,2023-03-29,ME0092619,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,PFBA,NaN,NaN,NaN
20810,NaN,YOULAND CONVENIENCE LLC,Maine DWP,NaN,NaN,2023-03-29,ME0092619,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,6:2 FTS,NaN,NaN,NaN
20811,NaN,YOULAND CONVENIENCE LLC,Maine DWP,NaN,NaN,2023-03-29,ME0092619,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,PFPEA,NaN,NaN,NaN
20812,NaN,YOULAND CONVENIENCE LLC,Maine DWP,NaN,NaN,2023-03-29,ME0092619,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,PFPES,NaN,NaN,NaN

In [64]:
df.to_csv('maine_dw.csv')