In [1]:
import pandas as pd
import os
import numpy as np

In [2]:
os.getcwd()

'/Users/chuqiwang/Desktop/US_PFAS_Project/data_analysis'

In [3]:
ppl_df = pd.read_excel('../PFAS Sites and Community Resources.xlsx')

In [4]:
ppl_df

,Site Name,State,Industry,Sample matrix,Sample date,PFOA (ppt),PFOS (ppt),PFOA+PFOS from one sample (ppt),Total PFAS from one sample (ppt)
0,Brookhaven/Aquadome Landfill,Alabama,Landfill,Groundwater,2019.0,NaN,3770,NaN,NaN
1,Deer Springs Landfill,Alabama,Landfill,Groundwater,2019.0,NaN,NaN,NaN,236000.0
2,Maxwell-Gunter Air Force Base,Alabama,Military,Groundwater,2017.0,84000,38000,122000,540637.0
3,Montgomery Air National Guard Base,Alabama,Military,Groundwater,2018.0,1200,260,1460,9564.0
4,Mud Tavern Landfill,Alabama,Landfill,Groundwater,2019.0,67200,25000,NaN,69675.0
...,...,...,...,...,...,...,...,...,...
2049,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2050,Camp Guernsey,Wyoming,Military,Drinking Water,2018.0,1,NaN,NaN,7.0
2051,Cheyenne Air National Guard Base,Wyoming,Military,Groundwater,2018.0,8500,89000,94400,122440.0
2052,Cheyenne Regional Airport,Wyoming,Military,Groundwater,2018.0,8500,89000,94400,NaN
2053,F.E. Warren Air Force Base,Wyoming,Military,Groundwater,2017.0,72000,64000,136000,147000.0

In [5]:
ppl_df[ppl_df.isna().all(axis=1)]

,Site Name,State,Industry,Sample matrix,Sample date,PFOA (ppt),PFOS (ppt),PFOA+PFOS from one sample (ppt),Total PFAS from one sample (ppt)
47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
379,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
384,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
391,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
395,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
396,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
405,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
430,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
458,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
592,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
593,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
615,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
655,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
656,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
678,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
679,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
850,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1081,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1562,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1563,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1592,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1730,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1735,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1736,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1821,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1822,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1979,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1980,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1986,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2035,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2036,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2039,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2040,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2042,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2043,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2049,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
ppl_df = ppl_df.dropna(how='all')

In [7]:
ppl_df

,Site Name,State,Industry,Sample matrix,Sample date,PFOA (ppt),PFOS (ppt),PFOA+PFOS from one sample (ppt),Total PFAS from one sample (ppt)
0,Brookhaven/Aquadome Landfill,Alabama,Landfill,Groundwater,2019.0,NaN,3770,NaN,NaN
1,Deer Springs Landfill,Alabama,Landfill,Groundwater,2019.0,NaN,NaN,NaN,236000.0
2,Maxwell-Gunter Air Force Base,Alabama,Military,Groundwater,2017.0,84000,38000,122000,540637.0
3,Montgomery Air National Guard Base,Alabama,Military,Groundwater,2018.0,1200,260,1460,9564.0
4,Mud Tavern Landfill,Alabama,Landfill,Groundwater,2019.0,67200,25000,NaN,69675.0
...,...,...,...,...,...,...,...,...,...
2048,WRR Environmental ERVCS,Wisconsin,AFFF,Groundwater,2021.0,3800,2300,5400,20905.0
2050,Camp Guernsey,Wyoming,Military,Drinking Water,2018.0,1,NaN,NaN,7.0
2051,Cheyenne Air National Guard Base,Wyoming,Military,Groundwater,2018.0,8500,89000,94400,122440.0
2052,Cheyenne Regional Airport,Wyoming,Military,Groundwater,2018.0,8500,89000,94400,NaN
2053,F.E. Warren Air Force Base,Wyoming,Military,Groundwater,2017.0,72000,64000,136000,147000.0

In [8]:
columns = {
    'sample_id': str,
    'sampling_location': str,
    'data_source': str,
    'latitude': float,
    'longitude': float,
    'sampling_date': 'datetime64[ns]',
    'pws_id': str,
    'water_system_name': str,
    'population': int,
    'well_type': str,
    'well_depth': float,
    'units': str,
    'source_type': str,
    'state': str,
    'city': str,
    'county': str,
    'MRL': float,
    'DL': float,
    'analytical_methods': str,
    'is_detected': bool,
    'analyte': str,
    'concentration': float,
    'pfas_total': float,
    'note': str   
}

In [9]:
analyte_list = ['PFOA', 'PFOS', 'PFOA+PFOS']

In [10]:
columns_to_repeat = ['Site Name', 'State', 'Industry', 'Sample matrix', 'Sample date', 'Total PFAS from one sample (ppt)']
df_repeated = pd.DataFrame(columns=columns_to_repeat)

for i in range(len(ppl_df)):
    row_repeated = pd.concat([ppl_df.iloc[[i]][columns_to_repeat]] * len(analyte_list), ignore_index=True)
    df_repeated = pd.concat([df_repeated, row_repeated], ignore_index=True)

df_repeated

/var/folders/m8/kh2nk5652k94h_n7lqjvr8n00000gn/T/ipykernel_21000/2481698385.py:6: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_repeated = pd.concat([df_repeated, row_repeated], ignore_index=True)

,Site Name,State,Industry,Sample matrix,Sample date,Total PFAS from one sample (ppt)
0,Brookhaven/Aquadome Landfill,Alabama,Landfill,Groundwater,2019.0,NaN
1,Brookhaven/Aquadome Landfill,Alabama,Landfill,Groundwater,2019.0,NaN
2,Brookhaven/Aquadome Landfill,Alabama,Landfill,Groundwater,2019.0,NaN
3,Deer Springs Landfill,Alabama,Landfill,Groundwater,2019.0,236000.0
4,Deer Springs Landfill,Alabama,Landfill,Groundwater,2019.0,236000.0
...,...,...,...,...,...,...
6034,Cheyenne Regional Airport,Wyoming,Military,Groundwater,2018.0,NaN
6035,Cheyenne Regional Airport,Wyoming,Military,Groundwater,2018.0,NaN
6036,F.E. Warren Air Force Base,Wyoming,Military,Groundwater,2017.0,147000.0
6037,F.E. Warren Air Force Base,Wyoming,Military,Groundwater,2017.0,147000.0
6038,F.E. Warren Air Force Base,Wyoming,Military,Groundwater,2017.0,147000.0

In [11]:
df_repeated['analyte'] = analyte_list * len(ppl_df)

In [12]:
df_repeated

,Site Name,State,Industry,Sample matrix,Sample date,Total PFAS from one sample (ppt),analyte
0,Brookhaven/Aquadome Landfill,Alabama,Landfill,Groundwater,2019.0,NaN,PFOA
1,Brookhaven/Aquadome Landfill,Alabama,Landfill,Groundwater,2019.0,NaN,PFOS
2,Brookhaven/Aquadome Landfill,Alabama,Landfill,Groundwater,2019.0,NaN,PFOA+PFOS
3,Deer Springs Landfill,Alabama,Landfill,Groundwater,2019.0,236000.0,PFOA
4,Deer Springs Landfill,Alabama,Landfill,Groundwater,2019.0,236000.0,PFOS
...,...,...,...,...,...,...,...
6034,Cheyenne Regional Airport,Wyoming,Military,Groundwater,2018.0,NaN,PFOS
6035,Cheyenne Regional Airport,Wyoming,Military,Groundwater,2018.0,NaN,PFOA+PFOS
6036,F.E. Warren Air Force Base,Wyoming,Military,Groundwater,2017.0,147000.0,PFOA
6037,F.E. Warren Air Force Base,Wyoming,Military,Groundwater,2017.0,147000.0,PFOS
6038,F.E. Warren Air Force Base,Wyoming,Military,Groundwater,2017.0,147000.0,PFOA+PFOS

In [13]:
ppl_df = ppl_df.replace('<2', 0)

/var/folders/m8/kh2nk5652k94h_n7lqjvr8n00000gn/T/ipykernel_21000/1960188465.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  ppl_df = ppl_df.replace('<2', 0)

In [14]:
ppl_df = ppl_df.replace('>70', 70)

/var/folders/m8/kh2nk5652k94h_n7lqjvr8n00000gn/T/ipykernel_21000/3321474041.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  ppl_df = ppl_df.replace('>70', 70)

In [15]:
ppl_df[['PFOA (ppt)', 'PFOS (ppt)', 'PFOA+PFOS from one sample (ppt)']] = ppl_df[['PFOA (ppt)', 'PFOS (ppt)', 'PFOA+PFOS from one sample (ppt)']].astype(float)

In [16]:
df_repeated['concentration'] = ppl_df[['PFOA (ppt)', 'PFOS (ppt)', 'PFOA+PFOS from one sample (ppt)']].values.flatten().tolist()

In [17]:
def set_is_detected(concentration):
    if pd.isna(concentration):
        return np.nan
    return concentration != 0

In [18]:
df_repeated['is_detected'] = df_repeated['concentration'].apply(set_is_detected)

In [19]:
df_repeated

,Site Name,State,Industry,Sample matrix,Sample date,Total PFAS from one sample (ppt),analyte,concentration,is_detected
0,Brookhaven/Aquadome Landfill,Alabama,Landfill,Groundwater,2019.0,NaN,PFOA,NaN,NaN
1,Brookhaven/Aquadome Landfill,Alabama,Landfill,Groundwater,2019.0,NaN,PFOS,3770.0,True
2,Brookhaven/Aquadome Landfill,Alabama,Landfill,Groundwater,2019.0,NaN,PFOA+PFOS,NaN,NaN
3,Deer Springs Landfill,Alabama,Landfill,Groundwater,2019.0,236000.0,PFOA,NaN,NaN
4,Deer Springs Landfill,Alabama,Landfill,Groundwater,2019.0,236000.0,PFOS,NaN,NaN
...,...,...,...,...,...,...,...,...,...
6034,Cheyenne Regional Airport,Wyoming,Military,Groundwater,2018.0,NaN,PFOS,89000.0,True
6035,Cheyenne Regional Airport,Wyoming,Military,Groundwater,2018.0,NaN,PFOA+PFOS,94400.0,True
6036,F.E. Warren Air Force Base,Wyoming,Military,Groundwater,2017.0,147000.0,PFOA,72000.0,True
6037,F.E. Warren Air Force Base,Wyoming,Military,Groundwater,2017.0,147000.0,PFOS,64000.0,True
6038,F.E. Warren Air Force Base,Wyoming,Military,Groundwater,2017.0,147000.0,PFOA+PFOS,136000.0,True

In [20]:
df = pd.DataFrame({col: pd.Series(dtype=dt) for col, dt in columns.items()})
df['analyte'] = df_repeated['analyte'].str.upper()
df['concentration'] = df_repeated['concentration']
df['sampling_location'] = df_repeated['Site Name']
df['sampling_date'] = df_repeated['Sample date'].astype('Int64')
df['units'] = 'ng/L'
df['state'] = df_repeated['State']
df['data_source'] = 'PPL'
df['source_type'] = df_repeated['Sample matrix']
df['is_detected'] = df_repeated['is_detected']
df['pfas_total'] = df_repeated['Total PFAS from one sample (ppt)']

In [21]:
df.to_csv('ppl.csv')

In [22]:
ppl_df['State'].unique()

array(['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California',
       'Colorado', 'Connecticut', 'Delaware', 'District of Columbia',
       'Florida', 'Georgia', 'Guam', 'Hawaii', 'Idaho', 'Illinois',
       'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine',
       'Marshall Islands', 'Maryland', 'Massachusetts', 'Michigan',
       'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska',
       'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York',
       'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon',
       'Pennsylvania', nan, 'Puerto Rico', 'Rhode Island',
       'Saipan, Commonwealth of the Northern Mariana Islands',
       'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah',
       'Vermont', 'Virgin Islands', 'Virginia', 'w', 'Wake Island',
       'Washington', 'West Virginia', 'Wisconsin', 'Wyoming'],
      dtype=object)

In [23]:
df[df['source_type'] == 'Drinking Water']

,sample_id,sampling_location,data_source,latitude,longitude,sampling_date,pws_id,water_system_name,population,well_type,...,city,county,MRL,DL,analytical_methods,is_detected,analyte,concentration,pfas_total,note
18,NaN,77 Same Old Road,PPL,NaN,NaN,2019,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,True,PFOA,53.0,NaN,NaN
19,NaN,77 Same Old Road,PPL,NaN,NaN,2019,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,True,PFOS,11500.0,NaN,NaN
20,NaN,77 Same Old Road,PPL,NaN,NaN,2019,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,PFOA+PFOS,NaN,NaN,NaN
24,NaN,Alcantra Armory Complex,PPL,NaN,NaN,2018,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,PFOA,NaN,1.0,NaN
25,NaN,Alcantra Armory Complex,PPL,NaN,NaN,2018,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,PFOS,NaN,1.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5959,NaN,Hayward TNG Site,PPL,NaN,NaN,2018,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,PFOS,NaN,1.0,NaN
5960,NaN,Hayward TNG Site,PPL,NaN,NaN,2018,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,PFOA+PFOS,NaN,1.0,NaN
6027,NaN,Camp Guernsey,PPL,NaN,NaN,2018,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,True,PFOA,1.0,7.0,NaN
6028,NaN,Camp Guernsey,PPL,NaN,NaN,2018,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,PFOS,NaN,7.0,NaN
6029,NaN,Camp Guernsey,PPL,NaN,NaN,2018,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,PFOA+PFOS,NaN,7.0,NaN