In [2]:
import pandas as pd
import os
import numpy as np
import re

In [3]:
in_df1 = pd.read_excel('pfas_results_1.xlsx', sheet_name = 'Detailed Results')

In [4]:
in_df1.columns

Index(['County', 'System_Proper', 'PWSID', 'LaboratorySampleIdentifier',
       'LocationIdentifier', 'Sample Type', 'SampleCollectionEndDate',
       'PreparationEndDate', 'AnalysisEndDate', 'SampleType', 'ResultUnits',
       '11Cl-PF3OUdS', '9Cl-PF3ONS', 'ADONA', 'HFPO-DA', 'N-EtFOSAA',
       'N-MeFOSAA', 'PFBS', 'PFDA', 'PFDoA', 'PFHpA', 'PFHxA', 'PFHxS', 'PFNA',
       'PFOA', 'PFOS', 'PFTA', 'PFTrDA', 'PFUnA'],
      dtype='object')

In [5]:
in_df1 = in_df1.drop(columns = ['PreparationEndDate', 'AnalysisEndDate', 'SampleType'])

In [6]:
in_df1

,County,System_Proper,PWSID,LaboratorySampleIdentifier,LocationIdentifier,Sample Type,SampleCollectionEndDate,ResultUnits,11Cl-PF3OUdS,9Cl-PF3ONS,...,PFDoA,PFHpA,PFHxA,PFHxS,PFNA,PFOA,PFOS,PFTA,PFTrDA,PFUnA
0,ADAMS,Berne Water Department,IN5201001,E21005959-001,Field Blank,Field Blank,2021-03-01,ng/L,<2,<2,...,<2,<2,<2,<2,<2,<2,<2,<2,<2,<2
1,ADAMS,Berne Water Department,IN5201001,E21005959-002,EP001,Finished Water,2021-03-01,ng/L,<2,<2,...,<2,<2,<2,<2,<2,<2,<2,<2,<2,<2
2,ADAMS,Berne Water Department,IN5201001,E21005959-003,WL001,Untreated,2021-03-01,ng/L,<2,<2,...,<2,<2,<2,<2,<2,<2,<2,<2,<2,<2
3,ADAMS,Berne Water Department,IN5201001,E21005959-004,WL002,Untreated,2021-03-01,ng/L,<2,<2,...,<2,<2,<2,<2,<2,<2,<2,<2,<2,<2
4,ADAMS,Decatur Water Department,IN5201002,E21005960-001,Field Blank,Field Blank,2021-03-02,ng/L,<2,<2,...,<2,<2,<2,<2,<2,<2,<2,<2,<2,<2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335,WASHINGTON,Salem Water Works,IN5288005,E21024702-003,IN001-6775,Untreated,2021-09-27,ng/L,<2,<2,...,<2,<2,<2,<2,<2,<2,<2,<2,<2,<2
336,WHITLEY,Columbia City Water Department,IN5292004,E21023774-001,Field Blank,Field Blank,2021-09-14,ng/L,<2,<2,...,<2,<2,<2,<2,<2,<2,<2,<2,<2,<2
337,WHITLEY,Columbia City Water Department,IN5292004,E21023774-002,EP001,Finished Water,2021-09-14,ng/L,<2,<2,...,<2,<2,<2,<2,<2,<2,<2,<2,<2,<2
338,WHITLEY,Columbia City Water Department,IN5292004,E21023774-004,WL003,Untreated,2021-09-14,ng/L,<2,<2,...,<2,<2,<2,<2,<2,<2,<2,<2,<2,<2
339,WHITLEY,Columbia City Water Department,IN5292004,E21023774-005,WL008,Untreated,2021-09-14,ng/L,<2,<2,...,<2,<2,<2,<2,<2,<2,<2,<2,<2,<2

In [7]:
analyte_list = list(in_df1.columns[8:])

In [8]:
columns_to_repeat = list(in_df1.columns[0:8])
df_repeated = pd.DataFrame(columns=columns_to_repeat)

for i in range(len(in_df1)):
    row_repeated = pd.concat([in_df1.iloc[[i]][columns_to_repeat]] * len(analyte_list), ignore_index=True)
    df_repeated = pd.concat([df_repeated, row_repeated], ignore_index=True)
df_repeated

/var/folders/m8/kh2nk5652k94h_n7lqjvr8n00000gn/T/ipykernel_64876/545209289.py:6: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_repeated = pd.concat([df_repeated, row_repeated], ignore_index=True)

,County,System_Proper,PWSID,LaboratorySampleIdentifier,LocationIdentifier,Sample Type,SampleCollectionEndDate,ResultUnits
0,ADAMS,Berne Water Department,IN5201001,E21005959-001,Field Blank,Field Blank,2021-03-01,ng/L
1,ADAMS,Berne Water Department,IN5201001,E21005959-001,Field Blank,Field Blank,2021-03-01,ng/L
2,ADAMS,Berne Water Department,IN5201001,E21005959-001,Field Blank,Field Blank,2021-03-01,ng/L
3,ADAMS,Berne Water Department,IN5201001,E21005959-001,Field Blank,Field Blank,2021-03-01,ng/L
4,ADAMS,Berne Water Department,IN5201001,E21005959-001,Field Blank,Field Blank,2021-03-01,ng/L
...,...,...,...,...,...,...,...,...
6115,WHITLEY,Columbia City Water Department,IN5292004,E21023774-005,WL008,Untreated,2021-09-14,ng/L
6116,WHITLEY,Columbia City Water Department,IN5292004,E21023774-005,WL008,Untreated,2021-09-14,ng/L
6117,WHITLEY,Columbia City Water Department,IN5292004,E21023774-005,WL008,Untreated,2021-09-14,ng/L
6118,WHITLEY,Columbia City Water Department,IN5292004,E21023774-005,WL008,Untreated,2021-09-14,ng/L
6119,WHITLEY,Columbia City Water Department,IN5292004,E21023774-005,WL008,Untreated,2021-09-14,ng/L

In [9]:
df_repeated['analyte'] = analyte_list * len(in_df1)
df_repeated['concentration'] = in_df1[analyte_list].values.flatten().tolist()

In [10]:
df_repeated

,County,System_Proper,PWSID,LaboratorySampleIdentifier,LocationIdentifier,Sample Type,SampleCollectionEndDate,ResultUnits,analyte,concentration
0,ADAMS,Berne Water Department,IN5201001,E21005959-001,Field Blank,Field Blank,2021-03-01,ng/L,11Cl-PF3OUdS,<2
1,ADAMS,Berne Water Department,IN5201001,E21005959-001,Field Blank,Field Blank,2021-03-01,ng/L,9Cl-PF3ONS,<2
2,ADAMS,Berne Water Department,IN5201001,E21005959-001,Field Blank,Field Blank,2021-03-01,ng/L,ADONA,<2
3,ADAMS,Berne Water Department,IN5201001,E21005959-001,Field Blank,Field Blank,2021-03-01,ng/L,HFPO-DA,<10
4,ADAMS,Berne Water Department,IN5201001,E21005959-001,Field Blank,Field Blank,2021-03-01,ng/L,N-EtFOSAA,<2
...,...,...,...,...,...,...,...,...,...,...
6115,WHITLEY,Columbia City Water Department,IN5292004,E21023774-005,WL008,Untreated,2021-09-14,ng/L,PFOA,<2
6116,WHITLEY,Columbia City Water Department,IN5292004,E21023774-005,WL008,Untreated,2021-09-14,ng/L,PFOS,<2
6117,WHITLEY,Columbia City Water Department,IN5292004,E21023774-005,WL008,Untreated,2021-09-14,ng/L,PFTA,<2
6118,WHITLEY,Columbia City Water Department,IN5292004,E21023774-005,WL008,Untreated,2021-09-14,ng/L,PFTrDA,<2
6119,WHITLEY,Columbia City Water Department,IN5292004,E21023774-005,WL008,Untreated,2021-09-14,ng/L,PFUnA,<2

In [11]:
def process_result(row):
    result_str = str(row['concentration'])
    if result_str.startswith('<'):
        detection_limit = float(result_str[1:])
        return pd.Series([0, detection_limit])
    elif result_str.replace('.', '', 1).isdigit():
        return pd.Series([float(result_str), np.nan])
    else:
        return pd.Series([np.nan, np.nan])

In [12]:
df_repeated[['concentration', 'detection_limit']] = df_repeated.apply(process_result, axis=1)

In [13]:
df_repeated

,County,System_Proper,PWSID,LaboratorySampleIdentifier,LocationIdentifier,Sample Type,SampleCollectionEndDate,ResultUnits,analyte,concentration,detection_limit
0,ADAMS,Berne Water Department,IN5201001,E21005959-001,Field Blank,Field Blank,2021-03-01,ng/L,11Cl-PF3OUdS,0.0,2.0
1,ADAMS,Berne Water Department,IN5201001,E21005959-001,Field Blank,Field Blank,2021-03-01,ng/L,9Cl-PF3ONS,0.0,2.0
2,ADAMS,Berne Water Department,IN5201001,E21005959-001,Field Blank,Field Blank,2021-03-01,ng/L,ADONA,0.0,2.0
3,ADAMS,Berne Water Department,IN5201001,E21005959-001,Field Blank,Field Blank,2021-03-01,ng/L,HFPO-DA,0.0,10.0
4,ADAMS,Berne Water Department,IN5201001,E21005959-001,Field Blank,Field Blank,2021-03-01,ng/L,N-EtFOSAA,0.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...
6115,WHITLEY,Columbia City Water Department,IN5292004,E21023774-005,WL008,Untreated,2021-09-14,ng/L,PFOA,0.0,2.0
6116,WHITLEY,Columbia City Water Department,IN5292004,E21023774-005,WL008,Untreated,2021-09-14,ng/L,PFOS,0.0,2.0
6117,WHITLEY,Columbia City Water Department,IN5292004,E21023774-005,WL008,Untreated,2021-09-14,ng/L,PFTA,0.0,2.0
6118,WHITLEY,Columbia City Water Department,IN5292004,E21023774-005,WL008,Untreated,2021-09-14,ng/L,PFTrDA,0.0,2.0
6119,WHITLEY,Columbia City Water Department,IN5292004,E21023774-005,WL008,Untreated,2021-09-14,ng/L,PFUnA,0.0,2.0

In [14]:
dl_list = [2.0, 2.0, 2.0, 10.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0 ]

In [15]:
dl_dict = dict(zip(analyte_list, dl_list))

In [16]:
df_repeated.loc[df_repeated['concentration'] != 0, 'detection_limit'] = df_repeated[df_repeated['concentration'] != 0]['analyte'].map(dl_dict)

In [17]:
df_repeated

,County,System_Proper,PWSID,LaboratorySampleIdentifier,LocationIdentifier,Sample Type,SampleCollectionEndDate,ResultUnits,analyte,concentration,detection_limit
0,ADAMS,Berne Water Department,IN5201001,E21005959-001,Field Blank,Field Blank,2021-03-01,ng/L,11Cl-PF3OUdS,0.0,2.0
1,ADAMS,Berne Water Department,IN5201001,E21005959-001,Field Blank,Field Blank,2021-03-01,ng/L,9Cl-PF3ONS,0.0,2.0
2,ADAMS,Berne Water Department,IN5201001,E21005959-001,Field Blank,Field Blank,2021-03-01,ng/L,ADONA,0.0,2.0
3,ADAMS,Berne Water Department,IN5201001,E21005959-001,Field Blank,Field Blank,2021-03-01,ng/L,HFPO-DA,0.0,10.0
4,ADAMS,Berne Water Department,IN5201001,E21005959-001,Field Blank,Field Blank,2021-03-01,ng/L,N-EtFOSAA,0.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...
6115,WHITLEY,Columbia City Water Department,IN5292004,E21023774-005,WL008,Untreated,2021-09-14,ng/L,PFOA,0.0,2.0
6116,WHITLEY,Columbia City Water Department,IN5292004,E21023774-005,WL008,Untreated,2021-09-14,ng/L,PFOS,0.0,2.0
6117,WHITLEY,Columbia City Water Department,IN5292004,E21023774-005,WL008,Untreated,2021-09-14,ng/L,PFTA,0.0,2.0
6118,WHITLEY,Columbia City Water Department,IN5292004,E21023774-005,WL008,Untreated,2021-09-14,ng/L,PFTrDA,0.0,2.0
6119,WHITLEY,Columbia City Water Department,IN5292004,E21023774-005,WL008,Untreated,2021-09-14,ng/L,PFUnA,0.0,2.0

In [18]:
df_repeated.dtypes

County                                object
System_Proper                         object
PWSID                                 object
LaboratorySampleIdentifier            object
LocationIdentifier                    object
Sample Type                           object
SampleCollectionEndDate       datetime64[ns]
ResultUnits                           object
analyte                               object
concentration                        float64
detection_limit                      float64
dtype: object

In [19]:
columns = {
    'sample_id': str,
    'sampling_location': str,
    'data_source': str,
    'latitude': float,
    'longitude': float,
    'sampling_date': 'datetime64[ns]',
    'pws_id': str,
    'water_system_name': str,
    'population': int,
    'well_type': str,
    'well_depth': float,
    'units': str,
    'source_type': str,
    'state': str,
    'city': str,
    'county': str,
    'MRL': float,
    'DL': float,
    'analytical_methods': str,
    'is_detected': bool,
    'analyte': str,
    'concentration': float,
    'pfas_total': float,
    'note': str   
}

In [20]:
df1 = pd.DataFrame({col: pd.Series(dtype=dt) for col, dt in columns.items()})
df1['sample_id'] = df_repeated['LaboratorySampleIdentifier']
df1['data_source'] = 'Indiana Department of Environmental Management'
df1['sampling_date'] = df_repeated['SampleCollectionEndDate']
df1['pws_id'] =  df_repeated['PWSID']
df1['water_system_name'] = df_repeated['System_Proper']
df1['units'] = df_repeated['ResultUnits']
df1['county'] = df_repeated['County']
df1['source_type'] = 'drinking water'
df1['state'] = 'Indiana'
df1['DL'] = df_repeated['detection_limit']
df1['analyte'] = df_repeated['analyte'].str.upper()
df1['concentration'] = df_repeated['concentration']
df1['note'] = df_repeated['Sample Type']

In [21]:
df1['is_detected'] = df1['concentration'] != 0

In [22]:
df1

,sample_id,sampling_location,data_source,latitude,longitude,sampling_date,pws_id,water_system_name,population,well_type,...,city,county,MRL,DL,analytical_methods,is_detected,analyte,concentration,pfas_total,note
0,E21005959-001,NaN,Indiana Department of Environmental Management,NaN,NaN,2021-03-01,IN5201001,Berne Water Department,NaN,NaN,...,NaN,ADAMS,NaN,2.0,NaN,False,11CL-PF3OUDS,0.0,NaN,Field Blank
1,E21005959-001,NaN,Indiana Department of Environmental Management,NaN,NaN,2021-03-01,IN5201001,Berne Water Department,NaN,NaN,...,NaN,ADAMS,NaN,2.0,NaN,False,9CL-PF3ONS,0.0,NaN,Field Blank
2,E21005959-001,NaN,Indiana Department of Environmental Management,NaN,NaN,2021-03-01,IN5201001,Berne Water Department,NaN,NaN,...,NaN,ADAMS,NaN,2.0,NaN,False,ADONA,0.0,NaN,Field Blank
3,E21005959-001,NaN,Indiana Department of Environmental Management,NaN,NaN,2021-03-01,IN5201001,Berne Water Department,NaN,NaN,...,NaN,ADAMS,NaN,10.0,NaN,False,HFPO-DA,0.0,NaN,Field Blank
4,E21005959-001,NaN,Indiana Department of Environmental Management,NaN,NaN,2021-03-01,IN5201001,Berne Water Department,NaN,NaN,...,NaN,ADAMS,NaN,2.0,NaN,False,N-ETFOSAA,0.0,NaN,Field Blank
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6115,E21023774-005,NaN,Indiana Department of Environmental Management,NaN,NaN,2021-09-14,IN5292004,Columbia City Water Department,NaN,NaN,...,NaN,WHITLEY,NaN,2.0,NaN,False,PFOA,0.0,NaN,Untreated
6116,E21023774-005,NaN,Indiana Department of Environmental Management,NaN,NaN,2021-09-14,IN5292004,Columbia City Water Department,NaN,NaN,...,NaN,WHITLEY,NaN,2.0,NaN,False,PFOS,0.0,NaN,Untreated
6117,E21023774-005,NaN,Indiana Department of Environmental Management,NaN,NaN,2021-09-14,IN5292004,Columbia City Water Department,NaN,NaN,...,NaN,WHITLEY,NaN,2.0,NaN,False,PFTA,0.0,NaN,Untreated
6118,E21023774-005,NaN,Indiana Department of Environmental Management,NaN,NaN,2021-09-14,IN5292004,Columbia City Water Department,NaN,NaN,...,NaN,WHITLEY,NaN,2.0,NaN,False,PFTRDA,0.0,NaN,Untreated
6119,E21023774-005,NaN,Indiana Department of Environmental Management,NaN,NaN,2021-09-14,IN5292004,Columbia City Water Department,NaN,NaN,...,NaN,WHITLEY,NaN,2.0,NaN,False,PFUNA,0.0,NaN,Untreated

In [23]:
in_df2 = pd.read_excel('pfas_results_1_update.xlsx', sheet_name = 'Phase 1 Resample Results Post')

In [24]:
in_df2

,County,System_Proper,PWSID,Lab ID,Sample ID,LocationID,Sample Type,SampleDate,Acronym,Parameter,Results,Units
0,BLACKFORD,Hartford City Water Works,IN5205002,35735354001,R5205002-01,Field Blank,Field Blank,7/28/2022,11Cl-PF3OUdS,11Cl-PF3OUdS,ND,ng/L
1,BLACKFORD,Hartford City Water Works,IN5205002,35735354001,R5205002-01,Field Blank,Field Blank,7/28/2022,9Cl-PF3ONS,9Cl-PF3ONS,ND,ng/L
2,BLACKFORD,Hartford City Water Works,IN5205002,35735354001,R5205002-01,Field Blank,Field Blank,7/28/2022,ADONA,ADONA,ND,ng/L
3,BLACKFORD,Hartford City Water Works,IN5205002,35735354001,R5205002-01,Field Blank,Field Blank,7/28/2022,GenX,HFPO-DA,ND,ng/L
4,BLACKFORD,Hartford City Water Works,IN5205002,35735354001,R5205002-01,Field Blank,Field Blank,7/28/2022,NEtFOSAA,NEtFOSAA,ND,ng/L
...,...,...,...,...,...,...,...,...,...,...,...,...
2551,WARRICK,Tennyson Water Utility,IN5287007,35735197003,R5287007-04,EP003,Finished Water,7/26/2022,PFOA,Perfluorooctanoic acid,ND,ng/L
2552,WARRICK,Tennyson Water Utility,IN5287007,35735197003,R5287007-04,EP003,Finished Water,7/26/2022,PFOS,Perfluorooctanesulfonic acid,ND,ng/L
2553,WARRICK,Tennyson Water Utility,IN5287007,35735197003,R5287007-04,EP003,Finished Water,7/26/2022,PFTeDA,Perfluorotetradecanoic acid,ND,ng/L
2554,WARRICK,Tennyson Water Utility,IN5287007,35735197003,R5287007-04,EP003,Finished Water,7/26/2022,PFTrDA,Perfluorotridecanoic acid,ND,ng/L
2555,WARRICK,Tennyson Water Utility,IN5287007,35735197003,R5287007-04,EP003,Finished Water,7/26/2022,PFUdA,Perfluoroundecanoic acid,ND,ng/L

In [25]:
def process_result(value):
    if value == 'ND':
        return float(0)
    else:
        return float(value)

In [26]:
in_df2['Results'] = in_df2['Results'].apply(process_result)

In [27]:
in_df2['is_detected'] = in_df2['Results'] != 0

In [28]:
df2 = pd.DataFrame({col: pd.Series(dtype=dt) for col, dt in columns.items()})
df2['sample_id'] = in_df2['Sample ID']
df2['data_source'] = 'Indiana Department of Environmental Management'
df2['sampling_date'] = pd.to_datetime(in_df2['SampleDate'])
df2['pws_id'] =  in_df2['PWSID']
df2['water_system_name'] = in_df2['System_Proper']
df2['units'] = in_df2['Units']
df2['county'] = in_df2['County']
df2['analyte'] = in_df2['Acronym'].str.upper()
df2['concentration'] = in_df2['Results']
df2['note'] = in_df2['Sample Type']
df2['is_detected'] = in_df2['is_detected']
df2['source_type'] = 'drinking water'
df2['state'] = 'Indiana'

In [29]:
df2

,sample_id,sampling_location,data_source,latitude,longitude,sampling_date,pws_id,water_system_name,population,well_type,...,city,county,MRL,DL,analytical_methods,is_detected,analyte,concentration,pfas_total,note
0,R5205002-01,NaN,Indiana Department of Environmental Management,NaN,NaN,2022-07-28,IN5205002,Hartford City Water Works,NaN,NaN,...,NaN,BLACKFORD,NaN,NaN,NaN,False,11CL-PF3OUDS,0.0,NaN,Field Blank
1,R5205002-01,NaN,Indiana Department of Environmental Management,NaN,NaN,2022-07-28,IN5205002,Hartford City Water Works,NaN,NaN,...,NaN,BLACKFORD,NaN,NaN,NaN,False,9CL-PF3ONS,0.0,NaN,Field Blank
2,R5205002-01,NaN,Indiana Department of Environmental Management,NaN,NaN,2022-07-28,IN5205002,Hartford City Water Works,NaN,NaN,...,NaN,BLACKFORD,NaN,NaN,NaN,False,ADONA,0.0,NaN,Field Blank
3,R5205002-01,NaN,Indiana Department of Environmental Management,NaN,NaN,2022-07-28,IN5205002,Hartford City Water Works,NaN,NaN,...,NaN,BLACKFORD,NaN,NaN,NaN,False,GENX,0.0,NaN,Field Blank
4,R5205002-01,NaN,Indiana Department of Environmental Management,NaN,NaN,2022-07-28,IN5205002,Hartford City Water Works,NaN,NaN,...,NaN,BLACKFORD,NaN,NaN,NaN,False,NETFOSAA,0.0,NaN,Field Blank
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2551,R5287007-04,NaN,Indiana Department of Environmental Management,NaN,NaN,2022-07-26,IN5287007,Tennyson Water Utility,NaN,NaN,...,NaN,WARRICK,NaN,NaN,NaN,False,PFOA,0.0,NaN,Finished Water
2552,R5287007-04,NaN,Indiana Department of Environmental Management,NaN,NaN,2022-07-26,IN5287007,Tennyson Water Utility,NaN,NaN,...,NaN,WARRICK,NaN,NaN,NaN,False,PFOS,0.0,NaN,Finished Water
2553,R5287007-04,NaN,Indiana Department of Environmental Management,NaN,NaN,2022-07-26,IN5287007,Tennyson Water Utility,NaN,NaN,...,NaN,WARRICK,NaN,NaN,NaN,False,PFTEDA,0.0,NaN,Finished Water
2554,R5287007-04,NaN,Indiana Department of Environmental Management,NaN,NaN,2022-07-26,IN5287007,Tennyson Water Utility,NaN,NaN,...,NaN,WARRICK,NaN,NaN,NaN,False,PFTRDA,0.0,NaN,Finished Water
2555,R5287007-04,NaN,Indiana Department of Environmental Management,NaN,NaN,2022-07-26,IN5287007,Tennyson Water Utility,NaN,NaN,...,NaN,WARRICK,NaN,NaN,NaN,False,PFUDA,0.0,NaN,Finished Water

In [30]:
in_df3 = pd.read_excel('pfas_results_3_update.xlsx', sheet_name = 'Phase 3 resample post')

In [31]:
in_df3

,County Name,System name,PWSID,Lab ID,Sample ID,Facility ID,SP Description,Sample Type,Collected Date,Acronym,Parameter,Results,Units
0,BARTHOLOMEW,COLUMBUS MUNICIPAL UTILITY,IN5203002,35824285002,5203002-02 Field Blank,Field Blank,NaN,NaN,08/30/2023 08:25,PFOS,Perfluorooctanesulfonic acid,ND,ng/L
1,BARTHOLOMEW,COLUMBUS MUNICIPAL UTILITY,IN5203002,35824285002,5203002-02 Field Blank,Field Blank,NaN,NaN,08/30/2023 08:25,PFOA,Perfluorooctanoic acid,ND,ng/L
2,BARTHOLOMEW,COLUMBUS MUNICIPAL UTILITY,IN5203002,35824285002,5203002-02 Field Blank,Field Blank,NaN,NaN,08/30/2023 08:25,PFHxS,Perfluorohexanesulfonic acid,ND,ng/L
3,BARTHOLOMEW,COLUMBUS MUNICIPAL UTILITY,IN5203002,35824285002,5203002-02 Field Blank,Field Blank,NaN,NaN,08/30/2023 08:25,PFHpA,Perfluoroheptanoic acid,ND,ng/L
4,BARTHOLOMEW,COLUMBUS MUNICIPAL UTILITY,IN5203002,35824285002,5203002-02 Field Blank,Field Blank,NaN,NaN,08/30/2023 08:25,PFNA,Perfluorononanoic acid,ND,ng/L
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3973,ST. JOSEPH,SOUTH BEND WATER WORKS,IN5271014,TP #8 - PINHOOK,NaN,TP008,PINHOOK,Finished Water,02/14/2024 09:50,PFOA,Perfluorooctanoic acid,ND,ng/L
3974,ST. JOSEPH,SOUTH BEND WATER WORKS,IN5271014,TP #8 - PINHOOK,NaN,TP008,PINHOOK,Finished Water,02/14/2024 09:50,PFOS,Perfluorooctanesulfonic acid,ND,ng/L
3975,ST. JOSEPH,SOUTH BEND WATER WORKS,IN5271014,TP #8 - PINHOOK,NaN,TP008,PINHOOK,Finished Water,02/14/2024 09:50,PFTeDA,Perfluorotetradecanoic acid,ND,ng/L
3976,ST. JOSEPH,SOUTH BEND WATER WORKS,IN5271014,TP #8 - PINHOOK,NaN,TP008,PINHOOK,Finished Water,02/14/2024 09:50,PFTrDA,Perfluorotridecanoic acid,ND,ng/L
3977,ST. JOSEPH,SOUTH BEND WATER WORKS,IN5271014,TP #8 - PINHOOK,NaN,TP008,PINHOOK,Finished Water,02/14/2024 09:50,PFUnA,Perfluoroundecanoic acid,ND,ng/L

In [32]:
in_df3['Results'] = in_df3['Results'].apply(process_result)
in_df3['is_detected'] = in_df3['Results'] != 0

In [33]:
in_df3

,County Name,System name,PWSID,Lab ID,Sample ID,Facility ID,SP Description,Sample Type,Collected Date,Acronym,Parameter,Results,Units,is_detected
0,BARTHOLOMEW,COLUMBUS MUNICIPAL UTILITY,IN5203002,35824285002,5203002-02 Field Blank,Field Blank,NaN,NaN,08/30/2023 08:25,PFOS,Perfluorooctanesulfonic acid,0.0,ng/L,False
1,BARTHOLOMEW,COLUMBUS MUNICIPAL UTILITY,IN5203002,35824285002,5203002-02 Field Blank,Field Blank,NaN,NaN,08/30/2023 08:25,PFOA,Perfluorooctanoic acid,0.0,ng/L,False
2,BARTHOLOMEW,COLUMBUS MUNICIPAL UTILITY,IN5203002,35824285002,5203002-02 Field Blank,Field Blank,NaN,NaN,08/30/2023 08:25,PFHxS,Perfluorohexanesulfonic acid,0.0,ng/L,False
3,BARTHOLOMEW,COLUMBUS MUNICIPAL UTILITY,IN5203002,35824285002,5203002-02 Field Blank,Field Blank,NaN,NaN,08/30/2023 08:25,PFHpA,Perfluoroheptanoic acid,0.0,ng/L,False
4,BARTHOLOMEW,COLUMBUS MUNICIPAL UTILITY,IN5203002,35824285002,5203002-02 Field Blank,Field Blank,NaN,NaN,08/30/2023 08:25,PFNA,Perfluorononanoic acid,0.0,ng/L,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3973,ST. JOSEPH,SOUTH BEND WATER WORKS,IN5271014,TP #8 - PINHOOK,NaN,TP008,PINHOOK,Finished Water,02/14/2024 09:50,PFOA,Perfluorooctanoic acid,0.0,ng/L,False
3974,ST. JOSEPH,SOUTH BEND WATER WORKS,IN5271014,TP #8 - PINHOOK,NaN,TP008,PINHOOK,Finished Water,02/14/2024 09:50,PFOS,Perfluorooctanesulfonic acid,0.0,ng/L,False
3975,ST. JOSEPH,SOUTH BEND WATER WORKS,IN5271014,TP #8 - PINHOOK,NaN,TP008,PINHOOK,Finished Water,02/14/2024 09:50,PFTeDA,Perfluorotetradecanoic acid,0.0,ng/L,False
3976,ST. JOSEPH,SOUTH BEND WATER WORKS,IN5271014,TP #8 - PINHOOK,NaN,TP008,PINHOOK,Finished Water,02/14/2024 09:50,PFTrDA,Perfluorotridecanoic acid,0.0,ng/L,False
3977,ST. JOSEPH,SOUTH BEND WATER WORKS,IN5271014,TP #8 - PINHOOK,NaN,TP008,PINHOOK,Finished Water,02/14/2024 09:50,PFUnA,Perfluoroundecanoic acid,0.0,ng/L,False

In [34]:
df3 = pd.DataFrame({col: pd.Series(dtype=dt) for col, dt in columns.items()})
df3['sample_id'] = in_df3['Sample ID']
df3['data_source'] = 'Indiana Department of Environmental Management'
df3['sampling_date'] = pd.to_datetime(in_df3['Collected Date'])
df3['pws_id'] =  in_df3['PWSID']
df3['water_system_name'] = in_df3['System name']
df3['units'] = in_df3['Units']
df3['county'] = in_df3['County Name']
df3['analyte'] = in_df3['Acronym'].str.upper()
df3['concentration'] = in_df3['Results']
df3['note'] = in_df3['Sample Type']
df3['is_detected'] = in_df3['is_detected']
df3['source_type'] = 'drinking water'
df3['state'] = 'Indiana'

In [35]:
df3

,sample_id,sampling_location,data_source,latitude,longitude,sampling_date,pws_id,water_system_name,population,well_type,...,city,county,MRL,DL,analytical_methods,is_detected,analyte,concentration,pfas_total,note
0,5203002-02 Field Blank,NaN,Indiana Department of Environmental Management,NaN,NaN,2023-08-30 08:25:00,IN5203002,COLUMBUS MUNICIPAL UTILITY,NaN,NaN,...,NaN,BARTHOLOMEW,NaN,NaN,NaN,False,PFOS,0.0,NaN,NaN
1,5203002-02 Field Blank,NaN,Indiana Department of Environmental Management,NaN,NaN,2023-08-30 08:25:00,IN5203002,COLUMBUS MUNICIPAL UTILITY,NaN,NaN,...,NaN,BARTHOLOMEW,NaN,NaN,NaN,False,PFOA,0.0,NaN,NaN
2,5203002-02 Field Blank,NaN,Indiana Department of Environmental Management,NaN,NaN,2023-08-30 08:25:00,IN5203002,COLUMBUS MUNICIPAL UTILITY,NaN,NaN,...,NaN,BARTHOLOMEW,NaN,NaN,NaN,False,PFHXS,0.0,NaN,NaN
3,5203002-02 Field Blank,NaN,Indiana Department of Environmental Management,NaN,NaN,2023-08-30 08:25:00,IN5203002,COLUMBUS MUNICIPAL UTILITY,NaN,NaN,...,NaN,BARTHOLOMEW,NaN,NaN,NaN,False,PFHPA,0.0,NaN,NaN
4,5203002-02 Field Blank,NaN,Indiana Department of Environmental Management,NaN,NaN,2023-08-30 08:25:00,IN5203002,COLUMBUS MUNICIPAL UTILITY,NaN,NaN,...,NaN,BARTHOLOMEW,NaN,NaN,NaN,False,PFNA,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3973,NaN,NaN,Indiana Department of Environmental Management,NaN,NaN,2024-02-14 09:50:00,IN5271014,SOUTH BEND WATER WORKS,NaN,NaN,...,NaN,ST. JOSEPH,NaN,NaN,NaN,False,PFOA,0.0,NaN,Finished Water
3974,NaN,NaN,Indiana Department of Environmental Management,NaN,NaN,2024-02-14 09:50:00,IN5271014,SOUTH BEND WATER WORKS,NaN,NaN,...,NaN,ST. JOSEPH,NaN,NaN,NaN,False,PFOS,0.0,NaN,Finished Water
3975,NaN,NaN,Indiana Department of Environmental Management,NaN,NaN,2024-02-14 09:50:00,IN5271014,SOUTH BEND WATER WORKS,NaN,NaN,...,NaN,ST. JOSEPH,NaN,NaN,NaN,False,PFTEDA,0.0,NaN,Finished Water
3976,NaN,NaN,Indiana Department of Environmental Management,NaN,NaN,2024-02-14 09:50:00,IN5271014,SOUTH BEND WATER WORKS,NaN,NaN,...,NaN,ST. JOSEPH,NaN,NaN,NaN,False,PFTRDA,0.0,NaN,Finished Water
3977,NaN,NaN,Indiana Department of Environmental Management,NaN,NaN,2024-02-14 09:50:00,IN5271014,SOUTH BEND WATER WORKS,NaN,NaN,...,NaN,ST. JOSEPH,NaN,NaN,NaN,False,PFUNA,0.0,NaN,Finished Water

In [36]:
in_df4 = pd.read_excel('pfas_results_3.xlsx', sheet_name = 'Phase 3 Results Post')

In [37]:
in_df4

,County Name,System name,PWSID,Lab ID,Sample ID,Facility ID,SP Description,Sample Type,Collected Date,Acronym,Parameter,Results,Units
0,BARTHOLOMEW,EASTERN BARTHOLOMEW WATER,IN5203004,3.579917e+10,5203004-02 EP003,TP003,TREATMENTT PLANT #3,Finished Water,2023-05-10 10:06:00,11Cl-PF3OUdS,11Cl-PF3OUdS,ND,ng/L
1,BARTHOLOMEW,EASTERN BARTHOLOMEW WATER,IN5203004,3.579917e+10,5203004-02 EP003,TP003,TREATMENTT PLANT #3,Finished Water,2023-05-10 10:06:00,9Cl-PF3ONS,9Cl-PF3ONS,ND,ng/L
2,BARTHOLOMEW,EASTERN BARTHOLOMEW WATER,IN5203004,3.579917e+10,5203004-02 EP003,TP003,TREATMENTT PLANT #3,Finished Water,2023-05-10 10:06:00,ADONA,ADONA,ND,ng/L
3,BARTHOLOMEW,EASTERN BARTHOLOMEW WATER,IN5203004,3.579917e+10,5203004-02 EP003,TP003,TREATMENTT PLANT #3,Finished Water,2023-05-10 10:06:00,GenX,HFPO-DA,ND,ng/L
4,BARTHOLOMEW,EASTERN BARTHOLOMEW WATER,IN5203004,3.579917e+10,5203004-02 EP003,TP003,TREATMENTT PLANT #3,Finished Water,2023-05-10 10:06:00,NEtFOSAA,NEtFOSAA,ND,ng/L
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16099,LAKE,INDIANA AMERICAN WATER - LOWELL,IN5245029,3.581122e+10,5245029-03 GW013,WL003,WELL #3,Untreated Water,2023-07-05 08:25:00,NEtFOSAA,NEtFOSAA,ND,ng/L
16100,LAKE,INDIANA AMERICAN WATER - LOWELL,IN5245029,3.581122e+10,5245029-03 GW013,WL003,WELL #3,Untreated Water,2023-07-05 08:25:00,NMeFOSAA,NMeFOSAA,ND,ng/L
16101,LAKE,INDIANA AMERICAN WATER - LOWELL,IN5245029,3.581122e+10,5245029-03 GW013,WL003,WELL #3,Untreated Water,2023-07-05 08:25:00,11Cl-PF3OUdS,11Cl-PF3OUdS,ND,ng/L
16102,LAKE,INDIANA AMERICAN WATER - LOWELL,IN5245029,3.581122e+10,5245029-03 GW013,WL003,WELL #3,Untreated Water,2023-07-05 08:25:00,ADONA,ADONA,ND,ng/L
16103,LAKE,INDIANA AMERICAN WATER - LOWELL,IN5245029,3.581122e+10,5245029-03 GW013,WL003,WELL #3,Untreated Water,2023-07-05 08:25:00,9Cl-PF3ONS,9Cl-PF3ONS,ND,ng/L

In [38]:
in_df4['Results'].unique()

array(['ND', '2.5', '2.3', '14.2', '5.2', '9.5', '4', '3.4', '3.1', '2.7',
       '2.2', '4.6', '2.9', '9', '5.4', 2.8, 3.9, 5.2, 7, 7.9, '2.1',
       '2.6', '1.9', '2.4', '3.6', '2', '3.2', '6', '6.8', '5.6', '15.3',
       '14.5', '4.7', '13.5', '8', '24.9', '20.8', '6.9', '10', '5.5',
       '18.5', '14.4', '5.7', '3.8', '5.1', '3.9', '3.3', '4.8', '3.7',
       '40.9', '27.6', '6.3', '29.6', '45', '4.2', '6.7', '8.9', '3.5',
       '10.8', '11', '8.6', '15.6', '20.9', '12.1', '5', '12.3', '6.2',
       '1.8', '11.4', '11.3', '4.4', '7.3', '7.8', '7.7', '7.6', '7.4',
       '8.3', '8.4', '8.2', '7.1', '7.9', '14', '4.5', '5.3', '12', nan,
       '<2.0', '3', '2.8', '4.3', '6.5', 2.9, 3.1, 7.2,
       '17.6 (Preliminary)', '2.1 (Preliminary)', '2.6 (Preliminary)',
       '5.5 (Preliminary)', 'ND (Preliminary)', '4.1', '9.3', '50.5',
       '61.1', 1.9, 15.4, 2, 2.1, 2.2, 2.3, 2.5, 2.6, 2.7, 3.4, 3.8, 4.1,
       4.2, 5.3, 5.7, 'ND ', '35.8', '19.3', '6.4', '16.3', '10.5',
       '10.7', '14.3', '15', '11.1', '7.2', '18.9', '2.0', '3.0', '5.8',
       '4.0'], dtype=object)

In [39]:
def process_result2(value):
    if pd.isna(value):
        return np.nan  # Handle NaN values explicitly
    value_str = str(value)
    if 'ND' in value_str or '<' in value_str:
        return float(0)
    else:
        return float(value_str.split()[0])

In [40]:
in_df4['Results'] = in_df4['Results'].apply(process_result2)

In [41]:
in_df4['is_detected'] = in_df4['Results'] != 0

In [42]:
in_df4

,County Name,System name,PWSID,Lab ID,Sample ID,Facility ID,SP Description,Sample Type,Collected Date,Acronym,Parameter,Results,Units,is_detected
0,BARTHOLOMEW,EASTERN BARTHOLOMEW WATER,IN5203004,3.579917e+10,5203004-02 EP003,TP003,TREATMENTT PLANT #3,Finished Water,2023-05-10 10:06:00,11Cl-PF3OUdS,11Cl-PF3OUdS,0.0,ng/L,False
1,BARTHOLOMEW,EASTERN BARTHOLOMEW WATER,IN5203004,3.579917e+10,5203004-02 EP003,TP003,TREATMENTT PLANT #3,Finished Water,2023-05-10 10:06:00,9Cl-PF3ONS,9Cl-PF3ONS,0.0,ng/L,False
2,BARTHOLOMEW,EASTERN BARTHOLOMEW WATER,IN5203004,3.579917e+10,5203004-02 EP003,TP003,TREATMENTT PLANT #3,Finished Water,2023-05-10 10:06:00,ADONA,ADONA,0.0,ng/L,False
3,BARTHOLOMEW,EASTERN BARTHOLOMEW WATER,IN5203004,3.579917e+10,5203004-02 EP003,TP003,TREATMENTT PLANT #3,Finished Water,2023-05-10 10:06:00,GenX,HFPO-DA,0.0,ng/L,False
4,BARTHOLOMEW,EASTERN BARTHOLOMEW WATER,IN5203004,3.579917e+10,5203004-02 EP003,TP003,TREATMENTT PLANT #3,Finished Water,2023-05-10 10:06:00,NEtFOSAA,NEtFOSAA,0.0,ng/L,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16099,LAKE,INDIANA AMERICAN WATER - LOWELL,IN5245029,3.581122e+10,5245029-03 GW013,WL003,WELL #3,Untreated Water,2023-07-05 08:25:00,NEtFOSAA,NEtFOSAA,0.0,ng/L,False
16100,LAKE,INDIANA AMERICAN WATER - LOWELL,IN5245029,3.581122e+10,5245029-03 GW013,WL003,WELL #3,Untreated Water,2023-07-05 08:25:00,NMeFOSAA,NMeFOSAA,0.0,ng/L,False
16101,LAKE,INDIANA AMERICAN WATER - LOWELL,IN5245029,3.581122e+10,5245029-03 GW013,WL003,WELL #3,Untreated Water,2023-07-05 08:25:00,11Cl-PF3OUdS,11Cl-PF3OUdS,0.0,ng/L,False
16102,LAKE,INDIANA AMERICAN WATER - LOWELL,IN5245029,3.581122e+10,5245029-03 GW013,WL003,WELL #3,Untreated Water,2023-07-05 08:25:00,ADONA,ADONA,0.0,ng/L,False
16103,LAKE,INDIANA AMERICAN WATER - LOWELL,IN5245029,3.581122e+10,5245029-03 GW013,WL003,WELL #3,Untreated Water,2023-07-05 08:25:00,9Cl-PF3ONS,9Cl-PF3ONS,0.0,ng/L,False

In [43]:
df4 = pd.DataFrame({col: pd.Series(dtype=dt) for col, dt in columns.items()})
df4['sample_id'] = in_df4['Sample ID']
df4['data_source'] = 'Indiana Department of Environmental Management'
df4['sampling_date'] = pd.to_datetime(in_df4['Collected Date'])
df4['pws_id'] =  in_df4['PWSID']
df4['water_system_name'] = in_df4['System name']
df4['units'] = in_df4['Units']
df4['county'] = in_df4['County Name']
df4['analyte'] = in_df4['Acronym'].str.upper()
df4['concentration'] = in_df4['Results']
df4['note'] = in_df4['Sample Type']
df4['is_detected'] = in_df4['is_detected']
df4['source_type'] = 'drinking water'
df4['state'] = 'Indiana'

In [44]:
df4

,sample_id,sampling_location,data_source,latitude,longitude,sampling_date,pws_id,water_system_name,population,well_type,...,city,county,MRL,DL,analytical_methods,is_detected,analyte,concentration,pfas_total,note
0,5203004-02 EP003,NaN,Indiana Department of Environmental Management,NaN,NaN,2023-05-10 10:06:00,IN5203004,EASTERN BARTHOLOMEW WATER,NaN,NaN,...,NaN,BARTHOLOMEW,NaN,NaN,NaN,False,11CL-PF3OUDS,0.0,NaN,Finished Water
1,5203004-02 EP003,NaN,Indiana Department of Environmental Management,NaN,NaN,2023-05-10 10:06:00,IN5203004,EASTERN BARTHOLOMEW WATER,NaN,NaN,...,NaN,BARTHOLOMEW,NaN,NaN,NaN,False,9CL-PF3ONS,0.0,NaN,Finished Water
2,5203004-02 EP003,NaN,Indiana Department of Environmental Management,NaN,NaN,2023-05-10 10:06:00,IN5203004,EASTERN BARTHOLOMEW WATER,NaN,NaN,...,NaN,BARTHOLOMEW,NaN,NaN,NaN,False,ADONA,0.0,NaN,Finished Water
3,5203004-02 EP003,NaN,Indiana Department of Environmental Management,NaN,NaN,2023-05-10 10:06:00,IN5203004,EASTERN BARTHOLOMEW WATER,NaN,NaN,...,NaN,BARTHOLOMEW,NaN,NaN,NaN,False,GENX,0.0,NaN,Finished Water
4,5203004-02 EP003,NaN,Indiana Department of Environmental Management,NaN,NaN,2023-05-10 10:06:00,IN5203004,EASTERN BARTHOLOMEW WATER,NaN,NaN,...,NaN,BARTHOLOMEW,NaN,NaN,NaN,False,NETFOSAA,0.0,NaN,Finished Water
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16099,5245029-03 GW013,NaN,Indiana Department of Environmental Management,NaN,NaN,2023-07-05 08:25:00,IN5245029,INDIANA AMERICAN WATER - LOWELL,NaN,NaN,...,NaN,LAKE,NaN,NaN,NaN,False,NETFOSAA,0.0,NaN,Untreated Water
16100,5245029-03 GW013,NaN,Indiana Department of Environmental Management,NaN,NaN,2023-07-05 08:25:00,IN5245029,INDIANA AMERICAN WATER - LOWELL,NaN,NaN,...,NaN,LAKE,NaN,NaN,NaN,False,NMEFOSAA,0.0,NaN,Untreated Water
16101,5245029-03 GW013,NaN,Indiana Department of Environmental Management,NaN,NaN,2023-07-05 08:25:00,IN5245029,INDIANA AMERICAN WATER - LOWELL,NaN,NaN,...,NaN,LAKE,NaN,NaN,NaN,False,11CL-PF3OUDS,0.0,NaN,Untreated Water
16102,5245029-03 GW013,NaN,Indiana Department of Environmental Management,NaN,NaN,2023-07-05 08:25:00,IN5245029,INDIANA AMERICAN WATER - LOWELL,NaN,NaN,...,NaN,LAKE,NaN,NaN,NaN,False,ADONA,0.0,NaN,Untreated Water
16103,5245029-03 GW013,NaN,Indiana Department of Environmental Management,NaN,NaN,2023-07-05 08:25:00,IN5245029,INDIANA AMERICAN WATER - LOWELL,NaN,NaN,...,NaN,LAKE,NaN,NaN,NaN,False,9CL-PF3ONS,0.0,NaN,Untreated Water

In [45]:
in_df5 = pd.read_excel('pfas_results_2_update.xlsx', sheet_name = 'Phase 2 resample post')

In [46]:
in_df5

,County,System Name,PWSID,Lab ID,Sample ID,Sampling Point Description,Matrix,Collected Date,Acronym,Parameter,Results,Units
0,PERRY,AND-TRO WATER AUTHORITY - DISTRICT 1,IN5262001,R5262001-02 EP001,35814224002,CC002-Tell City,Finish Water,2023-07-11 14:31:00,PFOA,Perfluorooctanoic acid,3.6,ng/L
1,PERRY,AND-TRO WATER AUTHORITY - DISTRICT 1,IN5262001,R5262001-01 Field Blank,35814224001,Field Blank,Field Blank,2023-07-11 14:30:00,11Cl-PF3OUdS,11Cl-PF3OUdS,ND,ng/L
2,PERRY,AND-TRO WATER AUTHORITY - DISTRICT 1,IN5262001,R5262001-01 Field Blank,35814224001,Field Blank,Field Blank,2023-07-11 14:30:00,9Cl-PF3ONS,9Cl-PF3ONS,ND,ng/L
3,PERRY,AND-TRO WATER AUTHORITY - DISTRICT 1,IN5262001,R5262001-01 Field Blank,35814224001,Field Blank,Field Blank,2023-07-11 14:30:00,ADONA,ADONA,ND,ng/L
4,PERRY,AND-TRO WATER AUTHORITY - DISTRICT 1,IN5262001,R5262001-01 Field Blank,35814224001,Field Blank,Field Blank,2023-07-11 14:30:00,GenX,HFPO-DA,ND,ng/L
...,...,...,...,...,...,...,...,...,...,...,...,...
1831,DECATUR,WESTPORT WATER COMPANY,IN5216005,R5216005-03 TOCRAW-TP01,35806312003,Before any Treatment,Untreated Water,2023-06-13 11:41:00,PFNA,Perfluorononanoic acid,ND,ng/L
1832,DECATUR,WESTPORT WATER COMPANY,IN5216005,R5216005-03 TOCRAW-TP01,35806312003,Before any Treatment,Untreated Water,2023-06-13 11:41:00,PFOA,Perfluorooctanoic acid,ND,ng/L
1833,DECATUR,WESTPORT WATER COMPANY,IN5216005,R5216005-03 TOCRAW-TP01,35806312003,Before any Treatment,Untreated Water,2023-06-13 11:41:00,PFTeDA,Perfluorotetradecanoic acid,ND,ng/L
1834,DECATUR,WESTPORT WATER COMPANY,IN5216005,R5216005-03 TOCRAW-TP01,35806312003,Before any Treatment,Untreated Water,2023-06-13 11:41:00,PFTrDA,Perfluorotridecanoic acid,ND,ng/L
1835,DECATUR,WESTPORT WATER COMPANY,IN5216005,R5216005-03 TOCRAW-TP01,35806312003,Before any Treatment,Untreated Water,2023-06-13 11:41:00,PFUdA,Perfluoroundecanoic acid,ND,ng/L

In [47]:
in_df5['Results'] = in_df5['Results'].apply(process_result)
in_df5['is_detected'] = in_df5['Results'] != 0

In [48]:
in_df5

,County,System Name,PWSID,Lab ID,Sample ID,Sampling Point Description,Matrix,Collected Date,Acronym,Parameter,Results,Units,is_detected
0,PERRY,AND-TRO WATER AUTHORITY - DISTRICT 1,IN5262001,R5262001-02 EP001,35814224002,CC002-Tell City,Finish Water,2023-07-11 14:31:00,PFOA,Perfluorooctanoic acid,3.6,ng/L,True
1,PERRY,AND-TRO WATER AUTHORITY - DISTRICT 1,IN5262001,R5262001-01 Field Blank,35814224001,Field Blank,Field Blank,2023-07-11 14:30:00,11Cl-PF3OUdS,11Cl-PF3OUdS,0.0,ng/L,False
2,PERRY,AND-TRO WATER AUTHORITY - DISTRICT 1,IN5262001,R5262001-01 Field Blank,35814224001,Field Blank,Field Blank,2023-07-11 14:30:00,9Cl-PF3ONS,9Cl-PF3ONS,0.0,ng/L,False
3,PERRY,AND-TRO WATER AUTHORITY - DISTRICT 1,IN5262001,R5262001-01 Field Blank,35814224001,Field Blank,Field Blank,2023-07-11 14:30:00,ADONA,ADONA,0.0,ng/L,False
4,PERRY,AND-TRO WATER AUTHORITY - DISTRICT 1,IN5262001,R5262001-01 Field Blank,35814224001,Field Blank,Field Blank,2023-07-11 14:30:00,GenX,HFPO-DA,0.0,ng/L,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1831,DECATUR,WESTPORT WATER COMPANY,IN5216005,R5216005-03 TOCRAW-TP01,35806312003,Before any Treatment,Untreated Water,2023-06-13 11:41:00,PFNA,Perfluorononanoic acid,0.0,ng/L,False
1832,DECATUR,WESTPORT WATER COMPANY,IN5216005,R5216005-03 TOCRAW-TP01,35806312003,Before any Treatment,Untreated Water,2023-06-13 11:41:00,PFOA,Perfluorooctanoic acid,0.0,ng/L,False
1833,DECATUR,WESTPORT WATER COMPANY,IN5216005,R5216005-03 TOCRAW-TP01,35806312003,Before any Treatment,Untreated Water,2023-06-13 11:41:00,PFTeDA,Perfluorotetradecanoic acid,0.0,ng/L,False
1834,DECATUR,WESTPORT WATER COMPANY,IN5216005,R5216005-03 TOCRAW-TP01,35806312003,Before any Treatment,Untreated Water,2023-06-13 11:41:00,PFTrDA,Perfluorotridecanoic acid,0.0,ng/L,False
1835,DECATUR,WESTPORT WATER COMPANY,IN5216005,R5216005-03 TOCRAW-TP01,35806312003,Before any Treatment,Untreated Water,2023-06-13 11:41:00,PFUdA,Perfluoroundecanoic acid,0.0,ng/L,False

In [49]:
df5 = pd.DataFrame({col: pd.Series(dtype=dt) for col, dt in columns.items()})
df5['sample_id'] = in_df5['Sample ID']
df5['data_source'] = 'Indiana Department of Environmental Management'
df5['sampling_date'] = pd.to_datetime(in_df5['Collected Date'])
df5['pws_id'] =  in_df5['PWSID']
df5['water_system_name'] = in_df5['System Name']
df5['units'] = in_df5['Units']
df5['county'] = in_df5['County']
df5['analyte'] = in_df5['Acronym'].str.upper()
df5['concentration'] = in_df5['Results']
df5['note'] = in_df5['Matrix']
df5['is_detected'] = in_df5['is_detected']
df5['source_type'] = 'drinking water'
df5['state'] = 'Indiana'

In [50]:
df5

,sample_id,sampling_location,data_source,latitude,longitude,sampling_date,pws_id,water_system_name,population,well_type,...,city,county,MRL,DL,analytical_methods,is_detected,analyte,concentration,pfas_total,note
0,35814224002,NaN,Indiana Department of Environmental Management,NaN,NaN,2023-07-11 14:31:00,IN5262001,AND-TRO WATER AUTHORITY - DISTRICT 1,NaN,NaN,...,NaN,PERRY,NaN,NaN,NaN,True,PFOA,3.6,NaN,Finish Water
1,35814224001,NaN,Indiana Department of Environmental Management,NaN,NaN,2023-07-11 14:30:00,IN5262001,AND-TRO WATER AUTHORITY - DISTRICT 1,NaN,NaN,...,NaN,PERRY,NaN,NaN,NaN,False,11CL-PF3OUDS,0.0,NaN,Field Blank
2,35814224001,NaN,Indiana Department of Environmental Management,NaN,NaN,2023-07-11 14:30:00,IN5262001,AND-TRO WATER AUTHORITY - DISTRICT 1,NaN,NaN,...,NaN,PERRY,NaN,NaN,NaN,False,9CL-PF3ONS,0.0,NaN,Field Blank
3,35814224001,NaN,Indiana Department of Environmental Management,NaN,NaN,2023-07-11 14:30:00,IN5262001,AND-TRO WATER AUTHORITY - DISTRICT 1,NaN,NaN,...,NaN,PERRY,NaN,NaN,NaN,False,ADONA,0.0,NaN,Field Blank
4,35814224001,NaN,Indiana Department of Environmental Management,NaN,NaN,2023-07-11 14:30:00,IN5262001,AND-TRO WATER AUTHORITY - DISTRICT 1,NaN,NaN,...,NaN,PERRY,NaN,NaN,NaN,False,GENX,0.0,NaN,Field Blank
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1831,35806312003,NaN,Indiana Department of Environmental Management,NaN,NaN,2023-06-13 11:41:00,IN5216005,WESTPORT WATER COMPANY,NaN,NaN,...,NaN,DECATUR,NaN,NaN,NaN,False,PFNA,0.0,NaN,Untreated Water
1832,35806312003,NaN,Indiana Department of Environmental Management,NaN,NaN,2023-06-13 11:41:00,IN5216005,WESTPORT WATER COMPANY,NaN,NaN,...,NaN,DECATUR,NaN,NaN,NaN,False,PFOA,0.0,NaN,Untreated Water
1833,35806312003,NaN,Indiana Department of Environmental Management,NaN,NaN,2023-06-13 11:41:00,IN5216005,WESTPORT WATER COMPANY,NaN,NaN,...,NaN,DECATUR,NaN,NaN,NaN,False,PFTEDA,0.0,NaN,Untreated Water
1834,35806312003,NaN,Indiana Department of Environmental Management,NaN,NaN,2023-06-13 11:41:00,IN5216005,WESTPORT WATER COMPANY,NaN,NaN,...,NaN,DECATUR,NaN,NaN,NaN,False,PFTRDA,0.0,NaN,Untreated Water
1835,35806312003,NaN,Indiana Department of Environmental Management,NaN,NaN,2023-06-13 11:41:00,IN5216005,WESTPORT WATER COMPANY,NaN,NaN,...,NaN,DECATUR,NaN,NaN,NaN,False,PFUDA,0.0,NaN,Untreated Water

In [51]:
in_df6 = pd.read_excel('pfas_results_2.xlsx', sheet_name = 'Phase 2 Results Post')

In [52]:
in_df6

,County,System_Name_Proper,PWSID,Lab ID,Sample ID,Location ID,Sample Type,DateSampled,Acronym,Parameter,Results,Units
0,ADAMS,Monroe Water Department,IN5201004,35754470002,5201004-02 EP001,EP001,Finished Water,2022-10-18,11Cl-PF3OUdS,11Cl-PF3OUdS,ND,ng/L
1,ADAMS,Monroe Water Department,IN5201004,35754470002,5201004-02 EP001,EP001,Finished Water,2022-10-18,9Cl-PF3ONS,9Cl-PF3ONS,ND,ng/L
2,ADAMS,Monroe Water Department,IN5201004,35754470002,5201004-02 EP001,EP001,Finished Water,2022-10-18,ADONA,ADONA,ND,ng/L
3,ADAMS,Monroe Water Department,IN5201004,35754470002,5201004-02 EP001,EP001,Finished Water,2022-10-18,GenX,HFPO-DA,ND,ng/L
4,ADAMS,Monroe Water Department,IN5201004,35754470002,5201004-02 EP001,EP001,Finished Water,2022-10-18,NEtFOSAA,NEtFOSAA,ND,ng/L
...,...,...,...,...,...,...,...,...,...,...,...,...
19849,OWEN,GOSPORT WATER UTILITY,IN5260003,35845483001,GW003,WELL #1,Untreated Water,2023-12-04,NEtFOSAA,NEtFOSAA,ND,ng/L
19850,OWEN,GOSPORT WATER UTILITY,IN5260003,35845483001,GW003,WELL #1,Untreated Water,2023-12-04,NMeFOSAA,NMeFOSAA,ND,ng/L
19851,OWEN,GOSPORT WATER UTILITY,IN5260003,35845483001,GW003,WELL #1,Untreated Water,2023-12-04,11Cl-PF3OUdS,11Cl-PF3OUdS,ND,ng/L
19852,OWEN,GOSPORT WATER UTILITY,IN5260003,35845483001,GW003,WELL #1,Untreated Water,2023-12-04,ADONA,ADONA,ND,ng/L
19853,OWEN,GOSPORT WATER UTILITY,IN5260003,35845483001,GW003,WELL #1,Untreated Water,2023-12-04,9Cl-PF3ONS,9Cl-PF3ONS,ND,ng/L

In [53]:
in_df6['Results'].unique()

array(['ND', '2.0', '2.1', '3.1', '4.0', '3.0', '3.4', '2.9', '1.9',
       '4.1', '7.4', '2.2', '2.8', '2.4', '3.7', '9.6', '2.7', '3.5',
       '4.4', '3.2', '2.3', '6.1', '3.9', '6.3', '13.2', '2.5', '4.3',
       '5.6', '2.6', '5.0', '5.8', '7.6', '14.0', '13.6', '4.2', '11.7',
       '6.9', '3.6', '3.3', '6.4', '8.2', '3.8', '2', '1.8', '5.2', '4.7',
       '4.9', '4', '12.3', '12.2', '11.3', 1.8, 2.1, 7, 3, 19.2, 26.9],
      dtype=object)

In [54]:
in_df6['Results'] = in_df6['Results'].apply(process_result)
in_df6['is_detected'] = in_df6['Results'] != 0

In [55]:
in_df6

,County,System_Name_Proper,PWSID,Lab ID,Sample ID,Location ID,Sample Type,DateSampled,Acronym,Parameter,Results,Units,is_detected
0,ADAMS,Monroe Water Department,IN5201004,35754470002,5201004-02 EP001,EP001,Finished Water,2022-10-18,11Cl-PF3OUdS,11Cl-PF3OUdS,0.0,ng/L,False
1,ADAMS,Monroe Water Department,IN5201004,35754470002,5201004-02 EP001,EP001,Finished Water,2022-10-18,9Cl-PF3ONS,9Cl-PF3ONS,0.0,ng/L,False
2,ADAMS,Monroe Water Department,IN5201004,35754470002,5201004-02 EP001,EP001,Finished Water,2022-10-18,ADONA,ADONA,0.0,ng/L,False
3,ADAMS,Monroe Water Department,IN5201004,35754470002,5201004-02 EP001,EP001,Finished Water,2022-10-18,GenX,HFPO-DA,0.0,ng/L,False
4,ADAMS,Monroe Water Department,IN5201004,35754470002,5201004-02 EP001,EP001,Finished Water,2022-10-18,NEtFOSAA,NEtFOSAA,0.0,ng/L,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19849,OWEN,GOSPORT WATER UTILITY,IN5260003,35845483001,GW003,WELL #1,Untreated Water,2023-12-04,NEtFOSAA,NEtFOSAA,0.0,ng/L,False
19850,OWEN,GOSPORT WATER UTILITY,IN5260003,35845483001,GW003,WELL #1,Untreated Water,2023-12-04,NMeFOSAA,NMeFOSAA,0.0,ng/L,False
19851,OWEN,GOSPORT WATER UTILITY,IN5260003,35845483001,GW003,WELL #1,Untreated Water,2023-12-04,11Cl-PF3OUdS,11Cl-PF3OUdS,0.0,ng/L,False
19852,OWEN,GOSPORT WATER UTILITY,IN5260003,35845483001,GW003,WELL #1,Untreated Water,2023-12-04,ADONA,ADONA,0.0,ng/L,False
19853,OWEN,GOSPORT WATER UTILITY,IN5260003,35845483001,GW003,WELL #1,Untreated Water,2023-12-04,9Cl-PF3ONS,9Cl-PF3ONS,0.0,ng/L,False

In [56]:
df6 = pd.DataFrame({col: pd.Series(dtype=dt) for col, dt in columns.items()})
df6['sample_id'] = in_df6['Sample ID']
df6['data_source'] = 'Indiana Department of Environmental Management'
df6['sampling_date'] = pd.to_datetime(in_df6['DateSampled'])
df6['pws_id'] =  in_df6['PWSID']
df6['water_system_name'] = in_df6['System_Name_Proper']
df6['units'] = in_df6['Units']
df6['county'] = in_df6['County']
df6['analyte'] = in_df6['Acronym'].str.upper()
df6['concentration'] = in_df6['Results']
df6['note'] = in_df6['Sample Type']
df6['is_detected'] = in_df6['is_detected']
df6['source_type'] = 'drinking water'
df6['state'] = 'Indiana'

In [57]:
df6

,sample_id,sampling_location,data_source,latitude,longitude,sampling_date,pws_id,water_system_name,population,well_type,...,city,county,MRL,DL,analytical_methods,is_detected,analyte,concentration,pfas_total,note
0,5201004-02 EP001,NaN,Indiana Department of Environmental Management,NaN,NaN,2022-10-18,IN5201004,Monroe Water Department,NaN,NaN,...,NaN,ADAMS,NaN,NaN,NaN,False,11CL-PF3OUDS,0.0,NaN,Finished Water
1,5201004-02 EP001,NaN,Indiana Department of Environmental Management,NaN,NaN,2022-10-18,IN5201004,Monroe Water Department,NaN,NaN,...,NaN,ADAMS,NaN,NaN,NaN,False,9CL-PF3ONS,0.0,NaN,Finished Water
2,5201004-02 EP001,NaN,Indiana Department of Environmental Management,NaN,NaN,2022-10-18,IN5201004,Monroe Water Department,NaN,NaN,...,NaN,ADAMS,NaN,NaN,NaN,False,ADONA,0.0,NaN,Finished Water
3,5201004-02 EP001,NaN,Indiana Department of Environmental Management,NaN,NaN,2022-10-18,IN5201004,Monroe Water Department,NaN,NaN,...,NaN,ADAMS,NaN,NaN,NaN,False,GENX,0.0,NaN,Finished Water
4,5201004-02 EP001,NaN,Indiana Department of Environmental Management,NaN,NaN,2022-10-18,IN5201004,Monroe Water Department,NaN,NaN,...,NaN,ADAMS,NaN,NaN,NaN,False,NETFOSAA,0.0,NaN,Finished Water
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19849,GW003,NaN,Indiana Department of Environmental Management,NaN,NaN,2023-12-04,IN5260003,GOSPORT WATER UTILITY,NaN,NaN,...,NaN,OWEN,NaN,NaN,NaN,False,NETFOSAA,0.0,NaN,Untreated Water
19850,GW003,NaN,Indiana Department of Environmental Management,NaN,NaN,2023-12-04,IN5260003,GOSPORT WATER UTILITY,NaN,NaN,...,NaN,OWEN,NaN,NaN,NaN,False,NMEFOSAA,0.0,NaN,Untreated Water
19851,GW003,NaN,Indiana Department of Environmental Management,NaN,NaN,2023-12-04,IN5260003,GOSPORT WATER UTILITY,NaN,NaN,...,NaN,OWEN,NaN,NaN,NaN,False,11CL-PF3OUDS,0.0,NaN,Untreated Water
19852,GW003,NaN,Indiana Department of Environmental Management,NaN,NaN,2023-12-04,IN5260003,GOSPORT WATER UTILITY,NaN,NaN,...,NaN,OWEN,NaN,NaN,NaN,False,ADONA,0.0,NaN,Untreated Water
19853,GW003,NaN,Indiana Department of Environmental Management,NaN,NaN,2023-12-04,IN5260003,GOSPORT WATER UTILITY,NaN,NaN,...,NaN,OWEN,NaN,NaN,NaN,False,9CL-PF3ONS,0.0,NaN,Untreated Water

In [58]:
df = pd.concat([df1, df2, df3, df4, df5, df6])

In [59]:
df[df['analyte'].isna()]

,sample_id,sampling_location,data_source,latitude,longitude,sampling_date,pws_id,water_system_name,population,well_type,...,city,county,MRL,DL,analytical_methods,is_detected,analyte,concentration,pfas_total,note
4751,NaN,NaN,Indiana Department of Environmental Management,NaN,NaN,NaT,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN

In [61]:
df = df.dropna(subset=['analyte'])

In [62]:
df['units'].unique()

array(['ng/L', 'ug/L'], dtype=object)

In [63]:
df.loc[df['units'] == 'ug/L', 'concentration'] *= 1000
df['units'] = 'ng/L'

In [65]:
df.index = range(0, len(df))

In [66]:
df

,sample_id,sampling_location,data_source,latitude,longitude,sampling_date,pws_id,water_system_name,population,well_type,...,city,county,MRL,DL,analytical_methods,is_detected,analyte,concentration,pfas_total,note
0,E21005959-001,NaN,Indiana Department of Environmental Management,NaN,NaN,2021-03-01,IN5201001,Berne Water Department,NaN,NaN,...,NaN,ADAMS,NaN,2.0,NaN,False,11CL-PF3OUDS,0.0,NaN,Field Blank
1,E21005959-001,NaN,Indiana Department of Environmental Management,NaN,NaN,2021-03-01,IN5201001,Berne Water Department,NaN,NaN,...,NaN,ADAMS,NaN,2.0,NaN,False,9CL-PF3ONS,0.0,NaN,Field Blank
2,E21005959-001,NaN,Indiana Department of Environmental Management,NaN,NaN,2021-03-01,IN5201001,Berne Water Department,NaN,NaN,...,NaN,ADAMS,NaN,2.0,NaN,False,ADONA,0.0,NaN,Field Blank
3,E21005959-001,NaN,Indiana Department of Environmental Management,NaN,NaN,2021-03-01,IN5201001,Berne Water Department,NaN,NaN,...,NaN,ADAMS,NaN,10.0,NaN,False,HFPO-DA,0.0,NaN,Field Blank
4,E21005959-001,NaN,Indiana Department of Environmental Management,NaN,NaN,2021-03-01,IN5201001,Berne Water Department,NaN,NaN,...,NaN,ADAMS,NaN,2.0,NaN,False,N-ETFOSAA,0.0,NaN,Field Blank
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50442,GW003,NaN,Indiana Department of Environmental Management,NaN,NaN,2023-12-04,IN5260003,GOSPORT WATER UTILITY,NaN,NaN,...,NaN,OWEN,NaN,NaN,NaN,False,NETFOSAA,0.0,NaN,Untreated Water
50443,GW003,NaN,Indiana Department of Environmental Management,NaN,NaN,2023-12-04,IN5260003,GOSPORT WATER UTILITY,NaN,NaN,...,NaN,OWEN,NaN,NaN,NaN,False,NMEFOSAA,0.0,NaN,Untreated Water
50444,GW003,NaN,Indiana Department of Environmental Management,NaN,NaN,2023-12-04,IN5260003,GOSPORT WATER UTILITY,NaN,NaN,...,NaN,OWEN,NaN,NaN,NaN,False,11CL-PF3OUDS,0.0,NaN,Untreated Water
50445,GW003,NaN,Indiana Department of Environmental Management,NaN,NaN,2023-12-04,IN5260003,GOSPORT WATER UTILITY,NaN,NaN,...,NaN,OWEN,NaN,NaN,NaN,False,ADONA,0.0,NaN,Untreated Water
50446,GW003,NaN,Indiana Department of Environmental Management,NaN,NaN,2023-12-04,IN5260003,GOSPORT WATER UTILITY,NaN,NaN,...,NaN,OWEN,NaN,NaN,NaN,False,9CL-PF3ONS,0.0,NaN,Untreated Water

In [67]:
df.to_csv('indiana_dw.csv')