In [1]:
import pandas as pd
import os
import numpy as np

In [2]:
os.getcwd()

'/Users/chuqiwang/Documents/US_PFAS_Project/data_cleaning/Maryland'

In [3]:
md_df1 = pd.read_excel('Export_Joint Base Andrews.xlsx')

In [4]:
md_df1

,Component ID,Component,State,Installation Name,Installation Type,Lab Report Id,Laboratory Sample ID,Sample Date,Analysis Method,CAS Number,Analyte Abbreviation,Final Result,Limit of Detection,Final Units,Final Qualification,Treatment System,Pre Or Post Treatment
0,5700,Air Force,Maryland,Joint Base Andrews,Active,FA98605,FA98605-4,8/29/2022,QSM_B15,757124-72-4,4:2FTS,NaN,8,ng/L,U,No,NaN
1,5700,Air Force,Maryland,Joint Base Andrews,Active,FA98605,FA98605-4,8/29/2022,QSM_B15,27619-97-2,6:2FTS,NaN,8,ng/L,U,No,NaN
2,5700,Air Force,Maryland,Joint Base Andrews,Active,FA98605,FA98605-4,8/29/2022,QSM_B15,39108-34-4,8:2FTS,NaN,8,ng/L,U,No,NaN
3,5700,Air Force,Maryland,Joint Base Andrews,Active,FA98605,FA98605-4,8/29/2022,QSM_B15,2991-50-6,NEtFOSAA,NaN,40,ng/L,U,No,NaN
4,5700,Air Force,Maryland,Joint Base Andrews,Active,FA98605,FA98605-4,8/29/2022,QSM_B15,2355-31-9,NMeFOSAA,NaN,8,ng/L,U,No,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,5700,Air Force,Maryland,Joint Base Andrews,Active,FA98605,FA98605-2,8/29/2022,QSM_B15,2706-91-4,PFPeS,NaN,4,ng/L,U,No,NaN
68,5700,Air Force,Maryland,Joint Base Andrews,Active,FA98605,FA98605-2,8/29/2022,QSM_B15,2706-90-3,PFPeA,NaN,4,ng/L,U,No,NaN
69,5700,Air Force,Maryland,Joint Base Andrews,Active,FA98605,FA98605-2,8/29/2022,QSM_B15,376-06-7,PFTeDA,NaN,4,ng/L,U,No,NaN
70,5700,Air Force,Maryland,Joint Base Andrews,Active,FA98605,FA98605-2,8/29/2022,QSM_B15,72629-94-8,PFTrDA,NaN,4,ng/L,U,No,NaN
71,5700,Air Force,Maryland,Joint Base Andrews,Active,FA98605,FA98605-2,8/29/2022,QSM_B15,2058-94-8,PFUnA,NaN,4,ng/L,U,No,NaN

In [5]:
columns = {
    'sample_id': str,
    'sampling_location': str,
    'data_source': str,
    'latitude': float,
    'longitude': float,
    'sampling_date': 'datetime64[ns]',
    'pws_id': str,
    'water_system_name': str,
    'population': int,
    'well_type': str,
    'well_depth': float,
    'units': str,
    'source_type': str,
    'state': str,
    'city': str,
    'county': str,
    'MRL': float,
    'DL': float,
    'analytical_methods': str,
    'is_detected': bool,
    'analyte': str,
    'concentration': float,
    'pfas_total': float,
    'note': str   
}

In [6]:
df1 = pd.DataFrame({col: pd.Series(dtype=dt) for col, dt in columns.items()})
df1['analyte'] = md_df1['Analyte Abbreviation'].str.upper()
df1['concentration'] = md_df1['Final Result'].fillna(0)
df1['sampling_location'] = md_df1['Installation Name']
df1['DL'] = md_df1['Limit of Detection']
df1['sampling_date'] = pd.to_datetime(md_df1['Sample Date'])
df1['sample_id'] = md_df1['Laboratory Sample ID']
df1['units'] = md_df1['Final Units']
df1['state'] = md_df1['State']
df1['analytical_methods'] = md_df1['Analysis Method']
df1['data_source'] = 'DoD'
df1['source_type'] = 'drinking water'

In [7]:
df1['is_detected'] = df1['concentration'] != 0

In [8]:
df1

,sample_id,sampling_location,data_source,latitude,longitude,sampling_date,pws_id,water_system_name,population,well_type,...,city,county,MRL,DL,analytical_methods,is_detected,analyte,concentration,pfas_total,note
0,FA98605-4,Joint Base Andrews,DoD,NaN,NaN,2022-08-29,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,8,QSM_B15,False,4:2FTS,0.0,NaN,NaN
1,FA98605-4,Joint Base Andrews,DoD,NaN,NaN,2022-08-29,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,8,QSM_B15,False,6:2FTS,0.0,NaN,NaN
2,FA98605-4,Joint Base Andrews,DoD,NaN,NaN,2022-08-29,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,8,QSM_B15,False,8:2FTS,0.0,NaN,NaN
3,FA98605-4,Joint Base Andrews,DoD,NaN,NaN,2022-08-29,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,40,QSM_B15,False,NETFOSAA,0.0,NaN,NaN
4,FA98605-4,Joint Base Andrews,DoD,NaN,NaN,2022-08-29,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,8,QSM_B15,False,NMEFOSAA,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,FA98605-2,Joint Base Andrews,DoD,NaN,NaN,2022-08-29,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,4,QSM_B15,False,PFPES,0.0,NaN,NaN
68,FA98605-2,Joint Base Andrews,DoD,NaN,NaN,2022-08-29,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,4,QSM_B15,False,PFPEA,0.0,NaN,NaN
69,FA98605-2,Joint Base Andrews,DoD,NaN,NaN,2022-08-29,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,4,QSM_B15,False,PFTEDA,0.0,NaN,NaN
70,FA98605-2,Joint Base Andrews,DoD,NaN,NaN,2022-08-29,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,4,QSM_B15,False,PFTRDA,0.0,NaN,NaN
71,FA98605-2,Joint Base Andrews,DoD,NaN,NaN,2022-08-29,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,4,QSM_B15,False,PFUNA,0.0,NaN,NaN

In [9]:
md_df2 = pd.read_excel('Export_NSF Thurmont.xlsx')

In [10]:
df2 = pd.DataFrame({col: pd.Series(dtype=dt) for col, dt in columns.items()})
df2['analyte'] = md_df2['Analyte Abbreviation'].str.upper()
df2['concentration'] = md_df2['Final Result'].fillna(0)
df2['sampling_location'] = md_df2['Installation Name']
df2['DL'] = md_df2['Limit of Detection']
df2['sampling_date'] = pd.to_datetime(md_df2['Sample Date'])
df2['sample_id'] = md_df2['Laboratory Sample ID']
df2['units'] = md_df2['Final Units']
df2['state'] = md_df2['State']
df2['analytical_methods'] = md_df2['Analysis Method']
df2['data_source'] = 'DoD'
df2['source_type'] = 'drinking water'

In [11]:
df2['is_detected'] = df2['concentration'] != 0

In [12]:
df2

,sample_id,sampling_location,data_source,latitude,longitude,sampling_date,pws_id,water_system_name,population,well_type,...,city,county,MRL,DL,analytical_methods,is_detected,analyte,concentration,pfas_total,note
0,2303063-01,NSF Thurmont,DoD,NaN,NaN,2023-03-01,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.60,537.1,False,HFPO-DA,0.00,NaN,NaN
1,2303063-01,NSF Thurmont,DoD,NaN,NaN,2023-03-01,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.60,537.1,True,PFOS,8.04,NaN,NaN
2,2303063-01,NSF Thurmont,DoD,NaN,NaN,2023-03-01,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.60,537.1,False,PFUNA,0.00,NaN,NaN
3,2303063-01,NSF Thurmont,DoD,NaN,NaN,2023-03-01,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.60,537.1,False,NMEFOSAA,0.00,NaN,NaN
4,2303063-01,NSF Thurmont,DoD,NaN,NaN,2023-03-01,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.60,537.1,False,NETFOSAA,0.00,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
373,2305187-01,NSF Thurmont,DoD,NaN,NaN,2023-05-17,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.45,537.1,False,PFTEDA,0.00,NaN,NaN
374,2305187-01,NSF Thurmont,DoD,NaN,NaN,2023-05-17,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.45,537.1,False,PFTRDA,0.00,NaN,NaN
375,2305187-01,NSF Thurmont,DoD,NaN,NaN,2023-05-17,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.45,537.1,False,9CL-PF3ONS,0.00,NaN,NaN
376,2305187-01,NSF Thurmont,DoD,NaN,NaN,2023-05-17,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.45,537.1,False,11CL-PF3OUDS,0.00,NaN,NaN
377,2305187-01,NSF Thurmont,DoD,NaN,NaN,2023-05-17,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.45,537.1,False,ADONA,0.00,NaN,NaN

In [30]:
md_df3 = pd.read_excel('Phase4PFASResulstTable.xlsx')

In [31]:
md_df3 = md_df3.replace(['<RL', '<Rl'], float(0))

/var/folders/m8/kh2nk5652k94h_n7lqjvr8n00000gn/T/ipykernel_56834/2363027566.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  md_df3 = md_df3.replace(['<RL', '<Rl'], float(0))

In [32]:
md_df3

,COUNTY,PWSID,SYSTEM NAME,SAMPLE ID,SITE NAME,SAMPLE \nCOLLECTION \nDATE,SAMPLE TYPE (UNTREATED VS FINISHED),PFOS,PFOA,PFNA,...,PFDA,11Cl-PF3OUdS,ADONA,9Cl-PF3ONS,N-EtFOSAA,N-MeFOSAA,PFDoA,PFTDA,PFTrDA,PFUnDA
0,ANNE ARUNDEL,MD0020017,GLEN BURNIE-BROADNECK,002-0017-TP16,DORSEY ROAD WTP,2022-09-19,Finished,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,ANNE ARUNDEL,MD0020223,WAYSONS MOBILE COURT,002-0223-TP01,WTP 1 (WELL 1 & WELL 2),2022-09-19,Finished,0.00,1.04,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,ANNE ARUNDEL,MD1021462,MAYO CENTER AND APARTMENTS,102-1462-TP01,MAYO APARTMENTS + SHOPPING CTR,2022-09-06,Finished,12.40,9.01,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,ANNE ARUNDEL,MD1021498,WOODLAND BEACH COMMUNITY ASSOC.,102-1498-CH01,WOODLAND BEACH WELLHEAD,2022-09-06,Finished,0.00,1.31,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,BALTIMORE,MD0030011,SUNNYBROOK,003-0011-TP01,SUNNYBROOK BALTO. CO. DPW,2022-09-22,Finished,7.58,6.50,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
223,WORCESTER,MD0230005,OCEAN PINES,023-0005-TP01,WTP 1 - WELL 3,2022-08-15,Finished,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
224,WORCESTER,MD0230005,OCEAN PINES,023-0005-TP02,WTP 2 - WELL 4,2022-08-15,Finished,1.03,2.57,1.63,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
225,WORCESTER,MD0230005,OCEAN PINES,023-0005-TP03,WTP 3 - WELL 5,2022-08-16,Finished,1.72,1.65,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
226,WORCESTER,MD0230005,OCEAN PINES,023-0005-TP04,WTP 4 - WELL 2,2022-08-15,Finished,1.06,2.08,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
227,WORCESTER,MD0230005,OCEAN PINES,023-0005-TP05,WTP 5 - WELL 10,2022-08-15,Finished,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [33]:
analyte_list = list(md_df3.columns[7:25])

In [34]:
md_df3[analyte_list]

,PFOS,PFOA,PFNA,PFHxS,PFBS,HFPO-DA,PFHpA,PFHxA,PFDA,11Cl-PF3OUdS,ADONA,9Cl-PF3ONS,N-EtFOSAA,N-MeFOSAA,PFDoA,PFTDA,PFTrDA,PFUnDA
0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.00,1.04,0.00,0.00,0.00,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,12.40,9.01,0.00,5.02,1.23,0.0,2.38,3.83,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.00,1.31,0.00,0.00,0.00,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,7.58,6.50,0.00,1.95,5.06,0.0,2.69,4.17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
223,0.00,0.00,0.00,1.42,0.00,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
224,1.03,2.57,1.63,1.10,1.85,0.0,1.85,2.39,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
225,1.72,1.65,0.00,1.41,2.22,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
226,1.06,2.08,0.00,1.59,2.74,0.0,1.20,1.39,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
227,0.00,0.00,0.00,1.42,0.00,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [35]:
columns_to_repeat = list(md_df3.columns[0:7])
df_repeated = pd.DataFrame(columns=columns_to_repeat)

for i in range(len(md_df3)):
    row_repeated = pd.concat([md_df3.iloc[[i]][columns_to_repeat]] * len(analyte_list), ignore_index=True)
    df_repeated = pd.concat([df_repeated, row_repeated], ignore_index=True)

df_repeated

/var/folders/m8/kh2nk5652k94h_n7lqjvr8n00000gn/T/ipykernel_56834/3349281169.py:6: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_repeated = pd.concat([df_repeated, row_repeated], ignore_index=True)

,COUNTY,PWSID,SYSTEM NAME,SAMPLE ID,SITE NAME,SAMPLE \nCOLLECTION \nDATE,SAMPLE TYPE (UNTREATED VS FINISHED)
0,ANNE ARUNDEL,MD0020017,GLEN BURNIE-BROADNECK,002-0017-TP16,DORSEY ROAD WTP,2022-09-19,Finished
1,ANNE ARUNDEL,MD0020017,GLEN BURNIE-BROADNECK,002-0017-TP16,DORSEY ROAD WTP,2022-09-19,Finished
2,ANNE ARUNDEL,MD0020017,GLEN BURNIE-BROADNECK,002-0017-TP16,DORSEY ROAD WTP,2022-09-19,Finished
3,ANNE ARUNDEL,MD0020017,GLEN BURNIE-BROADNECK,002-0017-TP16,DORSEY ROAD WTP,2022-09-19,Finished
4,ANNE ARUNDEL,MD0020017,GLEN BURNIE-BROADNECK,002-0017-TP16,DORSEY ROAD WTP,2022-09-19,Finished
...,...,...,...,...,...,...,...
4099,WORCESTER,MD0230005,OCEAN PINES,023-0005-TP05,WTP 5 - WELL 10,2022-08-15,Finished
4100,WORCESTER,MD0230005,OCEAN PINES,023-0005-TP05,WTP 5 - WELL 10,2022-08-15,Finished
4101,WORCESTER,MD0230005,OCEAN PINES,023-0005-TP05,WTP 5 - WELL 10,2022-08-15,Finished
4102,WORCESTER,MD0230005,OCEAN PINES,023-0005-TP05,WTP 5 - WELL 10,2022-08-15,Finished
4103,WORCESTER,MD0230005,OCEAN PINES,023-0005-TP05,WTP 5 - WELL 10,2022-08-15,Finished

In [36]:
df_repeated['analyte'] = analyte_list * len(md_df3)

In [37]:
df_repeated

,COUNTY,PWSID,SYSTEM NAME,SAMPLE ID,SITE NAME,SAMPLE \nCOLLECTION \nDATE,SAMPLE TYPE (UNTREATED VS FINISHED),analyte
0,ANNE ARUNDEL,MD0020017,GLEN BURNIE-BROADNECK,002-0017-TP16,DORSEY ROAD WTP,2022-09-19,Finished,PFOS
1,ANNE ARUNDEL,MD0020017,GLEN BURNIE-BROADNECK,002-0017-TP16,DORSEY ROAD WTP,2022-09-19,Finished,PFOA
2,ANNE ARUNDEL,MD0020017,GLEN BURNIE-BROADNECK,002-0017-TP16,DORSEY ROAD WTP,2022-09-19,Finished,PFNA
3,ANNE ARUNDEL,MD0020017,GLEN BURNIE-BROADNECK,002-0017-TP16,DORSEY ROAD WTP,2022-09-19,Finished,PFHxS
4,ANNE ARUNDEL,MD0020017,GLEN BURNIE-BROADNECK,002-0017-TP16,DORSEY ROAD WTP,2022-09-19,Finished,PFBS
...,...,...,...,...,...,...,...,...
4099,WORCESTER,MD0230005,OCEAN PINES,023-0005-TP05,WTP 5 - WELL 10,2022-08-15,Finished,N-MeFOSAA
4100,WORCESTER,MD0230005,OCEAN PINES,023-0005-TP05,WTP 5 - WELL 10,2022-08-15,Finished,PFDoA
4101,WORCESTER,MD0230005,OCEAN PINES,023-0005-TP05,WTP 5 - WELL 10,2022-08-15,Finished,PFTDA
4102,WORCESTER,MD0230005,OCEAN PINES,023-0005-TP05,WTP 5 - WELL 10,2022-08-15,Finished,PFTrDA
4103,WORCESTER,MD0230005,OCEAN PINES,023-0005-TP05,WTP 5 - WELL 10,2022-08-15,Finished,PFUnDA

In [38]:
df_repeated['concentration'] = md_df3[analyte_list].values.flatten().tolist()

In [39]:
df_repeated

,COUNTY,PWSID,SYSTEM NAME,SAMPLE ID,SITE NAME,SAMPLE \nCOLLECTION \nDATE,SAMPLE TYPE (UNTREATED VS FINISHED),analyte,concentration
0,ANNE ARUNDEL,MD0020017,GLEN BURNIE-BROADNECK,002-0017-TP16,DORSEY ROAD WTP,2022-09-19,Finished,PFOS,0.0
1,ANNE ARUNDEL,MD0020017,GLEN BURNIE-BROADNECK,002-0017-TP16,DORSEY ROAD WTP,2022-09-19,Finished,PFOA,0.0
2,ANNE ARUNDEL,MD0020017,GLEN BURNIE-BROADNECK,002-0017-TP16,DORSEY ROAD WTP,2022-09-19,Finished,PFNA,0.0
3,ANNE ARUNDEL,MD0020017,GLEN BURNIE-BROADNECK,002-0017-TP16,DORSEY ROAD WTP,2022-09-19,Finished,PFHxS,0.0
4,ANNE ARUNDEL,MD0020017,GLEN BURNIE-BROADNECK,002-0017-TP16,DORSEY ROAD WTP,2022-09-19,Finished,PFBS,0.0
...,...,...,...,...,...,...,...,...,...
4099,WORCESTER,MD0230005,OCEAN PINES,023-0005-TP05,WTP 5 - WELL 10,2022-08-15,Finished,N-MeFOSAA,0.0
4100,WORCESTER,MD0230005,OCEAN PINES,023-0005-TP05,WTP 5 - WELL 10,2022-08-15,Finished,PFDoA,0.0
4101,WORCESTER,MD0230005,OCEAN PINES,023-0005-TP05,WTP 5 - WELL 10,2022-08-15,Finished,PFTDA,0.0
4102,WORCESTER,MD0230005,OCEAN PINES,023-0005-TP05,WTP 5 - WELL 10,2022-08-15,Finished,PFTrDA,0.0
4103,WORCESTER,MD0230005,OCEAN PINES,023-0005-TP05,WTP 5 - WELL 10,2022-08-15,Finished,PFUnDA,0.0

In [40]:
df_repeated['is_detected'] = df_repeated['concentration'] != 0

In [41]:
df_repeated

,COUNTY,PWSID,SYSTEM NAME,SAMPLE ID,SITE NAME,SAMPLE \nCOLLECTION \nDATE,SAMPLE TYPE (UNTREATED VS FINISHED),analyte,concentration,is_detected
0,ANNE ARUNDEL,MD0020017,GLEN BURNIE-BROADNECK,002-0017-TP16,DORSEY ROAD WTP,2022-09-19,Finished,PFOS,0.0,False
1,ANNE ARUNDEL,MD0020017,GLEN BURNIE-BROADNECK,002-0017-TP16,DORSEY ROAD WTP,2022-09-19,Finished,PFOA,0.0,False
2,ANNE ARUNDEL,MD0020017,GLEN BURNIE-BROADNECK,002-0017-TP16,DORSEY ROAD WTP,2022-09-19,Finished,PFNA,0.0,False
3,ANNE ARUNDEL,MD0020017,GLEN BURNIE-BROADNECK,002-0017-TP16,DORSEY ROAD WTP,2022-09-19,Finished,PFHxS,0.0,False
4,ANNE ARUNDEL,MD0020017,GLEN BURNIE-BROADNECK,002-0017-TP16,DORSEY ROAD WTP,2022-09-19,Finished,PFBS,0.0,False
...,...,...,...,...,...,...,...,...,...,...
4099,WORCESTER,MD0230005,OCEAN PINES,023-0005-TP05,WTP 5 - WELL 10,2022-08-15,Finished,N-MeFOSAA,0.0,False
4100,WORCESTER,MD0230005,OCEAN PINES,023-0005-TP05,WTP 5 - WELL 10,2022-08-15,Finished,PFDoA,0.0,False
4101,WORCESTER,MD0230005,OCEAN PINES,023-0005-TP05,WTP 5 - WELL 10,2022-08-15,Finished,PFTDA,0.0,False
4102,WORCESTER,MD0230005,OCEAN PINES,023-0005-TP05,WTP 5 - WELL 10,2022-08-15,Finished,PFTrDA,0.0,False
4103,WORCESTER,MD0230005,OCEAN PINES,023-0005-TP05,WTP 5 - WELL 10,2022-08-15,Finished,PFUnDA,0.0,False

In [42]:
df3 = pd.DataFrame({col: pd.Series(dtype=dt) for col, dt in columns.items()})
df3['analyte'] = df_repeated['analyte'].str.upper()
df3['concentration'] = df_repeated['concentration']
df3['sampling_location'] = df_repeated['SYSTEM NAME']
df3['sampling_date'] = pd.to_datetime(df_repeated['SAMPLE \nCOLLECTION \nDATE'])
df3['units'] = 'ng/L'
df3['state'] = 'Maryland'
df3['data_source'] = 'MDE'
df3['source_type'] = 'drinking water'
df3['pws_id'] = df_repeated['PWSID']
df3['county'] = df_repeated['COUNTY']
df3['is_detected'] = df_repeated['is_detected']
df3['sample_id'] = df_repeated['SAMPLE ID']
df3['note'] = df_repeated[' SAMPLE TYPE (UNTREATED VS FINISHED)']

In [43]:
df3

,sample_id,sampling_location,data_source,latitude,longitude,sampling_date,pws_id,water_system_name,population,well_type,...,city,county,MRL,DL,analytical_methods,is_detected,analyte,concentration,pfas_total,note
0,002-0017-TP16,GLEN BURNIE-BROADNECK,MDE,NaN,NaN,2022-09-19,MD0020017,NaN,NaN,NaN,...,NaN,ANNE ARUNDEL,NaN,NaN,NaN,False,PFOS,0.0,NaN,Finished
1,002-0017-TP16,GLEN BURNIE-BROADNECK,MDE,NaN,NaN,2022-09-19,MD0020017,NaN,NaN,NaN,...,NaN,ANNE ARUNDEL,NaN,NaN,NaN,False,PFOA,0.0,NaN,Finished
2,002-0017-TP16,GLEN BURNIE-BROADNECK,MDE,NaN,NaN,2022-09-19,MD0020017,NaN,NaN,NaN,...,NaN,ANNE ARUNDEL,NaN,NaN,NaN,False,PFNA,0.0,NaN,Finished
3,002-0017-TP16,GLEN BURNIE-BROADNECK,MDE,NaN,NaN,2022-09-19,MD0020017,NaN,NaN,NaN,...,NaN,ANNE ARUNDEL,NaN,NaN,NaN,False,PFHXS,0.0,NaN,Finished
4,002-0017-TP16,GLEN BURNIE-BROADNECK,MDE,NaN,NaN,2022-09-19,MD0020017,NaN,NaN,NaN,...,NaN,ANNE ARUNDEL,NaN,NaN,NaN,False,PFBS,0.0,NaN,Finished
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4099,023-0005-TP05,OCEAN PINES,MDE,NaN,NaN,2022-08-15,MD0230005,NaN,NaN,NaN,...,NaN,WORCESTER,NaN,NaN,NaN,False,N-MEFOSAA,0.0,NaN,Finished
4100,023-0005-TP05,OCEAN PINES,MDE,NaN,NaN,2022-08-15,MD0230005,NaN,NaN,NaN,...,NaN,WORCESTER,NaN,NaN,NaN,False,PFDOA,0.0,NaN,Finished
4101,023-0005-TP05,OCEAN PINES,MDE,NaN,NaN,2022-08-15,MD0230005,NaN,NaN,NaN,...,NaN,WORCESTER,NaN,NaN,NaN,False,PFTDA,0.0,NaN,Finished
4102,023-0005-TP05,OCEAN PINES,MDE,NaN,NaN,2022-08-15,MD0230005,NaN,NaN,NaN,...,NaN,WORCESTER,NaN,NaN,NaN,False,PFTRDA,0.0,NaN,Finished
4103,023-0005-TP05,OCEAN PINES,MDE,NaN,NaN,2022-08-15,MD0230005,NaN,NaN,NaN,...,NaN,WORCESTER,NaN,NaN,NaN,False,PFUNDA,0.0,NaN,Finished

In [44]:
df = pd.concat([df1, df2, df3])

In [45]:
df.index = range(0, len(df))

In [3]:
df = pd.read_csv('maryland_dw.csv', index_col=0)

In [4]:
df

,sample_id,sampling_location,data_source,latitude,longitude,sampling_date,pws_id,water_system_name,population,well_type,...,city,county,MRL,DL,analytical_methods,is_detected,analyte,concentration,pfas_total,note
0,FA98605-4,Joint Base Andrews,DoD,NaN,NaN,2022-08-29,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,8.0,QSM_B15,False,4:2FTS,0.0,NaN,NaN
1,FA98605-4,Joint Base Andrews,DoD,NaN,NaN,2022-08-29,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,8.0,QSM_B15,False,6:2FTS,0.0,NaN,NaN
2,FA98605-4,Joint Base Andrews,DoD,NaN,NaN,2022-08-29,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,8.0,QSM_B15,False,8:2FTS,0.0,NaN,NaN
3,FA98605-4,Joint Base Andrews,DoD,NaN,NaN,2022-08-29,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,40.0,QSM_B15,False,NETFOSAA,0.0,NaN,NaN
4,FA98605-4,Joint Base Andrews,DoD,NaN,NaN,2022-08-29,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,8.0,QSM_B15,False,NMEFOSAA,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4549,023-0005-TP05,OCEAN PINES,MDE,NaN,NaN,2022-08-15,MD0230005,NaN,NaN,NaN,...,NaN,WORCESTER,NaN,NaN,NaN,False,N-MEFOSAA,0.0,NaN,Finished
4550,023-0005-TP05,OCEAN PINES,MDE,NaN,NaN,2022-08-15,MD0230005,NaN,NaN,NaN,...,NaN,WORCESTER,NaN,NaN,NaN,False,PFDOA,0.0,NaN,Finished
4551,023-0005-TP05,OCEAN PINES,MDE,NaN,NaN,2022-08-15,MD0230005,NaN,NaN,NaN,...,NaN,WORCESTER,NaN,NaN,NaN,False,PFTDA,0.0,NaN,Finished
4552,023-0005-TP05,OCEAN PINES,MDE,NaN,NaN,2022-08-15,MD0230005,NaN,NaN,NaN,...,NaN,WORCESTER,NaN,NaN,NaN,False,PFTRDA,0.0,NaN,Finished
4553,023-0005-TP05,OCEAN PINES,MDE,NaN,NaN,2022-08-15,MD0230005,NaN,NaN,NaN,...,NaN,WORCESTER,NaN,NaN,NaN,False,PFUNDA,0.0,NaN,Finished

In [7]:
from concurrent.futures import ThreadPoolExecutor
import pandas as pd
from geopy.geocoders import OpenCage

geolocator = OpenCage(api_key="1f1adf3211e64148bfe6de5e054906f8")

def geocode_address(address):
    try:
        location = geolocator.geocode(address)
        if location:
            return (address, location.latitude, location.longitude)
        else:
            return (address, None, None)
    except Exception as e:
        print(f"Error geocoding {address}: {e}")
        return (address, None, None)

addresses_to_query = df.loc[df['latitude'].isna() | df['longitude'].isna(), 'sampling_location'].unique()

with ThreadPoolExecutor(max_workers=10) as executor:
    results = list(executor.map(geocode_address, addresses_to_query))

location_cache = {address: (lat, lon) for address, lat, lon in results}

Error geocoding MISTY MEADOWS 1 / HIGHLAND HILLS M.H.P.: HTTPSConnectionPool(host='api.opencagedata.com', port=443): Max retries exceeded with url: /geocode/v1/json?key=1f1adf3211e64148bfe6de5e054906f8&q=MISTY+MEADOWS+1+%2F+HIGHLAND+HILLS+M.H.P. (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api.opencagedata.com', port=443): Read timed out. (read timeout=1)"))

In [8]:
location_cache

{'Joint Base Andrews': (38.8088762, -76.8687864),
 'NSF Thurmont': (39.62371, -77.41082),
 'GLEN BURNIE-BROADNECK': (None, None),
 'WAYSONS MOBILE COURT': (38.81385, -76.70321),
 'MAYO CENTER AND APARTMENTS': (None, None),
 'WOODLAND BEACH COMMUNITY ASSOC.': (None, None),
 'SUNNYBROOK': (38.3429694, -120.8768826),
 'WOODSTOCK JOB CORPS CENTER': (39.3354587, -76.8696318),
 'PHOENIX': (33.4484367, -112.074141),
 'CHAPEL HILL NURSING CENTER': (39.396667, -76.860225),
 'GRANITE MOBILE HOME PARK': (39.3324729, -76.8515264),
 'CITY OF BALTIMORE': (39.3196465, -76.6272228),
 'B&L MOBILE HOME PARK': (44.3040816, -105.4491422),
 'TOWN OF HAMPSTEAD': (51.5566155, -0.1782918),
 'TOWN OF MANCHESTER': (42.9694241, -77.2296711),
 'TOWN OF MOUNT AIRY': (42.11259, -73.982913),
 'TOWN OF NEW WINDSOR': (41.4767605, -74.0237519),
 'CITY OF TANEYTOWN': (39.65788, -77.17443),
 'TOWN OF UNION BRIDGE': (39.57327, -77.17455),
 'CITY OF WESTMINSTER': (51.4973206, -0.137149),
 'WAKEFIELD VALLEY': (39.5637122, -77.0344262),
 'BARK HILL': (54.0059746, -2.0967562),
 'GAITHER MANOR APARTMENTS': (None, None),
 'WOODBINE VILLAGE MOBILE HOME PARK': (39.3936332, -77.057585),
 'HILLANDALE MOBILE HOME PARK': (33.3382294, -84.7533846),
 'LAKEVIEW MHP LLC': (None, None),
 'PHEASANT RIDGE ESTATES': (39.0925333, -108.5370636),
 'PLEASANT VIEW NURSING HOME': (42.6226245, -89.6570027),
 'RESERVOIR TRAILER PARK': (25.95904, -109.05496),
 'ROCKBROOK VILLAGE MOBILE HOME PARK': (34.88831, -120.45322),
 'SULLIVANS MOBILE HOME PARK COMMUNITY': (None, None),
 'TAYLORSVILLE MHC, LLC': (None, None),
 'TODD VILLAGE MOBILE HOME PARK': (39.986532, -84.012727),
 'TWIN ARCH MOBILE HOME PARK': (29.69225, -91.17896),
 'TOWN OF ELKTON': (40.735903, -73.326177),
 'ELKTON WEST': (39.5878325, -84.5543932),
 'TOWN OF NORTH EAST': (41.9167594, -73.5662363),
 'PINE HILLS': (28.5825505, -81.4618323),
 'HARBOR VIEW': (41.6933811, -83.4443765),
 'TOWN OF CHARLESTOWN': (44.0233445, -88.0905348),
 'MOUNTAIN HILL WATER COMPANY': (None, None),
 'GOLDEN KAY APARTMENTS': (None, None),
 'GRAYMOUNT APARTMENTS': (None, None),
 'WEST NOTTINGHAM ACADEMY': (39.6680892, -76.0801558),
 'CALVERT MANOR CENTER FOR REHABILITATION': (None, None),
 'BAY COUNTRY ESTATES MOBILE HOME PARK': (41.21778, -95.86557),
 'BENJAMINS VILLAGE/HOMESTEAD M.H.P.': (None, None),
 'CHESAPEAKE ESTATES MOBILE HOME PARK': (41.6109992, -83.5305073),
 'WHISPERING PINES MOBILE HOME PARK': (39.0942793, -75.5171456),
 'CONOWINGO MOBILE HOME PARK': (39.680107, -76.1874537),
 'FOREST GREEN COURT MOBILE HOME PARK': (29.69225, -91.17896),
 'MAPLE HILL MOBILE ESTATES': (37.1254203, -121.6387298),
 'OAK LANE MOBILE HOME PARK': (41.6792576, -87.7062038),
 'PLEASANT HILL MOBILE HOME PARK': (35.1025799, -120.6047422),
 'STONEY CHASE/ ROCK CREEK M.H.P.S': (None, None),
 'TOWN & COUNTRY MOBILE HOME PARK': (40.6906758, -111.9364465),
 'WOODLAWN MOBILE HOME PARK - NEW': (39.63616, -91.09597),
 'TIMBER GROVE MHP': (None, None),
 'MISTY MEADOWS 1 / HIGHLAND HILLS M.H.P.': (None, None),
 'MAYBELLE MANOR MOBILE HOME PARK': (47.16822, -122.47999),
 'MISTY MEADOWS 2 MOBILE HOME PARK': (29.69225, -91.17896),
 'TOWN OF HURLOCK': (38.62669, -75.86395),
 'BRIERCREST APARTMENTS': (None, None),
 'CITY OF BRUNSWICK': (-37.7664715, 144.9613103),
 'FOUNTAINDALE SOUTH': (39.4290106, -77.5143626),
 'CITY OF FREDERICK': (39.4129171, -77.4647867),
 'TOWN OF MIDDLETOWN': (42.169167, -74.610556),
 'MOUNT SAINT MARYS UNIVERSITY': (39.68192, -77.35387),
 'TOWN OF MYERSVILLE': (39.50648, -77.56872),
 'TOWN OF THURMONT': (39.62063, -77.40738),
 'WHITE ROCK': (49.0235357, -122.797924),
 'TOWN OF WOODSBORO': (43.186386, -76.3020244),
 'NEW DESIGN - FREDERICK COUNTY': (39.3076025, -77.4602642),
 'BRADFORD ESTATES': (39.3648258, -77.2291495),
 'CAMBRIDGE FARMS': (39.3666884, -77.5275131),
 'LIBERTYTOWN APARTMENTS': (None, None),
 'COPPERFIELD': (50.912048, -113.9320979),
 'LIBERTYTOWN EAST': (27.23998, 87.14802),
 'SAM HILL ESTATES': (35.9336745, -86.8513896),
 'KNOLLS OF WINDSOR': (42.30008, -83.01654),
 'CONCORD ESTATES MOBILE HOME PARK': (43.138448, -83.693691),
 'GILBERTS MOBILE HOME PARK': (25.8623181, -80.2125481),
 'POLINGS MOBILE HOME PARK': (29.69225, -91.17896),
 'SPRING VIEW MOBILE HOME PARK': (29.69225, -91.17896),
 'TOWN OF ACCIDENT': (55.9552488, -3.1618537),
 'TOWN OF FRIENDSVILLE': (39.66296, -79.40446),
 'WHITE OAK MOBILE HOME PARK': (39.6760217, -75.4903184),
 'MEADOW PARK MOBILE SUBDIVISION': (None, None),
 'MCHENRY WATER SYSTEM': (None, None),
 'CITY OF ABERDEEN': (57.1479628, -2.1057537),
 'MARYLAND AMERICAN WATER COMPANY': (None, None),
 'CAMPUS HILLS WATER WORKS': (18.24834, -78.05343),
 'TOWN OF DARLINGTON': (42.6535398, -90.1122786),
 'GREENRIDGE SUBDIVISION': (None, None),
 'CITY OF HAVRE DE GRACE': (39.54928, -76.09162),
 'LAKESIDE VISTA': (52.1022452, -106.5665644),
 'HARFORD COUNTY D.P.W.': (39.503902, -76.388623),
 'CLEAR VIEW MOBILE HOME PARK LLC': (None, None),
 'FOUNTAIN GREEN MOBILE HOME PARK': (39.52733, -76.2819017),
 'R & R ESTATES': (39.0856667, -76.1255035),
 'QUEENS CASTLE MOBILE HOME PARK': (29.69225, -91.17896),
 'DARLINGTON MOBILE HOME PARK': (34.248986, -80.119683),
 'SWAN HARBOUR DELL MOBILE HOME PARK': (39.52563, -76.14385),
 'VILLAS AT CATTAIL CREEK': (35.75897, -91.13596),
 'TOWN OF CHESTERTOWN': (43.6525664, -73.8009597),
 'TOWN OF POOLESVILLE': (39.14226, -77.41013),
 'CITY OF ROCKVILLE': (14.7011978, 121.0377335),
 'WASHINGTON SUBURBAN SANITARY COMMISSION': (39.0551412, -76.965362),
 'TOWN OF PRINCESS ANNE': (-33.9656031, 18.4585965),
 'HIGHFIELD': (-17.8913239, 30.9860534),
 'BOONSBORO - KEEDYSVILLE': (39.48621, -77.69971),
 'ELK RIDGE LAKE': (39.5227006, -84.4547999),
 'MOUNT AETNA': (44.6353564, -67.3741554),
 'TOWN OF SHARPSBURG': (35.8667846, -77.8295098),
 'SANDY HOOK': (38.0864739, -83.1262839),
 'EL RANCHO MOBILE HOME PARK': (35.0722755, -106.551571),
 'WOODLAND TRAILER PARK': (34.770095, -83.0798755),
 'SAINT JAMES SCHOOL': (53.5606319, -0.0932651),
 'TOWN OF DELMAR': (44.9877679, -90.996622),
 'CITY OF SALISBURY': (-34.7684459, 138.6117546),
 'CITY OF FRUITLAND': (-37.8124129, 145.2499893),
 'GATEWAY VILLAGE MOBILE HOME PARK': (34.88831, -120.45322),
 'BOH-NAK MOBILE HOME PARK': (29.69225, -91.17896),
 'NAYLOR MILL VILLAGE MOBILE HOME PARK': (46.86729, -122.26151),
 'COLONIAL MILL ESTATES MOBILE HOME PARK': (29.69225, -91.17896),
 'HEBRON WOODS MOBILE HOME PARK': (38.5539912, -76.050295),
 'NORTHFIELD APARTMENTS': (42.6763509, -83.1364497),
 'TOWN OF BERLIN': (45.0763209, -89.7857186),
 'OCEAN PINES': (38.3873724, -75.1477233)}

In [9]:
df.loc[df['latitude'].isna(), 'latitude'] = df.loc[df['latitude'].isna(), 'sampling_location'].map(
    lambda x: location_cache.get(x, (None, None))[0]
)

df.loc[df['longitude'].isna(), 'longitude'] = df.loc[df['longitude'].isna(), 'sampling_location'].map(
    lambda x: location_cache.get(x, (None, None))[1]
)

In [10]:
df

,sample_id,sampling_location,data_source,latitude,longitude,sampling_date,pws_id,water_system_name,population,well_type,...,city,county,MRL,DL,analytical_methods,is_detected,analyte,concentration,pfas_total,note
0,FA98605-4,Joint Base Andrews,DoD,38.808876,-76.868786,2022-08-29,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,8.0,QSM_B15,False,4:2FTS,0.0,NaN,NaN
1,FA98605-4,Joint Base Andrews,DoD,38.808876,-76.868786,2022-08-29,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,8.0,QSM_B15,False,6:2FTS,0.0,NaN,NaN
2,FA98605-4,Joint Base Andrews,DoD,38.808876,-76.868786,2022-08-29,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,8.0,QSM_B15,False,8:2FTS,0.0,NaN,NaN
3,FA98605-4,Joint Base Andrews,DoD,38.808876,-76.868786,2022-08-29,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,40.0,QSM_B15,False,NETFOSAA,0.0,NaN,NaN
4,FA98605-4,Joint Base Andrews,DoD,38.808876,-76.868786,2022-08-29,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,8.0,QSM_B15,False,NMEFOSAA,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4549,023-0005-TP05,OCEAN PINES,MDE,38.387372,-75.147723,2022-08-15,MD0230005,NaN,NaN,NaN,...,NaN,WORCESTER,NaN,NaN,NaN,False,N-MEFOSAA,0.0,NaN,Finished
4550,023-0005-TP05,OCEAN PINES,MDE,38.387372,-75.147723,2022-08-15,MD0230005,NaN,NaN,NaN,...,NaN,WORCESTER,NaN,NaN,NaN,False,PFDOA,0.0,NaN,Finished
4551,023-0005-TP05,OCEAN PINES,MDE,38.387372,-75.147723,2022-08-15,MD0230005,NaN,NaN,NaN,...,NaN,WORCESTER,NaN,NaN,NaN,False,PFTDA,0.0,NaN,Finished
4552,023-0005-TP05,OCEAN PINES,MDE,38.387372,-75.147723,2022-08-15,MD0230005,NaN,NaN,NaN,...,NaN,WORCESTER,NaN,NaN,NaN,False,PFTRDA,0.0,NaN,Finished
4553,023-0005-TP05,OCEAN PINES,MDE,38.387372,-75.147723,2022-08-15,MD0230005,NaN,NaN,NaN,...,NaN,WORCESTER,NaN,NaN,NaN,False,PFUNDA,0.0,NaN,Finished

129

In [11]:
df.to_csv('maryland_dw.csv')