In [1]:
import numpy as np
import pandas as pd
import os

In [2]:
os.getcwd()

'/Users/chuqiwang/Documents/US_PFAS_Project/data_merging_analysis'

In [3]:
pd.set_option('display.max_columns', None)

In [4]:
us_pfas_dw = pd.read_csv('us_pfas_dw.csv', index_col=0)

/var/folders/h1/tx5r5g0n5k9cc_fl6nfvt9pc0000gn/T/ipykernel_24303/2150095071.py:1: DtypeWarning: Columns (1,2,7,8,10,15,16,19,20,24) have mixed types. Specify dtype option on import or set low_memory=False.
  us_pfas_dw = pd.read_csv('us_pfas_dw.csv', index_col=0)

In [5]:
us_pfas_dw

,sample_id,sampling_location,data_source,latitude,longitude,sampling_date,pws_id,water_system_name,population,well_type,well_depth,units,source_type,state,city,county,MRL,DL,analytical_methods,is_detected,analyte,concentration,pfas_total,note
0,XJ04025-001,Joint Base Elmendorf-Richardson,DoD,61.270524,-149.697633,2022-09-28,NaN,NaN,NaN,NaN,NaN,ng/L,drinking water,Alaska,NaN,NaN,NaN,3.6,QSM_B15,False,4:2FTS,0.0,NaN,NaN
1,XJ04025-001,Joint Base Elmendorf-Richardson,DoD,61.270524,-149.697633,2022-09-28,NaN,NaN,NaN,NaN,NaN,ng/L,drinking water,Alaska,NaN,NaN,NaN,3.6,QSM_B15,False,6:2FTS,0.0,NaN,NaN
2,XJ04025-001,Joint Base Elmendorf-Richardson,DoD,61.270524,-149.697633,2022-09-28,NaN,NaN,NaN,NaN,NaN,ng/L,drinking water,Alaska,NaN,NaN,NaN,3.6,QSM_B15,False,8:2FTS,0.0,NaN,NaN
3,XJ04025-001,Joint Base Elmendorf-Richardson,DoD,61.270524,-149.697633,2022-09-28,NaN,NaN,NaN,NaN,NaN,ng/L,drinking water,Alaska,NaN,NaN,NaN,3.6,QSM_B15,False,NETFOSAA,0.0,NaN,NaN
4,XJ04025-001,Joint Base Elmendorf-Richardson,DoD,61.270524,-149.697633,2022-09-28,NaN,NaN,NaN,NaN,NaN,ng/L,drinking water,Alaska,NaN,NaN,NaN,3.6,QSM_B15,False,NMEFOSAA,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2494885,117104R,Facility 930 - Booker Road and Cheyenne Road,UCMR5,41.152885,-104.858938,2024-04-22,WY5680122,USAF F.E. WARREN AFB,NaN,NaN,NaN,ng/L,MX,WY,NaN,NaN,4.0,NaN,EPA 533,False,PFOA,0.0,NaN,NaN
2494886,117104R,Facility 930 - Booker Road and Cheyenne Road,UCMR5,41.152885,-104.858938,2024-04-22,WY5680122,USAF F.E. WARREN AFB,NaN,NaN,NaN,ng/L,MX,WY,NaN,NaN,4.0,NaN,EPA 533,False,PFMPA,0.0,NaN,NaN
2494887,117104R,Facility 930 - Booker Road and Cheyenne Road,UCMR5,41.152885,-104.858938,2024-04-22,WY5680122,USAF F.E. WARREN AFB,NaN,NaN,NaN,ng/L,MX,WY,NaN,NaN,2.0,NaN,EPA 533,False,PFUNA,0.0,NaN,NaN
2494888,117104R,Facility 930 - Booker Road and Cheyenne Road,UCMR5,41.152885,-104.858938,2024-04-22,WY5680122,USAF F.E. WARREN AFB,NaN,NaN,NaN,ng/L,MX,WY,NaN,NaN,3.0,NaN,EPA 533,False,PFHXS,0.0,NaN,NaN
2494889,117104R,Facility 930 - Booker Road and Cheyenne Road,UCMR5,41.152885,-104.858938,2024-04-22,WY5680122,USAF F.E. WARREN AFB,NaN,NaN,NaN,ng/L,MX,WY,NaN,NaN,4.0,NaN,EPA 533,False,PFOS,0.0,NaN,NaN

In [6]:
len(us_pfas_dw['sampling_location'].unique())

24944

In [7]:
us_pfas_dw[us_pfas_dw['sample_id'].isnull()]

,sample_id,sampling_location,data_source,latitude,longitude,sampling_date,pws_id,water_system_name,population,well_type,well_depth,units,source_type,state,city,county,MRL,DL,analytical_methods,is_detected,analyte,concentration,pfas_total,note
1617,NaN,NaN,GAMA-Division of Drinking Water,40.524780,-122.300008,2019-09-30,NaN,NaN,NaN,Municipal,NaN,ng/L,drinking water,California,NaN,NaN,2.0,NaN,NaN,False,PFTRDA,0.0,NaN,EUROFINS EATON ANALYTICAL (MONROVIA)
1618,NaN,NaN,GAMA-Division of Drinking Water,40.524780,-122.300008,2019-12-16,NaN,NaN,NaN,Municipal,NaN,ng/L,drinking water,California,NaN,NaN,2.0,NaN,NaN,False,PFNA,0.0,NaN,EUROFINS EATON ANALYTICAL (MONROVIA)
1619,NaN,NaN,GAMA-Division of Drinking Water,37.686871,-121.878026,2019-10-07,NaN,NaN,NaN,Municipal,NaN,ng/L,drinking water,California,NaN,NaN,0.0,NaN,NaN,True,PFHXA,5.8,NaN,EUROFINS EATON ANALYTICAL (MONROVIA)
1620,NaN,NaN,GAMA-Division of Drinking Water,37.685681,-121.837888,2019-10-08,NaN,NaN,NaN,Municipal,NaN,ng/L,drinking water,California,NaN,NaN,2.0,NaN,NaN,False,PFHPA,0.0,NaN,EUROFINS EATON ANALYTICAL (MONROVIA)
1621,NaN,NaN,GAMA-Division of Drinking Water,37.685681,-121.837888,2019-07-08,NaN,NaN,NaN,Municipal,NaN,ng/L,drinking water,California,NaN,NaN,0.0,NaN,NaN,True,PFHXS,14.0,NaN,EUROFINS EATON ANALYTICAL (MONROVIA)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1357113,NaN,Montesano,PPL,46.981206,-123.602662,2018-01-01,NaN,NaN,NaN,NaN,NaN,ng/L,Drinking Water,Washington,NaN,NaN,NaN,NaN,NaN,NaN,PFOS,NaN,1.0,NaN
1357114,NaN,Hayward TNG Site,PPL,NaN,NaN,2018-01-01,NaN,NaN,NaN,NaN,NaN,ng/L,Drinking Water,Wisconsin,NaN,NaN,NaN,NaN,NaN,NaN,PFOA,NaN,1.0,NaN
1357115,NaN,Hayward TNG Site,PPL,NaN,NaN,2018-01-01,NaN,NaN,NaN,NaN,NaN,ng/L,Drinking Water,Wisconsin,NaN,NaN,NaN,NaN,NaN,NaN,PFOS,NaN,1.0,NaN
1357116,NaN,Camp Guernsey,PPL,49.454740,-2.576290,2018-01-01,NaN,NaN,NaN,NaN,NaN,ng/L,Drinking Water,Wyoming,NaN,NaN,NaN,NaN,NaN,True,PFOA,1.0,7.0,NaN
1357117,NaN,Camp Guernsey,PPL,49.454740,-2.576290,2018-01-01,NaN,NaN,NaN,NaN,NaN,ng/L,Drinking Water,Wyoming,NaN,NaN,NaN,NaN,NaN,NaN,PFOS,NaN,7.0,NaN

In [8]:
us_pfas_dw[us_pfas_dw['data_source']=='PPL']

,sample_id,sampling_location,data_source,latitude,longitude,sampling_date,pws_id,water_system_name,population,well_type,well_depth,units,source_type,state,city,county,MRL,DL,analytical_methods,is_detected,analyte,concentration,pfas_total,note
1356864,NaN,77 Same Old Road,PPL,58.415451,-135.706680,2019-01-01,NaN,NaN,NaN,NaN,NaN,ng/L,Drinking Water,Alaska,NaN,NaN,NaN,NaN,NaN,True,PFOA,53.0,NaN,NaN
1356865,NaN,77 Same Old Road,PPL,58.415451,-135.706680,2019-01-01,NaN,NaN,NaN,NaN,NaN,ng/L,Drinking Water,Alaska,NaN,NaN,NaN,NaN,NaN,True,PFOS,11500.0,NaN,NaN
1356866,NaN,Alcantra Armory Complex,PPL,61.603138,-149.374607,2018-01-01,NaN,NaN,NaN,NaN,NaN,ng/L,Drinking Water,Alaska,NaN,NaN,NaN,NaN,NaN,NaN,PFOA,NaN,1.0,NaN
1356867,NaN,Alcantra Armory Complex,PPL,61.603138,-149.374607,2018-01-01,NaN,NaN,NaN,NaN,NaN,ng/L,Drinking Water,Alaska,NaN,NaN,NaN,NaN,NaN,NaN,PFOS,NaN,1.0,NaN
1356868,NaN,Bloom Enterprises Fire,PPL,NaN,NaN,2019-01-01,NaN,NaN,NaN,NaN,NaN,ng/L,Drinking Water,Alaska,NaN,NaN,NaN,NaN,NaN,True,PFOA,3.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1357113,NaN,Montesano,PPL,46.981206,-123.602662,2018-01-01,NaN,NaN,NaN,NaN,NaN,ng/L,Drinking Water,Washington,NaN,NaN,NaN,NaN,NaN,NaN,PFOS,NaN,1.0,NaN
1357114,NaN,Hayward TNG Site,PPL,NaN,NaN,2018-01-01,NaN,NaN,NaN,NaN,NaN,ng/L,Drinking Water,Wisconsin,NaN,NaN,NaN,NaN,NaN,NaN,PFOA,NaN,1.0,NaN
1357115,NaN,Hayward TNG Site,PPL,NaN,NaN,2018-01-01,NaN,NaN,NaN,NaN,NaN,ng/L,Drinking Water,Wisconsin,NaN,NaN,NaN,NaN,NaN,NaN,PFOS,NaN,1.0,NaN
1357116,NaN,Camp Guernsey,PPL,49.454740,-2.576290,2018-01-01,NaN,NaN,NaN,NaN,NaN,ng/L,Drinking Water,Wyoming,NaN,NaN,NaN,NaN,NaN,True,PFOA,1.0,7.0,NaN
1357117,NaN,Camp Guernsey,PPL,49.454740,-2.576290,2018-01-01,NaN,NaN,NaN,NaN,NaN,ng/L,Drinking Water,Wyoming,NaN,NaN,NaN,NaN,NaN,NaN,PFOS,NaN,7.0,NaN

In [9]:
def generate_sample_id(row):
    if pd.notnull(row['sampling_location']):
        # If sampling_location exists, combine it with the sampling_date
        return f"{row['sampling_date']}_{row['sampling_location']}"
    elif pd.notnull(row['latitude']) and pd.notnull(row['longitude']):
        # If latitude and longitude exist, combine them with the sampling_date
        return f"{row['sampling_date']}_{row['latitude']}_{row['longitude']}"
    elif pd.notnull(row['pws_id']):
        # If sampling_location, latitude, and longitude are null, use pwd_id
        return f"{row['sampling_date']}_{row['pws_id']}"
    else:
        # If none of the above exist, return NaN (no way to generate ID)
        return np.nan

In [10]:
# Fill only rows where 'sample_id' is currently null
us_pfas_dw.loc[us_pfas_dw['sample_id'].isnull(), 'sample_id'] = (
    us_pfas_dw[us_pfas_dw['sample_id'].isnull()]
    .apply(generate_sample_id, axis=1)
)

In [11]:

# Check for null sample_id after generation
rows_with_null_sample_id = us_pfas_dw[us_pfas_dw['sample_id'].isnull()]

In [12]:
rows_with_null_sample_id

Empty DataFrame
Columns: [sample_id, sampling_location, data_source, latitude, longitude, sampling_date, pws_id, water_system_name, population, well_type, well_depth, units, source_type, state, city, county, MRL, DL, analytical_methods, is_detected, analyte, concentration, pfas_total, note]
Index: []

In [13]:
us_pfas_dw[us_pfas_dw['sampling_date'].isnull()]

Empty DataFrame
Columns: [sample_id, sampling_location, data_source, latitude, longitude, sampling_date, pws_id, water_system_name, population, well_type, well_depth, units, source_type, state, city, county, MRL, DL, analytical_methods, is_detected, analyte, concentration, pfas_total, note]
Index: []

In [14]:
us_pfas_dw

,sample_id,sampling_location,data_source,latitude,longitude,sampling_date,pws_id,water_system_name,population,well_type,well_depth,units,source_type,state,city,county,MRL,DL,analytical_methods,is_detected,analyte,concentration,pfas_total,note
0,XJ04025-001,Joint Base Elmendorf-Richardson,DoD,61.270524,-149.697633,2022-09-28,NaN,NaN,NaN,NaN,NaN,ng/L,drinking water,Alaska,NaN,NaN,NaN,3.6,QSM_B15,False,4:2FTS,0.0,NaN,NaN
1,XJ04025-001,Joint Base Elmendorf-Richardson,DoD,61.270524,-149.697633,2022-09-28,NaN,NaN,NaN,NaN,NaN,ng/L,drinking water,Alaska,NaN,NaN,NaN,3.6,QSM_B15,False,6:2FTS,0.0,NaN,NaN
2,XJ04025-001,Joint Base Elmendorf-Richardson,DoD,61.270524,-149.697633,2022-09-28,NaN,NaN,NaN,NaN,NaN,ng/L,drinking water,Alaska,NaN,NaN,NaN,3.6,QSM_B15,False,8:2FTS,0.0,NaN,NaN
3,XJ04025-001,Joint Base Elmendorf-Richardson,DoD,61.270524,-149.697633,2022-09-28,NaN,NaN,NaN,NaN,NaN,ng/L,drinking water,Alaska,NaN,NaN,NaN,3.6,QSM_B15,False,NETFOSAA,0.0,NaN,NaN
4,XJ04025-001,Joint Base Elmendorf-Richardson,DoD,61.270524,-149.697633,2022-09-28,NaN,NaN,NaN,NaN,NaN,ng/L,drinking water,Alaska,NaN,NaN,NaN,3.6,QSM_B15,False,NMEFOSAA,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2494885,117104R,Facility 930 - Booker Road and Cheyenne Road,UCMR5,41.152885,-104.858938,2024-04-22,WY5680122,USAF F.E. WARREN AFB,NaN,NaN,NaN,ng/L,MX,WY,NaN,NaN,4.0,NaN,EPA 533,False,PFOA,0.0,NaN,NaN
2494886,117104R,Facility 930 - Booker Road and Cheyenne Road,UCMR5,41.152885,-104.858938,2024-04-22,WY5680122,USAF F.E. WARREN AFB,NaN,NaN,NaN,ng/L,MX,WY,NaN,NaN,4.0,NaN,EPA 533,False,PFMPA,0.0,NaN,NaN
2494887,117104R,Facility 930 - Booker Road and Cheyenne Road,UCMR5,41.152885,-104.858938,2024-04-22,WY5680122,USAF F.E. WARREN AFB,NaN,NaN,NaN,ng/L,MX,WY,NaN,NaN,2.0,NaN,EPA 533,False,PFUNA,0.0,NaN,NaN
2494888,117104R,Facility 930 - Booker Road and Cheyenne Road,UCMR5,41.152885,-104.858938,2024-04-22,WY5680122,USAF F.E. WARREN AFB,NaN,NaN,NaN,ng/L,MX,WY,NaN,NaN,3.0,NaN,EPA 533,False,PFHXS,0.0,NaN,NaN
2494889,117104R,Facility 930 - Booker Road and Cheyenne Road,UCMR5,41.152885,-104.858938,2024-04-22,WY5680122,USAF F.E. WARREN AFB,NaN,NaN,NaN,ng/L,MX,WY,NaN,NaN,4.0,NaN,EPA 533,False,PFOS,0.0,NaN,NaN

In [15]:
us_pfas_dw.to_csv('us_pfas_dw.csv')